### ISSUE TITLE
Let's find a great name for this project!

### ISSUE THREAD

**Issue by munen** [200ok-ch/organice#1]
We're going to make this a biiig project. Therefore it'll be great to have a good name.

Ideas *should* contain the phrase *org*, unless they don't.

Generally good options:

- Made up names (containing *org*)
- A verb with a noun
- A word from just another language (containing *org*)

The winner get's something. I don't know what, yet, but it'll be a small personal gift. Plus, I'll personally get a designer to create a sweet logo. And the world will be eternally grateful!

**Comment by munen** [comment]
Suggestion Alain: *Organ*

Why?

- You can play an organ like an instrument (because it is)
- An organ has many buttons and functionality and sounds awesome (just
  like Emacs)
- Org is as vital to the functioning of me as an organ(;

Logo can be a literal organ.

**Comment by munen** [comment]
Suggestion Alain: **Orgaku**

Why?

From the story line he could be an ancient Zen master. 

- "The master does nothing and leaves nothing undone"
- "The master climbed the high seat. 3min silence. Katz!!"


Logo could be an old, little fat guy with a stick. A little comic style, but still serious

**Downsides**

Marcel says it's hard to pronounce (both for English people and for Japanese).

**Comment by munen** [comment]
Suggestions Marcel:

- BigOrg
- OrgMaster

**Comment by munen** [comment]
Suggestion Alex:

- Cyborg

**Comment by branch14** [comment]
## Suggestions Phil:

- `organza` because its a very light fabric - a "web" of fibers or threads, so in a way it has `org` **and** `web` (`organdy` is an alternative)
- `orgtastic` because is will be org and fantastic
- `organic` because that's really hard to google for, "org[mode][p]anic"
- `go-brew` because it is an anagram of orgweb and makes me think of beer, and beer I like
- `ogre-scam` because it is an anagram of `emacs org` and _ogre scams_ are probably hilarious
- `womacs` because it runs on the `w`eb, it is about `o`rg, and it (to some extent) has the `MACroS` part ot "Editor MACroS" which is what `Emacs` stands for, plus it sounds very inclusive :)

## Some names with `org`:

- `morgan`
- `george`,
- `gorgio`

## Other great words with `org`, that I haven't found a good reason for:

- `forge`
- `borg`
- `cyborg`
- `gorgonzola`

**Comment by munen** [comment]
Suggestion Luca: OrgIt

Alternative: Something with a `.now` domain.

He bought it.now - with the idea that you can do many things like eat.it.now. Maybe we could even organize.it.now?

**Comment by munen** [comment]
@branch14 Thank you so much for the many great ideas! 🙏🏻🙇🏻‍♂️

**Comment by munen** [comment]
Nico and Sanghee liked „Organ“. However, I didn’t pitch them the big great list from @branch14, because I unfortunately  didn’t read that, yet.

**Comment by munen** [comment]
Suggestion Alex: Organizm

**Comment by branch14** [comment]
Suggestion Sophia: organice / "org_a_nice"

**Comment by munen** [comment]
Suggestion Alex: Corgi

**Comment by alphapapa** [comment]
Two important, related criteria are relative uniqueness and ease of finding on search engines.  Names like `george`, `forge`, `organ`, etc. are neither distinctive nor descriptive, and will return many unrelated results on Google.

* I think `organice` is actually not bad, however there are many results on Google for other things, so it may not be the best choice.
* `organdy` is a nice-sounding word, like "burgandy."  It appears to be a type of fabric, and search results for it seem primarily confined to the fabric.  I don't see any search results for adding terms like `emacs` or `computers`, so it might be a good choice in this context.
* `gorgonzola` would be a hilarious name, though slightly repulsive (Google results include "the maggot-ridden history of..."), and non-descriptive.

Naming things is hard.  :)

**Comment by munen** [comment]
Naming things is hard, indeed^^

Thank you for your very welcome and accurate input!

**Comment by munen** [comment]
I'm very happy with all the contributions and the final name `organice`. Thank you all for your help! :pray: :bowing_man: 

Let's keep working hard on `organice` and make it a viable option for Org mode afficianados all over the world :confetti_ball:
