### ISSUE TITLE
Documentation of swipe functions 

### ISSUE THREAD

**Issue by BrianZbr** [200ok-ch/organice#1004]
**Is your feature request related to a problem? Please describe.**
I'm looking for documentation that explains what exactly the right and swipe functions do and I'm not finding it. I'm guessing the left swipe deletes but have no idea what the right swipe does. I had a look at thee documentation but couldn't find an explanation.

EDIT: I eventually figured out that left swipe is supposed to cycle the TODO state.

**Describe the solution you'd like**
I'm hoping someone who is already familiar with how this works can make an update to the documentation or point me to what I'm missing.

**Comment by munen** [comment]
Hi @BrianZbr 

Thank you for checking out organice :pray: 

The docs do include both swipes:

![image](https://github.com/user-attachments/assets/fc5c895f-99f7-42b7-9333-2fc8956606dd)

![image](https://github.com/user-attachments/assets/8a15f299-ecfe-4d96-aaa6-a70379372f23)

If you have a proposal on how to improve upon the existing documentation, I'd be happy to pull in your changes!

Does this answer your question?

**Comment by BrianZbr** [comment]
Ah, thank you! Where exactly would I find that?

This is the documentation I was looking at and I still don't see that here: https://organice.200ok.ch/documentation.html

**Comment by munen** [comment]
No worries, feel free to ask any question any time :pray:
