### ISSUE TITLE
Generate page from github ?

### ISSUE THREAD

**Issue by olymk2** [200ok-ch/organice#102]
Be nice if you could proxy a file in github through this app in some way, even if editing was not possible.

Although allowing edit and creating a pr or commit on a repo would also be an awesome feature :)

guessing this is not possible currently so more an idea.

**Comment by munen** [comment]
@olymk2 As I understand you're asking organice to be a git porcelain like Magit? If so, this is not in the scope of organice similarly like Org mode and Magit are different major modes in Emacs.

Or did you have something different in mind?

**Comment by olymk2** [comment]
I waws thinking mainly as a viewer for files in git, so i could pass it  url like gihub.org/project/readme.org and it would render it out an I could send that link on to other people as a way of viewing the file.

but then i was thinking morer out of scope and it would be nice if people could upddate and create a pr, basically a way to allow none emacs users to up date org documentation, but i understand that's way out of scope, just thought i would make the suggestion :)

**Comment by munen** [comment]
Thanks for the suggestion in any case and for your quick clarification!

I’d say this is out of the scope of organice, though. Personally, I’m happy that GH itself renders Org files nicely, too^^
