### ISSUE TITLE
Don't insert extra newlines in block without content

### ISSUE THREAD

**Issue by jamesnvc** [200ok-ch/organice#105]
I'm not sure if this is by design, but I prefer that a header without a body wouldn't insert extra newlines.

e.g. I would like

```org
* Foo
** Bar
   :LOGBOOK:
   CLOCK: [2019-11-11 Mon 13:12]--[2019-11-12 Tue 13:12] => 24:00
   :END: 
** Baz
```

but organice exports like

```org
* Foo
** Bar
   :LOGBOOK:
   CLOCK: [2019-11-11 Mon 13:12]--[2019-11-12 Tue 13:12] => 24:00
   :END:
 
** Baz
```

Would a PR for this be acceptable, or is this intended behaviour?

**Comment by munen** [comment]
> Would a PR for this be acceptable, or is this intended behaviour?

Very acceptable, indeed.

Thank you for coming up with a PR right away, too! :pray:  

Happy to say it's merged and I updated the changelog with your contribution: https://github.com/200ok-ch/organice/commit/4a757fa35d307a392419415d1820bed0486e442a
