### ISSUE TITLE
FR: Docker

### ISSUE THREAD

**Issue by gerroon** [200ok-ch/organice#114]
Hi

It would be nice if there is an official Docker provided.

**Comment by munen** [comment]
Hi @gerroon 

Thanks for the request. In other projects I'm using Docker _a lot_. However, I have never seen a simple front-end application that has no back-end in a Docker container. Are there popular precedents? If there are, I'm happy to follow along. Otherwise, it feels like an anti-pattern(;

**Comment by gerroon** [comment]
User convenience and avoiding nodejs yarn etc. I personally block all the nodejs repos because those node apps contantly pounding my local dns servers for whatever reason.

**Comment by munen** [comment]
Yes, those are the general selling proposition points for Docker. However, is there precedence for front-end only applications? I've never seen this and it feels like overkill to me. However, by precedence and convention, I can be persuaded, of course.

As for the 'right node version', that would only be for developers of Javascript. And for them, there's a nice `.nvmrc` file in the root directory as is customary.

**Comment by munen** [comment]
NB: I'm also reluctant, because there's already two canonical places for the node version: The nvmrc file and the deployment to Heroku. As always with competing standards, adding more of them doesn't only help(;

If you're interested in building a Dockerfile, I'd be in favor if we also get rid of the Heroku deployment documentation (and related configuration) in favor of deployment information using Docker.

**Comment by gerroon** [comment]
Well, I can't build the Docker file since I intentionally block all the Nodejs repos :) 

I am personally not interested in building node apps since I had very toxic expreriences in the past with building those including version mismatches, dependency hells on Debian. However I would be more than happy to use this app if there is a Docker or Snap version available.

thanks

**Comment by munen** [comment]
Well, if you're not planning on developing on organice and hate Nodejs with a passion, then you can just use the free version https://organice.200ok.ch

Enjoy^^

**Comment by gerroon** [comment]
I am not a developer, just a user.
