### ISSUE TITLE
Sign in with WebDAV on Nextcloud fails

### ISSUE THREAD

**Issue by benjaminbauer** [200ok-ch/organice#117]
When trying to sign in [here](https://organice.200ok.ch/sign_in) with WebDAV I get an error

> There was an error retreiving files

Can I debug that further?

**Comment by munen** [comment]
@benjaminbauer Yes, you can. Open your browsers console (preferably Firefox or Chrome) and look at the output there.

Initial hunch: You haven't yet setup your NextCloud instance to allow logins via JavaScript from organice.200ok.ch and you will see a CORS error. If you do, here's the relevant documentation for you: https://github.com/200ok-ch/organice/#webdav

**Comment by rosetree** [comment]
Thank you for providing this interesting project! I have a similar issue right now, though I think I configured my server to send the correct CORS headers. I’m not sure how I can setup my Nextcloud instance to allow logins via JavaScript. Can you point to a documentation, where this is explained, @munen? That would be great.

**Comment by munen** [comment]
Thank you for the kind words, @rosetree 

As I wrote in the comment just above yours, here's the relevant documentation for you: https://github.com/200ok-ch/organice/#webdav

The documentation includes the necessary CORS headers and a screencast showing you how to check if you have them configured.

**Comment by rosetree** [comment]
Thanks for your reply! I’m sorry, if my question seemed redundant. In your comment above mine you wrote that an error happens if “you haven't yet setup your NextCloud instance to allow logins via JavaScript from organice.200ok.ch”. It appeared to me, that you were referring to an security configuration in the NextCloud backend, that must be set to allow the login via JavaScript, in addition to the CORS settings. I followed the documentation you linked, to set the CORS headers (and can see them being set in the developer console); but had no success yesterday.

**Comment by munen** [comment]
Hi @rosetree

I'm sorry to hear that you still cannot log in to your Nextcloud instance via organice. You're in luck, though. @runejuhl just kindly contributed documentation on how to configure Nextcloud+haproxy to allow WebDAV: https://github.com/200ok-ch/organice#configuring-nextcloud-behind-haproxy-to-allow-webdav

I hope this helps. In any case: Good luck to you! 🍀

**Comment by davidszpak** [comment]
Here is how I got organice to access my Nextcloud WebDAV:

1. I installed organice via docker and used nginx/letsencrypt to create a subdomain that I can access with SSL encryption. Let's call this `https://organice.mydomain.com`
2. My Nextcloud instance runs in docker and is setup to use nginx. The following should apply to Apache as well with necessary changes.

I edited the nginx config and inserted the following inside the location section starting with `location ~ ^\/(?:index|remote|public|cron|core\/ajax\/update|status|ocs\/v[12]|updater\/.+|oc[ms]-provider
\/.+)\.php(?:$|\/) { `

```
add_header "Access-Control-Allow-Origin" https://organice.mydomain.com always;
add_header "Access-Control-Allow-Methods" "GET, HEAD, POST, PUT, OPTIONS, MOVE, DELETE, COPY, LOCK, UNLOCK, PROPFIND" always;
add_header "Access-Control-Allow-Headers" "Authorization, Origin, X-Requested-With, Content-Type, Accept, DNT, X-CustomHeader, Keep-Alive,User-Agent, X-Requested-With, If-Modified-Since, Cache-Control, Content-Range, Range, Depth" always;
```

3. After editing, I restarted the docker container and my https://organice.mydomain.com was able to access via WebDAV using:
```
URL: https://nextcloud.mydomain.com/remote.php/dav/files/username/
User: [user]
Pass: [pass]
```

**Comment by jt196** [comment]
@davidszpak - tried adding this section to my Nginx config and it actually broke my Nextcloud setup. 

My only locations in my nginx config are the / location and carddav, caldav and error locations. 

Any help with adding a correct nginx location, assuming that's the problem? I'm on/off studying a this stuff but haven't got too far into the nginx/webserver stuff.

**Comment by joeforan** [comment]
In addition to 
(1) The [solution](https://github.com/200ok-ch/organice/issues/117#issuecomment-636348985)  from @davidszp 
I found I also had to 
(2) Install the [Webapppassword](https://apps.nextcloud.com/apps/webapppassword) app in nextcloud and add the following to the Allowed Origins
```
http://organice.mydomain.com,https://organice.mydomain.com
```
Neither of these measures on their own was sufficient, I found I needed both.

**Comment by munen** [comment]
@joeforan Thank you for adding this information!

Would you like to make it available as documentation in the `contrib` directory for organice? https://github.com/200ok-ch/organice/tree/master/contrib
