### ISSUE TITLE
PWA implementation is broken

### ISSUE THREAD

**Issue by dotcs** [200ok-ch/organice#134]
**Describe the bug**
Organice's implemenation of PWA is broken. It is currently not installable on Android (and likely on iOS) and on Linux operating systems.

**To Reproduce**
1. Go to https://organice.200ok.ch/
2. Check your browser's status bar and see if the "Install organice" button appears.

**Expected behavior**
The install button should appear, but it is missing. It should look like this: 
![image](https://user-images.githubusercontent.com/3976183/70540310-4c103980-1b65-11ea-970b-6b25be6ab69b.png)

**Desktop (please complete the following information):**
 - OS: `Linux mali 4.19.84-1-MANJARO #1 SMP PREEMPT Wed Nov 13 00:07:37 UTC 2019 x86_64 GNU/Linux`
 - Browser: Firefox, Chrome (latest versions)

**Smartphone (please complete the following information):**
 - Device: Pixel 2
 - OS: Android
 - Browser: Chrome, Brave

**Additional context**
I have found the root cause for this. It seems that PWA's require to have two icons with a) 192x192 and b) 512x512 pixel sizes in order to a) installable and b) provide a splash screen while loading. Both icons are currently not available.

To check open `Chromium -> Developer Tools -> Audit` and run an audit on Progressive Web Apps. This should look like this:

![image](https://user-images.githubusercontent.com/3976183/70540733-10c23a80-1b66-11ea-9f16-079b3e71cd84.png)

The audit then lists the findings as follows:

![organice-pwa-issue](https://user-images.githubusercontent.com/3976183/70540005-c3919900-1b64-11ea-83a1-fd3742b79a7b.png)

I am working on a solution for this bug.

**Comment by munen** [comment]
Great bug report!

Looks like Android and Firefox are quite finicky with respect to PWAs. We just finished a ticket where the PWA functionality didn't work on those: https://github.com/200ok-ch/organice/issues/89

Awesome that you described how you debugged the problem! I was not aware that Chromium has this functionality. As an iOS user, for the last issue I was relying on feedback from Android users.

The [logo](https://github.com/200ok-ch/organice/blob/master/public/organice.png) is available in 1863 x 1861, so providing a logo in at least 512px and 192px should be feasible(;

Thank you for reporting and taking care of the issue! :pray: :bowing_man:

**Comment by dotcs** [comment]
@munen Thanks for the kind words. I appreciate it.

These audit features are absolutely great! Glad that I could show you that those exist. :+1: 

In the PR I have changed display from `standalone` to `fullscreen`. I have tested various settings and found this most attractive because it gives maximum space to the application. Let me know if this is fine for you as well.

**Comment by dotcs** [comment]
@munen Can this PR be merged from your side or does it require any more work from my side?

**Comment by munen** [comment]
> These audit features are absolutely great! Glad that I could show you that those exist. +1

Generally speaking, I did know about them. However, since they are not really open source[1], I don't have access to them on Debian. It's a little bit of a pain topic between how Google and Debian operates.

Hence, this is the first time I've seen them in action. Thanks for showing me!(;

1. https://github.com/GoogleChrome/lighthouse/issues/7246#issuecomment-507061573
