### ISSUE TITLE
Suggestion list for inputs in property editor

### ISSUE THREAD

**Issue by schoettl** [200ok-ch/organice#143]
To minimize typing and typos, a smart completion for property names and values in the PropertyListEditorModal would be useful.

**Solution**
- [ ] the suggestion list for property names should contain all property names of the org file
- [ ] the suggestion list for a property value should contain all values of the same property in the org file

**Implementation**
Add a `list=` attribute in the `<input>`s and an associated `<datalist>`.

**Problem**
As far as I see, the index.js for PropertyListEditorModal has no knowledge about other properties in the file. So, an additional argument must be passed to the modal.

**Comment by munen** [comment]
Implemented by @schoettl in https://github.com/200ok-ch/organice/pull/144

:pray: :bowing_man:
