### ISSUE TITLE
#+TODO lines not parsed unless before first headline

### ISSUE THREAD

**Issue by aspiers** [200ok-ch/organice#151]
I have a fairly complex configuration for my `TODO` keywords.  I have `org-todo-keywords` customised to:

```elisp
((sequence "NEXT(n)" "STARTED(>)" "|" "DONE(d)")
 (sequence "PROJECT(p)" "PROJDONE(P)")
 (sequence "ONGOING(o)" "WAITING(w@)" "CHASE(C@)" "|")
 (sequence "SOMEDAY(s)" "MAYBE(m)" "|" "CANCELLED(c)"))
```

Since organice does not know about elisp configuration, I added this to near the bottom of my `TODO.org`:

```org
* org-mode settings
*** TODO keywords
#+TODO: NEXT(n) STARTED(>) | DONE(d)
#+TODO: PROJECT(p) PROJDONE(P)
#+TODO: ONGOING(o) WAITING(w@) CHASE(C@) |
#+TODO: SOMEDAY(s) MAYBE(m) | CANCELLED(c)
```

However it seems to have no impact on organice.  All the above keywords are treated like normal headline text.  Upon further experimentation I isolated some issues which contribute to the problem:

1. The `(x)` keyboard shortcuts are not parsed separately, and are treated as part of the keywords. (**UPDATE: filed as #184**)

2. The `#+TODO` lines need to be at the top of the file.  If I put them under a headline anywhere, they cease to take effect.  This differs to Org's behaviour, and prevents us from being able to tuck them out of sight in order to keep the file tidy.

On the plus side, I did note that `|` seems to be handled correctly.

**Desktop (please complete the following information):**
 - OS: openSUSE Linux
 - Browser: Chrome 79

**Smartphone (please complete the following information):**
 - Device: OnePlus 5T
 - OS: Android 9.0.x
 - Browser Brave

**Comment by munen** [comment]
Thank you for your well defined bug report!

As I understand it, your configuration will be parsed correctly if it is placed on top of the very beginning of the file. If so, then this is a known and (likely imperfectly) documented restriction of the current parser: https://github.com/200ok-ch/organice/blob/master/README.org#current-restrictionsexpectations-of-organice

Refactoring this behavior in the current parser will be very hard. Hence, the work on a completely new and platform agnostic parser in the sister project: https://github.com/200ok-ch/org-parser

If your configuration parsed well on the top of the file, I propose to close the bug. I can’t test right now, because I’m traveling for Christmas and didn’t bring my laptop. If you have a suggestion on how to improve the documentation regarding this constraint, I’ll happily pull in your requested changes^^

**Comment by aspiers** [comment]
[**@munen**](https://github.com/munen) commented on [December 25, 2019 9:18 AM](https://github.com/200ok-ch/organice/issues/151#issuecomment-568872280 "2019-12-25T09:18:41Z - Replied by Github Reply Comments"):
> As I understand it, your configuration will be parsed correctly if it is placed on top of the very beginning of the file.

Sadly not - the `(x)` keyboard shortcut suffices also break it.

> If so, then this is a known and (likely imperfectly) documented restriction of the current parser: [/README.org@`master`#current-restrictionsexpectations-of-organice](https://github.com/200ok-ch/organice/blob/master/README.org#current-restrictionsexpectations-of-organice)

Yes you are right; AFAICS the docs do not explicitly state that in-buffer settings only works at the top of the file.  The closest I can find is this hint:

> After potential in-buffer settings, your Org file has to begin with a headline.

but that doesn't explicitly rule out placing in-buffer settings lower down.
 
> Refactoring this behavior in the current parser will be very hard.

You mean that adding support for `#+TODO` etc. anywhere but the top of the file would be hard?  I would have thought it would be easy to add a first-phase pass to the parser which scans for these lines anywhere in the file, but I guess the challenge is in the need to preserve the position of these lines when writing out the file later - is that right, or is it some other challenge?

> If your configuration parsed well on the top of the file, I propose to close the bug. 

It didn't unfortunately - that was one of the first things I tested, which led me to discover the issue with `(x)` suffix.

> If you have a suggestion on how to improve the documentation regarding this constraint, I’ll happily pull in your requested changes^^

Sure - I'll come up with something :-)

**Comment by munen** [comment]
Sorry to hear that the parser doesn't work for you - even with the known restriction. Great that you want to tackle it!

> Sadly not - the (x) keyboard shortcut suffices also break it.

Can you elaborate a little what happens and what your expectations are? I apologize, but I don't know what you're referencing with `(x)` shortcut.

> but that doesn't explicitly rule out placing in-buffer settings lower down.

Documentation is hard^^ I'm personally happy how much documentation I did get to write over the last months, though*g*

I added this line to the known restrictions: https://github.com/200ok-ch/organice/commit/d2115888510e1722297ad658ad5d71215cbbefc3

Would that have made it clearer? If not, can you provide a different wording, please? Feel free to rephrase the whole section if that helps getting the point across!

> I would have thought it would be easy to add a first-phase pass to the parser which scans for these lines anywhere in the file, but I guess the challenge is in the need to preserve the position of these lines when writing out the file later - is that right, or is it some other challenge?

You mentioned both challenges:

1. The current parser doesn't pass multiple times. I'm sure it can be rewritten to do it, of course. I don't know how long a pass takes for a longer file, but if we're passing multiple times for just one feature, it would be nice if we could add a first performance related test.

2. My primary goal when starting to work on the original org-web was to make the parser not change a single byte if there was no user induced change. That's a USP compared to other Org mode related tools like Beorg. Having said that, the current parser is still inherited from org-web. It does not track the position of tokens within the Org file. It parses and exports only semantically.

Again, the change is certainly possible, but it might be a bit more involved than a trivial fix.

> Sure - I'll come up with something :-)

Good luck and happy hacking! :+1:

**Comment by munen** [comment]
I propose to re-phrase the issue to "Parse in-buffer settings settings anywhere in the Org file", remove the bug and add a feature label.

I realize that compared to Emacs Org mode, the current behavior is a bug. However, then every new feature which is not yet implemented, but Org mode understands is a bug(;

Having said that, I didn't understand the `(x)` shortcuts topic. Maybe we're talking about a bug and a new feature here. If they are implemented with the same code, we can just keep the one issue, of course. But if they are two separate things, we can also pull them apart if that helps focusing on one thing. I don't have a preference, I'm just making suggestions in case they help you get started without tackling a too big task for your first PR^^

**Comment by aspiers** [comment]
> Having said that, I didn't understand the `(x)` shortcuts topic. Maybe we're talking about a bug and a new feature here.

Nope, two features, or two bugs depending on your PoV 😜 Please see the sample config I have in my initial report, plus this: https://orgmode.org/manual/Fast-access-to-TODO-states.html#Fast-access-to-TODO-states

I'm talking about the suffixes after each keyword. 

> If they are implemented with the same code, we can just keep the one issue, of course. But if they are two separate things, we can also pull them apart if that helps focusing on one thing. I don't have a preference, I'm just making suggestions in case they help you get started without tackling a too big task for your first PR^^

I think it definitely makes sense to split them.

**Comment by munen** [comment]
Nice, fast access to todo states is actually a sweet function!

I didn't know it before, but I do see myself integrating this into my workflow. Thank you for sharing!

**Comment by munen** [comment]
> I think it definitely makes sense to split them.

Since you're in the lead for this, I'll defer this to you. I would have written the new feature request for 'fast access to todo states', but since organice doesn't have the `C-c C-t` workflow, there's some UX thinking involved before one can start programming^^

**Comment by aspiers** [comment]
[**@munen**](https://github.com/munen) commented on [December 30, 2019 8:59 PM](https://github.com/200ok-ch/organice/issues/151#issuecomment-569794868 "2019-12-30T20:59:02Z - Replied by Github Reply Comments"):
> > I think it definitely makes sense to split them.
> 
> Since you're in the lead for this, I'll defer this to you. I would have written the new feature request for 'fast access to todo states', but since organice doesn't have the `C-c C-t` workflow, there's some UX thinking involved before one can start programming^^

Ah no, I suspect we're not quite on the same page yet.  The issue I reported is not about adding support for fast access to TODO states; it's about not hopelessly breaking the *existing* functionality when shortcut suffixes are added to `#+TODO` lines.  Currently when I have

    #+TODO: NEXT(n) STARTED(>) | DONE(d)

then organice thinks I want three keywords called `NEXT(n)`, `STARTED(>)`, and `DONE(d)`.  So if I have a line like this in organice:

    *** NEXT some task

and I swipe right, I'll get:

    *** NEXT(n) NEXT some task

because it's treating `NEXT` as if it's part of the headline.  Obviously this is completely wrong and I actually want the three keywords to be `NEXT`, `STARTED`, and `DONE`.  That's why I was considering it as a bug rather than a feature request.

So the immediate goal is simply to change organice's parser to ignore the suffixes in parentheses.  That should be really easy (but I think still deserves to be split into a separate issue).

Sure, *later on* we could add some kind of support for keyboard shortcuts which honour these suffixes within organice, but for me personally that is extremely low priority as I would probably never use it, since I'm very unlikely to use organice on a desktop / laptop, and only want to use it my phone or tablet.  However I still need to keep those suffixes on the `#+TODO` line because I rely on them when using emacs on desktop / laptop, and I need to keep the same file synchronised between my computers and mobile devices.

Sorry, I thought this was all obvious from my original description, but re-reading it now I can see how it might not have been.  Hopefully it's clear now?

**Comment by aspiers** [comment]
I've now submitted #184 for the `(x)` suffix issue, so this issue is now only concerned with allowing `#+TODO` lines (and potentially other in-buffer settings) to be parsed regardless of where in the file they come.

**Comment by aspiers** [comment]
Bearing in mind #185, addressing this issue by allowing `#+TODO` etc. anywhere should be considered feature work rather than a bug fix.  You've already addressed the documentation bug via d211588, so I think relabelling this issue to `feature` is now warranted.

**Comment by aspiers** [comment]
Probably going to get back to this very shortly.

**Comment by munen** [comment]
👍
