### ISSUE TITLE
clarify medium (if any) for synchronous developer chat

### ISSUE THREAD

**Issue by aspiers** [200ok-ch/organice#179]
Hi @munen, @schoettl, and other contributors :-)  I see that you two in particular are extremely active at the moment - I guess you are probably taking advantage of the holiday lull! - and I would like to contribute a bit too over the next few days at least before work starts to get busy again.

Given the fairly rapid pace of development it would be helpful to establish a place where as a newbie I can ask quick questions, check that my planned contributions are on the right track, and that sort of thing.

Half by accident I stumbled across https://gitter.im/org-web/Lobby and see that you have been using that to some degree for developer chat.  I understand that organice is a friendly fork of org-web so that makes sense to me, but I just wanted to ask for clarification whether that is indeed the preferred place where I should ask questions.  BTW "please just submit questions as GitHub issues" would also be a perfectly fine answer ;-)  I'm happy with whatever you prefer.  Whatever the answer, I think it would be great if it could be documented in either README.org or CONTRIBUTING.org so that it is clear for others too.

Thanks in advance - I'm excited to get my teeth into this awesome project!!

**Comment by munen** [comment]
Hi @aspiers

> I see that you two in particular are extremely active at the moment - I guess you are probably taking advantage of the holiday lull!

Full steam ahead^^

You haven't even seen all the emails and Signal messages. @schoettl is on fire the last couple of days! I'm stoked to see that some people want to spend their holidays working on organice - hence I'm trying my best to keep up^^

> and I would like to contribute a bit too over the next few days at least before work starts to get busy again.

You're very welcome to the party!

I have just invited you to our Slack team. You're welcome to hang out and ask away^^ 

NB: The org-web gitter Chat is for org-web. organice has evolved quite a bit from org-web. And the org-web maintainer (and original creator) asked to make a fork. So it makes sense to also make a distinction in communication channels.

I'll add the option to get an invite to the documentation, as well.

P.S.: I have hooks set up for Github and organice and try to respond to GH issues just as fast as to a chat. However, I would appreciate it a lot if more people wanted to have more in-depth discussions or even a pairing session!

**Comment by aspiers** [comment]
Awesome!!  Got your invite and joining Slack now (as soon as the train wifi catches up).  I'll leave it up to you whether to close this now or wait for one of us to submit a PR which closes it by updating the docs to mention Slack.  I would submit one right now but I guess you'll need to decide how to handle the Slack sign-up process.

**Comment by munen** [comment]
We now have #organice on Freenode as community chat.

I have written a [follow up issue](https://github.com/200ok-ch/organice/issues/258) to document it and spread the word.
