### ISSUE TITLE
Fixed version of node engine breaks install

### ISSUE THREAD

**Issue by aspiers** [200ok-ch/organice#180]
My openSUSE Leap 15.1 laptop has node 12.14.0 installed:

```
$ yarn versions
yarn versions v1.3.2
{
  yarn: '1.3.2',
  organice: '0.2.0',
  node: '12.14.0',
  v8: '7.7.299.13-node.16',
  uv: '1.33.1',
  zlib: '1.2.11',
  brotli: '1.0.7',
  ares: '1.14.0',
  modules: '72',
  nghttp2: '1.39.2',
  napi: '5',
  llhttp: '1.1.4',
  http_parser: '2.8.0',
  openssl: '1.1.1d',
  cldr: '35.1',
  icu: '64.2',
  tz: '2019c',
  unicode: '12.1'
}
Done in 0.06s.
```

but `package.json` is very opinionated about the node engine version and insists on 12.13.1:

```
$ yarn install 
yarn install v1.3.2
[1/5] Validating package.json...
error organice@0.2.0: The engine "node" is incompatible with this module. Expected version "12.13.1".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

I don't think it's entirely trivial to install an exact node version on most systems.  I know it can be done with `nvm`, so one easy improvement would be to mention `nvm` in `README.org`, but I suspect it might be better to slightly relax the node version requirement in `package.json`, unless there's a good reason to avoid this.  For example, how about something like this?

```diff
modified   package.json
@@ -3,7 +3,7 @@
   "version": "0.2.0",
   "private": true,
   "engines": {
-    "node": "12.13.1"
+    "node": "^12.13.1"
   },
   "dependencies": {
     "bowser": "^2.6.1",
```

**Comment by aspiers** [comment]
`~12.13.1` is also an option, of course, although this would only allow newer bugfix versions, so probably wouldn't help much.

**Comment by aspiers** [comment]
I'll submit a PR which introduces the `^` and mentions `nvm` in the `README.org`.

**Comment by munen** [comment]
If it runs, we can gladly upgrade. Please make sure the PR includes all parts that define this version. From the top of my head, those would be:

- .nvmrc (for nvm^^)
- package.json (for Heroku)
- Dockerfile (for packaging via Docker)

If you're touching the documentation, a bonus point whould be to mention that there's multiple places where the nodejs version is mentioned for different reasons.

**Comment by munen** [comment]
Thanks for making sure organice also runs on stock Linux systems! :pray:

**Comment by aspiers** [comment]
Thanks for the pointers!

**Comment by dotcs** [comment]
@aspiers 
Maybe we can also consider which parts of node.js are used. Is `12.x` really necessary? Which features are used that are not in say `10.x`? In my local setup I used nodejs 10, which worked without an issue. Node 10 is an LTS version if I remember correctly. IMHO we should allow for the minimum version that is possible.

**Comment by aspiers** [comment]
I entirely agree! However I have no idea which parts of node are used, or
how, so I'd need to defer to someone else on that.

**Comment by munen** [comment]
I don’t mind if we want to change the used node version. Some thoughts on that from my side:

- In the node and react ecosystem, it’s common practice to use NVM, so using the right version is automated 
- It’s absolutely possible to locally override that setting or not use nvm
- If someone does not want or cannot install Node, that’s what Docker is for

So, we are covering all best practices already. 

If you want to change the node version, I’m generally in favor. However, the version should only go forward. organice is not a legacy application and we serve as an Ops team; it is an actively developed application embedded in a fast moving ecosystem. Even if Nodejs 10 would work today, there’s likely downsides already today (speed) or a missing API tomorrow, or worse - a slight change in API behavior that we will only learn about through though debugging. 

The way forward in languages like JS or Ruby is forward^^

**Comment by aspiers** [comment]
That's a very good point about Docker.  I hadn't thought of that because I went straight to [the "Development" section of `README.org`](https://github.com/200ok-ch/organice#development), and Docker is only mentioned under [the "Deployment" section](https://github.com/200ok-ch/organice#deployment).

If we want Docker to be a truly viable option for development, we need to document how to mount the git repository code inside the container and run it directly from that, because most people (at least the sane ones :stuck_out_tongue_winking_eye:) will not attempt to run their code editor within the Docker container.

In fact, the current `Dockerfile` has `COPY . /opt/organice` which probably doesn't work for that use case, so I suspect we might need not only to update the docs, but also to create a separate `Dockerfile` just for development.  The requirement would be to be able to make a change to the code and have the container instantly update to reflect that.  Anything else would introduce latency into the code/test feedback loop which would seem unacceptable IMHO.

**Comment by munen** [comment]
Imo the idiomatic solution would be to mount the source repo as a volume for a dev use case.

**Comment by aspiers** [comment]
[**@munen**](https://github.com/munen) commented on [January 1, 2020 9:37 AM](https://github.com/200ok-ch/organice/issues/180#issuecomment-570037833 "2020-01-01T09:37:23Z - Replied by Github Reply Comments"):
> Imo the idiomatic solution would be to mount the source repo as a volume for a dev use case.

Agreed, that's what I was suggesting above - but as mentioned I don't see how it's compatible with the existing `COPY` approach.  However I've filed a separate issue #191 for that.
