### ISSUE TITLE
#+TODO doesn't understand (x) suffixes for keyboard shortcuts

### ISSUE THREAD

**Issue by aspiers** [200ok-ch/organice#184]
[This was originally reported in #151, but is now split out into this issue.]

I need to keep my `TODO.org` synchronised between my desktop/laptop/mobile phone/tablet, with the intention of using emacs on desktop/laptop, and organice on mobile phone/tablet.

I have a fairly complex configuration for my `TODO` keywords.  I have `org-todo-keywords` customised to:

```elisp
((sequence "NEXT(n)" "STARTED(>)" "|" "DONE(d)")
 (sequence "PROJECT(p)" "PROJDONE(P)")
 (sequence "ONGOING(o)" "WAITING(w@)" "CHASE(C@)" "|")
 (sequence "SOMEDAY(s)" "MAYBE(m)" "|" "CANCELLED(c)"))
```

Since organice does not know about elisp configuration, I added this to near the bottom of my `TODO.org`:

```org
* org-mode settings
*** TODO keywords
#+TODO: NEXT(n) STARTED(>) | DONE(d)
#+TODO: PROJECT(p) PROJDONE(P)
#+TODO: ONGOING(o) WAITING(w@) CHASE(C@) |
#+TODO: SOMEDAY(s) MAYBE(m) | CANCELLED(c)
```

Note that [the letters in parentheses define keyboard shortcuts providing fast access to TODO states](https://orgmode.org/manual/Fast-access-to-TODO-states.html#Fast-access-to-TODO-states), so that within emacs I can hit (say) `C-c C-t p` to immediately change a headline to `PROJECT`.

However organice does not understand these parenthetical suffixes.  All the above keywords are treated like normal headline text, i.e. it thinks I want three keywords called `NEXT(n)`, `STARTED(>)`, and `DONE(d)`.  So if I have a line like this in organice:

    *** NEXT some task

and I swipe right, I'll get:

    *** NEXT(n) NEXT some task

because it's treating `NEXT` as if it's part of the headline.  Obviously this is completely wrong and I actually want the three keywords to be `NEXT`, `STARTED`, and `DONE`.

So the immediate goal is simply to change organice's parser to ignore the suffixes in parentheses.  That should be really easy.  Of course we'll also want some unit tests to ensure we avoid any regressions when switching to `org-parser` later on.

Even later on, we could potentially add some kind of support for keyboard shortcuts which honour these suffixes within organice, but for me personally that is extremely low priority as I would probably never use it, since I'm very unlikely to use organice on a desktop / laptop, and only want to use it my phone or tablet.  However I still need to keep those suffixes on the `#+TODO` line because as mentioned above, I rely on them when using emacs on desktop / laptop, and I need to keep the same file synchronised between my computers and mobile devices.

**Desktop (please complete the following information):**
 - OS: openSUSE Linux
 - Browser: Chrome 79

**Smartphone (please complete the following information):**
 - Device: OnePlus 5T
 - OS: Android 9.0.x
 - Browser: Brave and Chrome

**Comment by munen** [comment]
Perfect issue. And I agree that this is a proper bug(;

Do you plan to work on making the required changes to the parser?

**Comment by aspiers** [comment]
Yes I do.  I would assign the issue to myself but I don't have access to do that - feel free to assign it to me if you want :-)

**Comment by munen** [comment]
Happily assigned^^
