### ISSUE TITLE
As a user, when I have "unpushed changes" and then go to a non-org view (settings/help or the like), I don't want to lose the changes made to my Org file

### ISSUE THREAD

**Issue by munen** [200ok-ch/organice#19]
## Description
Visiting the help page and then returning loses any unpushed changes.

## To reproduce

0. Ensure that the Live sync setting is disabled
1. Go to any file in organice
2. Make a change, so that "Unpushed changes" is visible in the bottom right
3. Click the `?` icon at the top right to visit the help screen
4. Click `Done` at the top right to return from the help screen
5. Observe that unpushed changes have now vanished.

## Expected behavior

Ideally unpushed changes would be preserved after returning from the help.  However if that is not easy to implement, a reasonable alternative short-term fix would be to display "You have unpushed changes - are you sure you want to leave this page?" after clicking the `?` icon.  This is not ideal because it prevents users from visiting the help when they have unpushed changes, but it's a lot better than silently discarding their changes.

## Potentially related

I don't know if that's related, but I recently experienced that changes in the 'sample.org' file sometimes also do trigger a wish to synchronize.

This is pretty weird, since the sample.org file is not synchronized.

**Comment by munen** [comment]
In `Entry/index.js`, there's a `shouldPromptWhenLeaving` function.

Option: Refactor the logic into a middleware like 'should sync on becoming visible'.

This could fix https://github.com/200ok-ch/organice/issues/199, as well.

**Comment by aspiers** [comment]
As explained in https://github.com/200ok-ch/organice/issues/214#issuecomment-571824648, this issue's title is about going to the settings page, which doesn't match the issue's body newly copied from #214.  The latter concerns visiting the help page, not the settings page, and the two currently have different behaviours.

**Comment by munen** [comment]
#214 was a dupe. organice has a general issue with routing protection. Adding multiple issues for different routes is not required.

**Comment by aspiers** [comment]
[**@munen**](https://github.com/munen) commented on [January 9, 2020 12:58 PM](https://github.com/200ok-ch/organice/issues/19#issuecomment-572549849 "2020-01-09T12:58:04Z - Replied by Github Reply Comments"):
> [#214](https://github.com/200ok-ch/organice/issues/214) was a dupe. organice has a general issue with routing protection. Adding multiple issues for different routes is not required.

I can appreciate that, and thanks for fixing the inconsistency in the title.  To check I understand correctly: the intention is to eliminate the unpushed changes alert window when attempting to visit the settings window, and in both the settings and help cases to allow visiting those pages whilst preserving unpushed changes on return to the main editor?

**Comment by munen** [comment]
> the intention is to eliminate the unpushed changes alert window when attempting to visit the settings window, and in both the settings and help cases to allow visiting those pages whilst preserving unpushed changes on return to the main editor?

The implementation would depend on the person doing the implementation. There's a different trade-off when implementing. Of course it's better UX to have the ability to visit help and settings whilst doing the sync in the background. Since this is a major bug, I'd happily pull in any implementation - bar which variant would be the better UX wise.

**Comment by munen** [comment]
I don't know if that's related, but I recently experienced that changes in the 'sample.org' file sometimes also do trigger a wish to synchronize.

This is pretty weird, since the sample.org file is not synchronized.

**Comment by tarnung** [comment]
I think this is fixed by multi file support / saving to local storage.

**Comment by munen** [comment]
Confirm. Fixed by multi file support.
