### ISSUE TITLE
Docker-based development setup

### ISSUE THREAD

**Issue by aspiers** [200ok-ch/organice#191]
[Originally raised in #180]

## User story

As a developer, I would like to be able to run organice within a Docker container  directly from a checkout of the git repository, in order to efficiently develop and test modifications to the source code. 

## Explanation

Not everyone will by default have a version of the nodejs engine installed which fulfils the requirements specified in `package.json`, even if we relax the requirements as proposed in #180.  Furthermore, some developers newly joining the project may prefer to set up a development environment in a Docker container rather than installing `nvm` and using that to install an appropriate version of the nodejs engine.  (For example, `nvm` is not really supported on Windows.)

However, setting up an environment via Docker is only mentioned under [the "Deployment" section](https://github.com/200ok-ch/organice#deployment), not in [the "Development" section of `README.org`](https://github.com/200ok-ch/organice#development).

If we want Docker to be a truly viable option for development, we need to document how to mount the git repository code inside the container and run it directly from that, because most people (at least the sane ones :stuck_out_tongue_winking_eye:) will not attempt to run their code editor within the Docker container.

[The current `Dockerfile`](https://github.com/200ok-ch/organice/blob/master/Dockerfile) has

    COPY . /opt/organice

which AFAICS won't work for this development use case.  So I suspect we might need not only to update the docs, but also to create a separate `Dockerfile` just for development which doesn't embed the source code inside but instead assumes that it will be mounted from outside.  The requirement would be to be able to make a change to the code and have the running container process instantly update to reflect that.  Anything else (e.g. building a new container image after each source code modification) would introduce undesirable latency into the code/test feedback loop and make the development experience inefficient.

Ideally it wouldn't even be necessary to restart the container process after each modification, but if that's non-trivial to implement it could be taken care of in a later step.

**Comment by aspiers** [comment]
Sorry, this isn't really a bug but I can't change labels (and it's not really a feature request either :wink: ).

**Comment by munen** [comment]
Looking forward to seeing the new dev environment^^

**Comment by munen** [comment]
Closing as per https://github.com/200ok-ch/organice/blob/master/CONTRIBUTING.org#how-we-work-with-issues. If you choose to work on this at some point, please re-open the issue.
