### ISSUE TITLE
Discuss: Upgrade react-dom

### ISSUE THREAD

**Issue by aspiers** [200ok-ch/organice#196]
`yarn test` is showing errors with latest git `master`:

```
 PASS  src/components/Landing/Landing.test.js
  ● Console

    console.error node_modules/@testing-library/react/dist/act-compat.js:88
      It looks like you're using a version of react-dom that supports the "act" function, but not an awaitable version of "act" which you will need. Please upgrade to at least react-dom@16.9.0 to remove this warning.

 PASS  src/lib/org_utils.unit.test.js
 PASS  src/components/OrgFile/OrgFile.integration.test.js
  ● Console

    console.error node_modules/@testing-library/react/dist/act-compat.js:88
      It looks like you're using a version of react-dom that supports the "act" function, but not an awaitable version of "act" which you will need. Please upgrade to at least react-dom@16.9.0 to remove this warning.
```

Am I the only person to see these?

## To Reproduce

1. Run `yarn test`
2. View errors in output

## Expected behavior

No errors on `yarn test`.

**Desktop (please complete the following information):**
 - OS: openSUSE Leap 15.0
 - Browser: Chrome

**Additional context**

Unfortunately tweaking `package.json` to require `react-dom@16.9.0` or later results in a whole bunch of new errors.

**Comment by aspiers** [comment]
See also #54 but there's no obvious link between the two other than react-dom.

**Comment by aspiers** [comment]
> Unfortunately tweaking package.json to require react-dom@16.9.0 or later results in a whole bunch of new errors.

Turns out that most of these were due to a version mismatch between react, react-dom, and react-test-renderer - I think we'll have to update the versions of all three at the same time.  I'm looking into this.

**Comment by munen** [comment]
This is not a bug in organice. It's a warning relayed from @testing-library/react. All tests in organice were green and not impacted from this warning.

It's likely true that updating react-dom would fix it. However, this is a non-trivial task due to breaking changes in React. A pre-requesiste to doing this is finishing work on this issue: https://github.com/200ok-ch/organice/issues/15

Additionally, it's an errorneus warning from @testing-library/react which they fixed upstream: https://github.com/testing-library/react-testing-library/commit/139df628291511a9ce0c3a559c2c245f7ce64747

I've upgraded @testing-library/react and the warning is gone. Voting to close the ticket - unless you actually want to finish writing all regression tests and than do the manual upgrade to a newer version of react-dom which would certainly be awesome.

**Comment by aspiers** [comment]
[**@munen**](https://github.com/munen) commented on [January 2, 2020 1:57 PM](https://github.com/200ok-ch/organice/issues/196#issuecomment-570214368 "2020-01-02T13:57:00Z - Replied by Github Reply Comments"):
> This is not a bug in organice. It's a warning relayed from @testing-library/react. All tests in organice were green and not impacted from this warning.

Sure, I never said it was a bug in organice ;-)  However the only way I could have avoided the `bug` label would have been to submit a feature request issue instead, which is of course even less accurate.  So as a side note I suggest we consider adding a separate template to `.github/ISSUE_TEMPLATE` which allows reporting issues which are neither bugs nor features.  For example right now even though there is a `question` label, I think you are the only person who can assign it.

> It's likely true that updating react-dom would fix it. However, this is a non-trivial task due to breaking changes in React.

Yup, so I discovered :-/

> A pre-requesiste to doing this is finishing work on this issue: [#15](https://github.com/200ok-ch/organice/issues/15)

Cool, thanks for the pointer!

> Additionally, it's an errorneus warning from @testing-library/react which they fixed upstream: [testing-library/react-testing-library@139df62](https://github.com/testing-library/react-testing-library/commit/139df628291511a9ce0c3a559c2c245f7ce64747)
> 
> I've upgraded @testing-library/react and the warning is gone.

Ah, just saw you upgraded it in #197!  At first I wasn't sure what you meant by that sentence - there was no cross-reference so I thought you were talking about a `yarn upgrade` or something.  But I've just tested latest `master` and it works great.  Awesome - thanks a lot!

> Voting to close the ticket - unless you actually want to finish writing all regression tests and than do the manual upgrade to a newer version of react-dom which would certainly be awesome.

No, I agree we can close.  Thanks again! :clap:

**Comment by munen** [comment]
@aspiers 

> Sure, I never said it was a bug in organice ;-) However the only way I could have avoided the bug label would have been to submit a feature request issue instead, which is of course even less accurate. 

Now I understand! You wanted to stick to the issue templates which only gives you those two options.. 

Thank you for being nice and always trying to fill out all the metadata(; 

> So as a side note I suggest we consider adding a separate template to .github/ISSUE_TEMPLATE which allows reporting issues which are neither bugs nor features. For example right now even though there is a question label, I think you are the only person who can assign it.

I've updated the docs in CONTRIBUTING.org to try and clarify how to handle both non-bug/feature-requests and the question label: https://github.com/200ok-ch/organice/commit/20358e63869f87b482a632e645643e4c3af654b0

Could you kindly read it and give me feedback if it helps? If it does not, feel free to make a PR to give it a better wording.

**Comment by aspiers** [comment]
[**@munen**](https://github.com/munen) commented on [January 2, 2020 10:41 PM](https://github.com/200ok-ch/organice/issues/196#issuecomment-570382818 "2020-01-02T22:41:31Z - Replied by Github Reply Comments"):
> [@aspiers](https://github.com/aspiers)
> 
> > Sure, I never said it was a bug in organice ;-) However the only way I could have avoided the bug label would have been to submit a feature request issue instead, which is of course even less accurate.
> 
> Now I understand! You wanted to stick to the issue templates which only gives you those two options..

Well, it's more that I didn't realise until just now that https://github.com/200ok-ch/organice/issues/new/choose has a bit under the templates saying "Don’t see your issue here? Open a blank issue." ;-) 

> I've updated the docs in CONTRIBUTING.org to try and clarify how to handle both non-bug/feature-requests and the question label: [20358e6](https://github.com/200ok-ch/organice/commit/20358e63869f87b482a632e645643e4c3af654b0)
> 
> Could you kindly read it and give me feedback if it helps? If it does not, feel free to make a PR to give it a better wording.

Looks great to me, thanks!

**Comment by munen** [comment]
> Looks great to me, thanks!

Thanks for looking it over^^
