### ISSUE TITLE
As a user, when I visit Search, Task List or Agenda whilst having a dirty file, I don't want the browser to pop up a dialogue notifying me about unpushed changes

### ISSUE THREAD

**Issue by munen** [200ok-ch/organice#199]
@schoettl According to your [comment](https://github.com/200ok-ch/organice/pull/181#issuecomment-569944110), you're sometimes getting notified about unpushed changes on Android when using the Task List and Agenda views.

I have found a way to reproduce this issue:

- Open a big file on a slow connection
- Make changes to it
- Before the changes are saved to the synchronization back-end, quickly open the Task List or Agenda

Then I'll get this pop-up.

![image](https://user-images.githubusercontent.com/505721/71672981-b89ee280-2d77-11ea-9f70-74e2424c2a8a.png)

This popup is created by the `Entry` component to ensure that the application first synchronizes before it changes views. Generally speaking, this is a very good check. It should exclude non-mutative drawers on Org files (Agenda, Task List), though.

**Comment by schoettl** [comment]
Right, you also get this message more often, if you have not enabled the "immediately synchronize on every change" setting.

**Comment by munen** [comment]
Ok, now that the issue is reproducible, the fix is to exclude non-mutative drawers on Org files (Agenda, Task List) from the synchronization validation.

**Comment by munen** [comment]
In `Entry/index.js`, there's a `shouldPromptWhenLeaving` function.

Option: Refactor the logic into a middleware like 'should sync on becoming visible'.

This could fix https://github.com/200ok-ch/organice/issues/19, as well.
