### ISSUE TITLE
When refiling a header, don't show subheaders in the refile drawer

### ISSUE THREAD

**Issue by schoettl** [200ok-ch/organice#212]
## TODO

- [x] Filter out child headers from the header that is to be refiled from the refile view.

## History

Thank you @munen for the new feature :)
I pretty much messed up my org file ^^

There are a few issues currently:

1. If you don't know the refile action and icon, you will be surprised finding yourself at the "Search" when you press it.
2. When I dismiss the "Search" modal without pressing on a header, the current header is gone, and it took me some time to find it.
3. When I refile a top-level header, the header is refiled, but the subheaders are not. Also, they staying at level two. I would expect that the subheaders are either staying below its header or go one level up.

For 1. I think it's very important to fix the title of the modal. We have to do that anyway by #211 

For 2. it's very important to make clear what a click to the header does. And more importantly, dismissing the modal must cancel the operation.

**Comment by munen** [comment]
@schoettl Sorry to hear the new feature messed up your file. 

1. I was planning to do that as part of the discussed refactor.
2. That's a bad one. I can reproduce it. Will work on it!
3. Can you write a test or make a video (plus share your Org file)? I did test this feature quite extensively and I'm not seeing this behavior.

**Comment by munen** [comment]
@schoettl [This](https://github.com/200ok-ch/organice/commit/3292e966fada1c07d1d8ef918a82691a6462db7b) fixes your second point.

I apologize for the inconvenience!

Thank you for testing :pray:

**Comment by schoettl** [comment]
```
* Aufgaben [2/2]
** DONE fix tests in feature/42/...
* Einkaufen
```
---------------------
If we use this example file, here are instructions to reproduce two bugs:

I refile the last header and cancel/dismiss (so I don't know what the app was doing, maybe refile to the first header in the list?)

Then the last header appears top-most in the file but at level 2.

----------------

When I now use the original file again:

I refile the first header and cancel/dismiss.

Then it looks like this:
![test2](https://user-images.githubusercontent.com/1301843/71917842-4ff1a480-3181-11ea-89e0-80f34d2757ed.png)
------------------------
(sorry, I forgot to take a screenshot for the first)

Can you reproduce it?

**Comment by munen** [comment]
Skipping your last comment (will get to that later).

> For 2. it's very important to make clear what a click to the header does.

I've made this change: https://github.com/200ok-ch/organice/issues/188#issuecomment-571730711

**Comment by munen** [comment]
Now to your last comment:

> Can you reproduce it?

No, I can't. I provided and deployed a fix before you provided instructions (see my comment about your instructions: https://github.com/200ok-ch/organice/issues/212#issuecomment-571702488). Your bug report was enough to let me understand this bug.

I couldn't reproduce the bug that you described in your original issue as no. 3.

**Comment by schoettl** [comment]
OK, now that cancel works, I cannot reproduce either :)

One more bug:

1. in my example file, refile "Aufgaben [2/2]" under "DONE fix tests in feature/42/..."
2. check the indentation level of the result

I know... I'm not supposed to do that... :D

**Comment by munen** [comment]
> I know... I'm not supposed to do that... :D

No, you're not(;

Having said that, the UI gives you the option, so it's the UIs fault. Emacs Org mode doesn't allow it and also doesn't auto-complete for such headlines.

The solution is to filter out child headers from the refile view.

Thank you for reporting it! I was thinking of openening an issue, myself, because it's definitively a UX bug.

NB: Since https://github.com/200ok-ch/organice/pull/226, you can at least 'undo' the bad refile(; Not saying that this is good enough, of course, but it's a good step towards giving the user control of potentially wrong actions of organice.

**Comment by munen** [comment]
@schoettl Happy to report that all three of your reported issues have been taken care of^^ Good call on all 3 of them! :pray:
