### ISSUE TITLE
As a user, when I’m in the Search modal, I want to see not just the headline title, but the hierarchy of the parents

### ISSUE THREAD

**Issue by munen** [200ok-ch/organice#213]
This could look like breadcrumbs.

**Comment by schoettl** [comment]
A guess that would be useful for search and refile but maybe not for the task list. Maybe that can be parameterizable depending on if it's search or task list.

Same applies for the planning items that are visible for each header in the task list but not in the search result.

**Comment by munen** [comment]
Definitively only useful for the search modal. That's why I didn't say anything about the task list.

For search/refile it's 100% required, though. Because otherwise, how do you make a distinction between "Next" and "Next" when selecting your chosen header?(;

**Comment by tarnung** [comment]
This should be added to [the multi file support project](https://github.com/200ok-ch/organice/projects/1).

**Comment by munen** [comment]
@tarnung Done.
