### ISSUE TITLE
FR: quick switch to different action

### ISSUE THREAD

**Issue by aspiers** [200ok-ch/organice#216]
## Feature description

Imagine this user workflow:

1. Tap on property list icon to add a property or edit an existing one
2. "Edit property list" modal dialog slides up from the bottom of the screen.
3. Immediately change your mind and decide to add or edit a tag instead. (This could even be a simple mistake in tapping the wrong icon, rather than due to a change of mind.)
4. Tap the tag icon.

**Expected result**: The "Edit property list" dialog automatically closes and the "Edit tags" dialog pops up in a single go.

**Observed result**: The "Edit property list" dialog closes, but nothing else happens.  You have to tap the tag icon a second time to open the "Edit tags" dialog.  Furthermore, if you tap it too soon after the first tap to close the previous dialog, nothing happens.  You have to wait at least a fraction of a second for some JS event to complete (not sure what, but I can see a tiny flicker so I know it's happening).

## Further considerations

- This lack of "quick switch" behaviour applies to any (pair of) actions which pop up a dialog in this fashion; not just property lists and tags, but also setting `SCHEDULED` or `DEADLINE` timestamps.
- In contrast, it already works fine when first editing the item's headline or description (body) and then tapping one of the icons for the above four actions.
- If any editing (i.e. change of property list / tags / timestamps) is done prior to tapping the second action, those edits should be preserved (as they already are when first editing the headline or body in the scenario described by the previous bullet item immediately above).  That's why I coined the term "quick switch" rather than say, "quick cancel and switch".

**Comment by munen** [comment]
I'm not aware of applications having this pattern. To me it sounds like it complicates an already complicated UX design and would hinder the progress of a refactor. But maybe I'm just understanding it wrong. Or maybe you're thinking of this as part of the UX redesign process and not as a feature request for the current UI design iteration.

Can you name a couple applications that have this pattern? It would be great if they run on iOS, so that I can test them. Alternatively, a video would be good.

**Comment by aspiers** [comment]
[**@munen**](https://github.com/munen) commented on [January 9, 2020 10:49 AM](https://github.com/200ok-ch/organice/issues/216#issuecomment-572506255 "2020-01-09T10:49:59Z - Replied by Github Reply Comments"):
> I'm not aware of applications having this pattern.

Organice does already :-)  That's what I was referring to in my 2nd bullet point under "Further considerations" above.

> Can you name a couple applications that have this pattern?

I can't think of a second one off the top of my head, but the fact that Organice already does it in the described circumstances suggests to me that, for UI consistency if nothing else, probably it should either do it in all applicable circumstances, or in none.

> It would be great if they run on iOS, so that I can test them. A video works, too.
> 
> Alternatively, if showing existing apps is hard, can you make a clickable wireframe to show how this would work?

No need for any of that.  You can see it yourself in Organice:

1. Tap a headline to display the icons
2. Tap the "Edit header title" icon
3. Tap the "Modify tags" icon (you may have to scroll this back into visibility first if the keyboard covers it like it does on my Android device)
4. Observe that the "Edit tags" modal immediately pops up.
5. Now tap the "Edit header title" icon
6. Observe that it only cancels the tag editing modal and does nothing else - a second tap of this icon is required to re-enter the header title editing mode.

IMHO this is a clear inconsistency in the behaviour of those two icons, and as I already mentioned the inconsistency extends to other icons too.

It's also interesting to note that this behaviour is *not* reproducible if trying it from a desktop browser using the mouse, unless the browser is simulating a mobile device (e.g. using Chrome dev tools).

**Comment by munen** [comment]
> Organice does already :-) That's what I was referring to in my 2nd bullet point under "Further considerations" above.

Ok, thanks for clarifying. You're saying:

> In contrast, it already works fine when first editing the item's headline or description (body) and then tapping one of the icons for the above four actions.

Changing a header or description have a different UX than the other buttons you mention. They only open a textarea field whereas tags, properties and the like open a full screen drawer. The rationale is that some actions need more screen estate than others (agenda, search, task list, tags, property editor need more space than just editing a headline).

Hence, I don't see the rationale in your statement "IMHO this is a clear inconsistency in the behaviour of those two icons, and as I already mentioned the inconsistency extends to other icons too.".

They work very different - inline editing vs full screen modal. 

I still don't see how the UX could be harmonized. If you do provide clickable wireframes, I'll likely understand and maybe I'll even agree with your assessment. 

One important bit that I read (that's kind of unrelated to your proposed issue, though):

> Tap the "Modify tags" icon (you may have to scroll this back into visibility first if the keyboard covers it like it does on my Android device)

That's not happening on the Desktop browser or the iPhone for me. The textarea and the action items are clearly in focus. If you do have the time and some CSS skills, I don't mind a PR that fixes this for Android and likely your specific device model.

**Comment by aspiers** [comment]
> > Organice does already :-) That's what I was referring to in my 2nd bullet point under "Further considerations" above.
> 
> Ok, thanks for clarifying. You're saying:
> 
> > In contrast, it already works fine when first editing the item's headline or description (body) and then tapping one of the icons for the above four actions.
> 
> Changing a header or description have a different UX than the other buttons you mention. They only open a textarea field whereas tags, properties and the like open a full screen drawer. The rationale is that some actions need more screen estate than others (agenda, search, task list, tags, property editor need more space than just editing a headline).

Sure - but this issue isn't about how these different interfaces appear or function.  It's about being able to switch between them with a single tap.
 
> Hence, I don't see the rationale in your statement "IMHO this is a clear inconsistency in the behaviour of those two icons, and as I already mentioned the inconsistency extends to other icons too.".
> 
> They work very different - inline editing vs full screen modal.

Again, it's not about how they work.  It's about switching between them.  Switching from editing the header to editing tags (say) can be done in a single tap.  Switching back the other way requires two taps.  That's inconsistent.

> I still don't see how the UX could be harmonized. If you do provide clickable wireframes, I'll likely understand and maybe I'll even agree with your assessment.

If you're asking for wireframes then I fear I've miserably failed to communicate the issue.  In which case sorry for that failure!

I'm simply saying that **switching between these editing modes should always only require a single tap, not two taps**.  So the UX is harmonized **simply by removing the need for the extra tap**.  The first tap should always cancel the current editing mode and immediately switch to the new mode.  No change in appearance is required!  Making a wireframe would be way overkill for this, as it's really a trivial UX detail (albeit one which apparently I am struggling to explain well).

Although one possible reason for the apparent disconnect here just occurred to me. You described one of the modes as a "full screen drawer" and "full screen modal".  However on my Android device (and indeed in Chrome) it only covers roughly half the screen.  This is a crucial detail, because if it really covered the whole screen, the action icons would not be visible, therefore what I am asking for would not make sense.  So I am wondering if maybe it *does* cover the whole screen on your iPhone, and maybe that is why the request doesn't make sense to you?  Just a wild guess...  Although I know you also test on the desktop, so the guess is probably wrong.

In slightly more technical terms, I suspect the fix is going to be a matter of changing the half screen modal/drawer so that a tap on an icon above that drawer are handled not only as an indication to close the drawer, but also as a normal event acting on the icon.   Indeed, a quick look at the HTML shows:

```html
<div class="drawer-outer-container drawer-outer-container--visible"><div class="drawer-inner-container nice-scroll" data-testid="drawer" style="transform: translateY(0px);"> ... </div></div>
```
where the inner container has the half-screen drawer, and the outer container masks the *entire* screen, thereby preventing any clicks from directly reaching any visible action icons.  So probably it would be necessary to eliminate this outer container as part of the fix.

> One important bit that I read (that's kind of unrelated to your proposed issue, though):
> 
> > Tap the "Modify tags" icon (you may have to scroll this back into visibility first if the keyboard covers it like it does on my Android device)
> 
> That's not happening on the Desktop browser or the iPhone for me. The textarea and the action items are clearly in focus. If you do have the time and some CSS skills, I don't mind a PR that fixes this for Android and likely your specific device model.

Yeah, I can look at that one; let's track it in a separate issue though!

**Comment by munen** [comment]
I can only repeat: They are completely different UI design actions. It’s:

- In-line editing of a header (title, description)
- Editing in a full screen modal

Those two ways are there by design. And I have never seen a modal behave like inline editing in my life and I wouldn’t know how to change that. In fact I wouldn’t want to. 

If the modals aren’t full screen on your device, then this is a rendering issue on your device. Please feel free to debug that and make a PR. 

As for your propose changes, they are not possible with the current UX. 

They can be part of a redesign where we get rid of the header action bar and work in a new way.

**Comment by munen** [comment]
Some screenshots for reference:

Inline editing of a header

![B90A3028-99A2-4F9D-8289-6A105F7B50B4](https://user-images.githubusercontent.com/505721/72132794-2783c900-3380-11ea-89cc-b8b7892cffde.png)

Drawers 

Agenda

![91AB1E8F-E103-419D-9B10-14B4C8538BE4](https://user-images.githubusercontent.com/505721/72132822-37031200-3380-11ea-94cf-b7730a6f37e0.png)

Tags in a File with few tags

![BD4490AD-C96E-4005-BF8D-B9302E3955BC](https://user-images.githubusercontent.com/505721/72132865-57cb6780-3380-11ea-996e-0946e75ef233.png)

Increasing the drawer size with more items

![1C9C927D-17C6-4E18-92AC-C0BA170C1031](https://user-images.githubusercontent.com/505721/72132905-69ad0a80-3380-11ea-90e6-e5681d248eda.png)

**Comment by aspiers** [comment]
[**@munen**](https://github.com/munen) commented on [January 10, 2020 6:55 AM](https://github.com/200ok-ch/organice/issues/216#issuecomment-572899872 "2020-01-10T06:55:16Z - Replied by Github Reply Comments"):
> I can only repeat: They are completely different UI design actions. It’s:
> 
> *   In-line editing of a header (title, description)
> *   Editing in a full screen modal

No need to repeat :-) I fully acknowledge that (except the "full screen" bit, if you'll forgive the nitpick - see below).

> Those two ways are there by design. And I have never seen a modal behave like inline editing in my life and I wouldn’t know how to change that. In fact I wouldn’t want to.

Neither would I!  The existing design is great.  I already said I am not proposing to change the behaviour of either the inline editing or the modal, so the fact you are writing that makes me worry that we still have a communication disconnect.

> If the modals aren’t full screen on your device, then this is a rendering issue on your device. Please feel free to debug that and make a PR.

This modal you just posted is not full screen; it only occupies the bottom half:

> Tags in a File with few tags
> 
> ![BD4490AD-C96E-4005-BF8D-B9302E3955BC](https://user-images.githubusercontent.com/505721/72132865-57cb6780-3380-11ea-996e-0946e75ef233.png)

However that seems entirely correct behaviour to me, so I don't see the need to debug and make a PR.

I appreciate that it can grow and potentially cover some or all visible action icons, but my point is that while the action icons are still visible, it would be more helpful if tapping on them took immediate effect:

![modal-switch](https://user-images.githubusercontent.com/100738/72144170-ff03cb00-338f-11ea-999d-d6ef9d5df481.jpg)

> As for your propose changes, they are not possible with the current UX.

From a *design* perspective it is possible.  Regarding *implementation* I would obviously defer to your judgement since I don't know the codebase well enough to comment yet; however while it might be too complex to justify the effort, I don't see why it would be impossible.

I feel that we are probably still talking at cross-purposes and that I failed to clearly communicate the UI change I was proposing :-( But if this last comment doesn't resolve any confusion then I suggest to just forget about it, since I don't want to suck your time away from more important things!

**Comment by aspiers** [comment]
[**@munen**](https://github.com/munen) commented on [January 10, 2020 10:52 AM](https://github.com/200ok-ch/organice/issues/216#issuecomment-572986880 "2020-01-10T10:52:00Z - Replied by Github Reply Comments"):
> A drawer works like this:
> 
> - It's like a modal, hence it doesn't operate on the same level as the headers in the Org file
> - It has different semantics:
>   - When touching/dragging a header down, you'll scroll in the Org file
>   vs
>   - When touching/dragging a drawer down, you'll close the drawer
>   and
>   - When touching a header, you select a header
>   vs
>   - When touching a header when in a drawer, you close the drawer
> 
> Since the HeaderActionBar is in the Header, it _cannot_ be clicked when the drawer is open. The drawer is logically _on top_ of the Org file headers. Hence you _cannot_ reach the header when the drawer is open. If you do, that's supposed to close the drawer.

Sure - I am aware of and acknowledge all that.

> This is a common concept for drawers. If you don't believe me, please look at some other source, like the material design drawers: material-ui.com/components/drawers

I believe you :-)  I've encountered drawers many times before.  I don't see why my proposal would negate any aspects of that concept.  But let's just forget about it for now :-)

> The only change we can do is think about removing inline actions
> and drawers and only use one concept.

This bit doesn't make sense to me, since I can see the possibility for a much simpler change, but that's OK.  Let's just drop it :-)

> That's a _huge_ undertaking, though. And if done, it should be part of the complete redesign.

I certainly don't want to propose a big redesign within the scope of this issue.  That was never my intention.

> Hence I already mentioned this issue in the relevant redesign issue.
> 
> This particular issue is closed since it is not actionable. You're
> proposing that drawers are behaving like inline actions.

That's certainly not the intention of my proposal.  I don't want to change the behaviour of drawers at all.  I was suggesting to change what happens immediately _after a drawer closes_, in a few very specific circumstances.

But please let's leave it there - I already feel bad for wasting your time on this.  It's such a small UI tweak, it doesn't deserve this amount of attention.  Let's get back to more important stuff :-)  I'd prefer to be submitting PRs than having long discussions, and I'm sure you would too!
