### ISSUE TITLE
As a user, when creating/modifying a SCHEDULED and DEADLINE timestamp, I want to see more semantic information in the modal

### ISSUE THREAD

**Issue by aspiers** [200ok-ch/organice#217]
(This is a minor UI/UX bug, but when combined with #218 it becomes a slightly more significant problem.)

If I click either of [the new `DEADLINE` or `SCHEDULED` icons](https://github.com/200ok-ch/organice/issues/188#issuecomment-571730711), I get an identical-looking modal dialog with no way to tell which type of timestamp I'm editing.  They should say "Edit scheduled timestamp" and "Edit deadline" or similar to differentiate the two.

This is particularly important given that currently the two icons are very similar and it's not immediately obvious which is which.  I've filed #218 to track that separate but related issue.

**Comment by schoettl** [comment]
Good point, this was also on my list.

Maybe we can make the title of the modal a property and pass an appropriate value for it.

There must be a third option "Edit timestamp" for normal timestamps in title or description.

We could also differentiate between "Add deadline" and "Edit deadline", to make clear that there was no deadline before.

**Comment by munen** [comment]
@aspiers @schoettl Does either of you want to work on this?

One note I want to make: Currently, it's always "edit timestamp", never "create timestamp". Rationale: As soon as you hit the action button, you'll have a corresponding timestamp for today. In the modal, you can change the date or delete the timestamp altogether. 

It would be possible to change this behavior, but that would not be trivial - even from a UX standpoint, because it would require more clicks to set a simple timestamp. 

Hence, I propose to keep this issue to differenciate between 'schedule' and timestamp' in the modal header.

**Comment by aspiers** [comment]
[**@munen**](https://github.com/munen) commented on [January 9, 2020 10:41 AM](https://github.com/200ok-ch/organice/issues/217#issuecomment-572502930 "2020-01-09T10:41:36Z - Replied by Github Reply Comments"):
> [@aspiers](https://github.com/aspiers) [@schoettl](https://github.com/schoettl) Does either of you want to work on this?
> 
> One note I want to make: Currently, it's always "edit timestamp", never "create timestamp". Rationale: As soon as you hit the action button, you'll have a corresponding timestamp for today. In the modal, you can change the date or delete the timestamp altogether.
> 
> It would be possible to change this behavior, but that would not be trivial - even from a UX standpoint, because it would require more clicks to set a simple timestamp.

Makes sense.

> Hence, I propose to keep this issue to differenciate between 'schedule' and timestamp' in the modal header.

Thanks - that was my original intention.

> PS: This is not a bug according to the contributor guidelines: [/CONTRIBUTING.org@`master`#did-you-find-a-bug-or-do-you-want-to-implement-a-new-feature](https://github.com/200ok-ch/organice/blob/master/CONTRIBUTING.org#did-you-find-a-bug-or-do-you-want-to-implement-a-new-feature)

OK.  There's a certain degree of subjectivity here - personally when I encounter something for which the UI/UX is not optimal, I tend to think of it as a minor UI/UX bug, but I agree it also makes sense to think of it as an enhancement.

However in this case I think it's fair to say that fixing this issue would be an enhancement but would *not* be an implementation of a new feature.  And the section header you link to and https://github.com/200ok-ch/organice/issues/new/choose both present a binary choice between "bug" and "feature request", so neither of them currently cater in an optimal way to filing enhancements for *existing* features.  I would have happily applied the `enhancement` label when filing this rather than `bug`, if that option had been presented to me, but it wasn't.  So I think there's room for improvement in both the contributor guidelines and the issue templates.

**Comment by schoettl** [comment]
I would try to implement that. I assigned me for this issue.

**Comment by munen** [comment]
@schoettl :+1:

**Comment by munen** [comment]
We have a distinction between "edit deadline" and "edit schedule" since merging #751, but forgot to close the issue.

Thank you, @aspiers, for the initial report :pray: 
 
![image](https://user-images.githubusercontent.com/505721/175906426-71fd76f2-48c2-46d9-9bcb-856c699ea46a.png)

**Comment by aspiers** [comment]
Fantastic, thanks @munen! I hope to get back to using organice sometime this summer. And I would also love to come on a coding/meditation retreat sometime too ;-)
