### ISSUE TITLE
Discuss if it makes sense to use more differentiated icons for SCHEDULED and DEADLINE

### ISSUE THREAD

**Issue by aspiers** [200ok-ch/organice#218]
(This is a minor UI/UX bug, but when combined with #217 it becomes a slightly more significant problem.)

The two [new `DEADLINE` and `SCHEDULED` icons](https://github.com/200ok-ch/organice/issues/188#issuecomment-571730711) look very similar and it's not immediately obvious which is which. I would recommend switching the deadline icon to something a little more alarmist (literally!). For example using this for the deadline icon would have nicely expressed greater urgency:

- https://fontawesome.com/icons/alarm-exclamation?style=duotone

but unfortunately it's only accessible via Font Awesome Pro, so can't be used in an open source project :cry:

**Comment by munen** [comment]
This is _not_ a bug. Please read the contributor guidelines: https://github.com/200ok-ch/organice/blob/master/CONTRIBUTING.org#did-you-find-a-bug-or-do-you-want-to-implement-a-new-feature

> The two [new `DEADLINE` and `SCHEDULED` icons](https://github.com/200ok-ch/organice/issues/188#issuecomment-571730711) look very similar and it's not immediately obvious which is which

What happend to the aspiers from this statement?(;

![image](https://user-images.githubusercontent.com/505721/72059535-825ee700-32d2-11ea-917e-f9be13fafc69.png)

I'm not against changing icons, however:

1. Semantically, a SCHEDULED and a DEADLINE item are very similar. The semantics are that they will show up in the Agenda (calendar). They differ only slightly in what the time means in the calendar. Hence, imo it's proper valid to have calendar icons.
2. An alarm icon is not correct. organice does not set alarms and bring up notifications.
3. I'll consider using a Font Awesome Pro icon if someone donates a pro account. But even then, an alarm icon is semantically wrong.
4. To make the meaning clear, the icons have a mouseover and are documented in sample.org with links to the original Org documentation.

**Comment by aspiers** [comment]
[**@munen**](https://github.com/munen) commented on [January 9, 2020 10:27 AM](https://github.com/200ok-ch/organice/issues/218#issuecomment-572495615 "2020-01-09T10:27:15Z - Replied by Github Reply Comments"):
> This is _not_ a bug.

It's also not a feature request, but those are currently the only two options both presented and documented, as I mentioned in https://github.com/200ok-ch/organice/issues/217#issuecomment-572590664 just now.

> Please read the contributor guidelines: [/CONTRIBUTING.org@`master`#did-you-find-a-bug-or-do-you-want-to-implement-a-new-feature](https://github.com/200ok-ch/organice/blob/master/CONTRIBUTING.org#did-you-find-a-bug-or-do-you-want-to-implement-a-new-feature)

Sure, I already read them, but I think there's still a gap in those guidelines and the corresponding issue templates.  What happens if, as it did here and in #217, the answer to "Did you find a bug or do you want to implement a new feature?" is "no"?  I'd be happy to instead file a "blank" issue via https://github.com/200ok-ch/organice/issues/new with no labels, if you'd prefer that.

> > The two [new `DEADLINE` and `SCHEDULED` icons](https://github.com/200ok-ch/organice/issues/188#issuecomment-571730711) look very similar and it's not immediately obvious which is which
> 
> What happend to the aspiers from this statement?(;
> 
> [![image](https://user-images.githubusercontent.com/505721/72059535-825ee700-32d2-11ea-917e-f9be13fafc69.png)](https://user-images.githubusercontent.com/505721/72059535-825ee700-32d2-11ea-917e-f9be13fafc69.png)

Still here ;-)  AFAICS I don't think I contradicted myself.  I still believe 100% it's right to optimise for regular users over newbies; however of course that does not mean we should stop trying to make things easier for newbies when it does not negatively impact regular users.  And increasing the differentiation between these two icons should be beneficial for all users, regardless of their level of experience, so there is no trade-off required here.

> I'm not against changing icons, however:
> 
> 1.  Semantically, a SCHEDULED and a DEADLINE item are very similar. The semantics are that they will show up in the Agenda (calendar). They differ only slightly in what the time means in the calendar. Hence, imo it's proper valid to have calendar icons.

I'm also fine with calendar icons for both.  The problem arises from them being so similar looking.

> 2.  An alarm icon is not correct. organice does not set alarms and bring up notifications.

True.  The suggestion was more about using the exclamation mark to express greater urgency, rather than about using an alarm clock per se.  For example if the deadline icon was a calendar icon with an additional exclamation mark surrounded by a circle in the top-right corner, to me that would be plenty good enough to distinguish the two.  From a quick glance at https://fontawesome.com/license/free I think we might be able to edit and redistribute an existing free fontawesome icon.

> 3.  I'll consider using a Font Awesome Pro icon if someone donates a pro account. But even then, an alarm icon is semantically wrong.

Unfortunately we can't use Pro icons in an Open Source project.  https://fontawesome.com/plans#faq-standard-pro-license says:

> Pro is commercial software, so there are some restrictions. The biggest one is that you cannot distribute Pro to folks not specifically covered by your license (e.g. you can't provide the files in your open source public repo).

> 4.  To make the meaning clear, the icons have a mouseover and are documented in sample.org with links to the original Org documentation.

That's great of course, but the mouseover has no effect on most mobile devices, and it's nice if the UI is intuitive enough to minimise the need to read the docs.

**Comment by munen** [comment]
> It's also not a feature request,

It's not, you're right.

> Sure, I already read them, but I think there's still a gap in those guidelines and the corresponding issue templates. What happens if, as it did here and in #217, the answer to "Did you find a bug or do you want to implement a new feature?" is "no"? I'd be happy to instead file a "blank" issue via https://github.com/200ok-ch/organice/issues/new with no labels, if you'd prefer that.

That would be great. This would be totally aligned with this section:

![image](https://user-images.githubusercontent.com/505721/72099858-c88f6700-3321-11ea-894d-0c0382363ad0.png)

**Comment by munen** [comment]
> Still here ;-) AFAICS I don't think I contradicted myself. I still believe 100% it's right to optimise for regular users over newbies; however of course that does not mean we should stop trying to make things easier for newbies when it does not negatively impact regular users. And increasing the differentiation between these two icons should be beneficial for all users, regardless of their level of experience, so there is no trade-off required here.

Sweet, welcome! :hugs: 

> Unfortunately we can't use Pro icons in an Open Source project. https://fontawesome.com/plans#faq-standard-pro-license says:

Thanks for checking on that. That'll make future decisions easier.

Generally speaking, I'm not against changing the icon provider completely, of course. Fontawesome is just a good general start for a new project. If somebody comes up with some icon set that has all the things we need and in a better configuration, I'm all for it! Especially if it would be FOSS(;

> True. The suggestion was more about using the exclamation mark to express greater urgency, rather than about using an alarm clock per se. For example if the deadline icon was a calendar icon with an additional exclamation mark surrounded by a circle in the top-right corner, to me that would be plenty good enough to distinguish the two. From a quick glance at https://fontawesome.com/license/free I think we might be able to edit and redistribute an existing free fontawesome icon.

Greater urgency makes sense. I did take my time on searching for icons - in my initial runs I came up empty. But then there were some people commenting on that there shouldn't be text, but only icons, so i re-tripled my effort and also involved my wife. We came up to use the bold calendar, because **bold** is more urgent. Personally, I'm happier with the icons than the text, so it's a good step forward.

I quickly looked at the license. It's a little complicated that they have so many. In any case, it looks like we can make an edited version. However, it implies these tasks:

1. Change the integration of the icons from a 3rd-party font icon set to using SVGs
  - That wouldn't be a bad choice in any case. Having SVGs would decrease file size and would enable us to bundle it with the application. Hence they would be more resilient to use offline compared to know.
  - As I read the license, that would give us "CC BY 4.0 license" which allows for remixing and redistribution.
2. Someone with some arts skills needs to design a new icon.
3. Someone needs to double check if the license is how we understand it after a quick glance.

@aspiers Would you be interested in either doing 1. or 2.?

**Comment by aspiers** [comment]
[**@munen**](https://github.com/munen) commented on [January 9, 2020 8:02 PM](https://github.com/200ok-ch/organice/issues/218#issuecomment-572731143 "2020-01-09T20:02:30Z - Replied by Github Reply Comments"):
> Generally speaking, I'm not against changing the icon provider completely, of course. Fontawesome is just a good general start for a new project. If somebody comes up with some icon set that has all the things we need and in a better configuration, I'm all for it! Especially if it would be FOSS(;

Agreed :-)

> Greater urgency makes sense. I did take my time on searching for icons - in my initial runs I came up empty. But then there were some people commenting on that there shouldn't be text, but only icons, so i re-tripled my effort and also involved my wife. We came up to use the bold calendar, because **bold** is more urgent. Personally, I'm happier with the icons than the text, so it's a good step forward.

Totally agree!

> I quickly looked at the license. It's a little complicated that they have so many. In any case, it looks like we can make an edited version. However, it implies these tasks:
> 
> 1.  Change the integration of the icons from a 3rd-party font icon set to using SVGs

We could mix'n'match: use an edited SVG just for cases like this where we want our own version, and fontawesome for the rest.  It's not ideal but might be a reasonable short-term solution at least.

> *   That wouldn't be a bad choice in any case. Having SVGs would decrease file size and would enable us to bundle it with the application. Hence they would be more resilient to use offline compared to know.

Exactly.

> *   As I read the license, that would give us "CC BY 4.0 license" which allows for remixing and redistribution.

Yes I think so.

> 2.  Someone with some arts skills needs to design a new icon.

I don't really have art skills but I could probably manage to add an exclamation mark to the existing icon.

> 3.  Someone needs to double check if the license is how we understand it after a quick glance.
> 
> [@aspiers](https://github.com/aspiers) Would you be interested in either doing 1. or 2.?

I'll try to give it a go if noone else beats me to it.  However I want to tackle the parser first, as that has a much bigger impact on functionality ;-)

**Comment by munen** [comment]
Great, good luck with the parser and the artwork^^ 👍

**Comment by munen** [comment]
Closing as per https://github.com/200ok-ch/organice/blob/master/CONTRIBUTING.org#how-we-work-with-issues. If you choose to work on this at some point, please re-open the issue.
