### ISSUE TITLE
As a user, when I see a web link (http[s]), I want to be able to click it

### ISSUE THREAD

**Issue by munen** [200ok-ch/organice#23]
When rendering the org file, check for web links and make them anchor tags.

**Comment by schoettl** [comment]
Does it make sense to wait for the new org-parser with this? Does the new parser also parse the body of headlines? Specifically, can it parse the body and URIs like `https://xxx` and also `email@address.es`?

Or is it better to do this while rendering (via regexes for mail address and URIs)? Then mail-addresses in property values and titles would also be clickable.

**Comment by munen** [comment]
@schoettl

> Does it make sense to wait for the new org-parser with this? 

What makes sense and what doesn't would be up to you. If you want to work on the feature now, I propose that you should work with the current parser. The alternative is to get the new parser on feature parity with the existing one and make a PR on organice to replace the old with the new one. The latter option is going to require quite a lot of work, though.

> Or is it better to do this while rendering (via regexes for mail address and URIs)? Then mail-addresses in property values and titles would also be clickable.

That would be the first option. If you want to work on this feature before the new parser is ready, that's the best way to go forward.

[Here's](https://github.com/200ok-ch/organice/blob/master/src/lib/parse_org.js) the implementation of the parser and [here](https://github.com/200ok-ch/organice/blob/master/src/components/OrgFile/OrgFile.unit.test.js#L22-L145) are the parser tests to get you started.

> Does the new parser also parse the body of headlines?

Yes. [Here](https://github.com/200ok-ch/org-parser/blob/master/test/org_parser/parser_test.cljc) are the tests of the new parser where you can see what's being parsed alrady.

**Comment by munen** [comment]
@schoettl Adding this in today is a wonderful christmas present!

Great job - I'm certain you're making quite a few people happy with that. For sure I can say that I am. This is one of the features that'll be using a lot(;

:pray: :bowing_man:

**Comment by munen** [comment]
I also updated the changelog with this major contribution and added your attribution: https://github.com/200ok-ch/organice/commit/6eb97cee16c5e124cb049d5b97d5d855c8ed7ef5
