### ISSUE TITLE
As a (power-)user, I want to be able to host organice on my own machine.

### ISSUE THREAD

**Issue by maqiv** [200ok-ch/organice#238]
Hey

First of all thank you very much for developing organice. I like it a lot.

I'm running my own webserver which also hosts a WebDAV server service. Now I would like to also host an instance of organice on that machine so I don't have to deal with CORS.
Thus and because organice is a web application consisting of static web files, it would be great to have a downloadable release package which contains a compiled version of organice and can easily be deployed to a webserver.

Best regards

**Comment by munen** [comment]
Hi @maqiv 
> First of all thank you very much for developing organice. I like it a lot.

Thank you for using organice and the kind words. :pray: 

> Now I would like to also host an instance of organice

What holds you back regarding your request?

Here's documentation to get you started: https://github.com/200ok-ch/organice#deployment

Best of luck and enjoy^^

**Comment by maqiv** [comment]
Hi @munen 

Thank you very much for your fast response.

> What holds you back regarding your request?

As a lazy person (🙈) without any of the prerequisites installed I would love to be able to download a compressed archive containing a compiled version of organice.

Greets 😊

**Comment by munen** [comment]
> As a lazy person (🙈) without any of the prerequisites installed I would love to be able to download a compressed archive containing a compiled version of organice.

We've got you covered. Here's how to get organice running using Docker. No building of organice required: https://github.com/200ok-ch/organice/#docker

**Comment by maqiv** [comment]
Ok, I was hoping to get around docker, but you got me 😆.

Thank you very much for your patience 🤗

**Comment by munen** [comment]
:+1:
