### ISSUE TITLE
Remove LOGBOOK entries?

### ISSUE THREAD

**Issue by Linuus** [200ok-ch/organice#242]
I accidentally clicked the hour glass icon and got some clock timestamps in the LOGBOOK drawer. Is there a way to remove this drawer? Whenever I edit it, remove all the text and press Done, it gets re-added.

**Comment by munen** [comment]
Hi @Linuus 

Thank you for reporting this bug, I confirm this issue!

This was an oversight when the time clocking feature was built. I just fixed it in PR https://github.com/200ok-ch/organice/pull/244 and refactored the code to make such an oversight less likely in the future. The change is already deployed to organice.200ok.ch - please make sure to load the newest version of organice and then you can delete the `LOGBOOK` drawer - or make any other manual adjustment you wish to do.

Thanks again and I apologize for the inconvenience :pray: 

P.S.: If you accidentally hit other mutating buttons in organice, you can always undo and redo them. There's respective icons on the very top header bar. Not to say you should have done this in this scenario, you found a legit bug which I'm happy about^^

**Comment by Linuus** [comment]
Awesome! Thanks! 😊👍

**Comment by dimitar-petrov** [comment]
Hello @munen, @Linuus 
I am currently noticing the same issue with latest docker deployment: twohundredok/organice:3628

Did this issue regressed?

**Comment by schoettl** [comment]
For me, it's working on organice.200ok.ch although it's a hidden feature. In the new "edit description" pane, click on the edit button a second time, then you can delete the logbook. As an alternative you can use the undo feature.

**Comment by dimitar-petrov** [comment]
@schoettl, Thanks, also the "Prefer raw values" option has to be enabled in order to be able to edit the logbook drawer.

**Comment by schoettl** [comment]
But it is, by default? I didn't change it.

**Comment by munen** [comment]
Hi @dimitar-petrov 

Thank you for the report. @schoettl and you are right in your description. When we introduced the semantic editor, we only documented it in the changelog. I've added some documentation to the help documentation: https://github.com/200ok-ch/organice/pull/769

**Comment by munen** [comment]
@schoettl The "prefer raw values" option doesn't have a default option (and hence is disabled for new users imo): https://github.com/200ok-ch/organice/blob/master/src/util/settings_persister.js#L201

I think that's a sane UX default for a generic organice user - they can create drawers (like logbook and properties) through the UI and interact with them in the semantic view. But when editing the description of the header, they don't get in the way. The more technical (or experienced) user can enable the 'raw' view.
