### ISSUE TITLE
Google Drive no sign in possible

### ISSUE THREAD

**Issue by poulpoulsen** [200ok-ch/organice#253]
Hello,
i try to sign in with my Google Drive account, but it isn't working from Smartphone (Android 9 Firefox/Chrome) or Laptop (Linux Mint 19.3 Firefox/Chromium). I can click on it, but nothing happens. No error or anything else.
Is it working?
Please could you give me an advice.

Regards
Poul

**Comment by schoettl** [comment]
Hi Poul, I think it is related with #127 and we're waiting for Google to fix this...

**Comment by munen** [comment]
Yes, we have already done all we can. We're waiting since 4 months on Google to set us up.

Status reports are here: https://github.com/200ok-ch/organice/issues/127

In the meantime, until Google starts to do some work, you're welcome to use Dropbox or Webdav synchronization.
