### ISSUE TITLE
Parsing of timestamps with 12-hour clock convention fails

### ISSUE THREAD

**Issue by munen** [200ok-ch/organice#255]
For example `SCHEDULED: <2020-02-17 Mon 1:00pm>` is not recognized as a timestamp.

Resources:

- https://orgmode.org/manual/Timestamps.html

**Comment by schoettl** [comment]
Hm, ISO 8601 does not support the am/pm format.

The page you linked provide no examples for am/pm time and it says
> The Org date format is inspired by the standard ISO 8601 date/time format. To use an alternative format, see Custom time format.

OK, at least org mode recognizes am/pm times as timestamps...

**Comment by munen** [comment]
Emacs does support them, though-_-

I recognized that, because my agenda on Emacs and organice didn't look the same.

**Comment by schoettl** [comment]
Quoting [wikipedia](
https://en.wikipedia.org/wiki/ISO_8601#Times):

> ISO 8601 uses the 24-hour clock system.

So according to orgmode doc (which points to ISO format), it's not "required" to parse 12-hour-clock format.

If I understand the doc correctly, any other display format is only a text overlay (using text emacs properties). And orgmode should never generate am/pm by itself.
https://orgmode.org/manual/Custom-time-format.html

I'm asking because I'm not convinced to implement am/pm in [org-parser](https://github.com/200ok-ch/org-parser/pull/2).

I guess, the reason why emacs generously accept am/pm is that (some) system date parsing functions just accepts this format, e.g. `date -d8:00pm` is valid even under german locale.

**Comment by munen** [comment]
@schoettl Thank you for double checking the ISO standard. It made me curious and look a little around the Org mode code. I don't think that Org mode parses am/pm by coincidence, now. In `org.el` it defines multiple regexps which include am/pm - for example `org-plain-time-of-day-regexp` (quoting from it's docstring: "Regular expression to match a plain time or time range. Examples:  11:45 or 8am-13:15 or 2:45-2:45pm.").

There's also Org mode docs that mention the format (for example https://orgmode.org/manual/Time_002dof_002dday-specifications.html).

Hence, I agree that it's not clearly specified, this is what happens if I put them against each other:

Reasons against am/pm:

1. The spec mentions that it implements ISO 8601 which doesn't do
   am/pm.

Reasons in favor of am/pm:

1. The Org mode code implements am/pm.
2. There's docs having examples of timestamps with am/pm format.
3. am/pm timestamps work in Org mode in Emacs.

So I understand what you're getting at, but in my book it's a 3:1 win
in favor of am/pm, unless I'm missing some points against am/pm here(;

**Comment by schoettl** [comment]
OK, if it's no coincidence, then we should also implement this am/pm format, even if I don't like this format ^^

I wonder, how the example "2:45-2:45pm" is to be interpreted? Does the "pm" counts for both? Or is "am" the default, if missing?

**Comment by munen** [comment]
Very good question, from https://en.wikipedia.org/wiki/12-hour_clock: "When abbreviations and phrases are omitted, one may rely on sentence context and societal norms to reduce ambiguity. For example, if one commutes to work at "9:00", 9:00 a.m. may be implied, but if a social dance is scheduled to begin at "9:00", it may begin at 9:00 p.m."

Having said that, since Org mode doesn't have 'social context', it defaults to 'am' as I would have expected:

![image](https://user-images.githubusercontent.com/505721/80288835-fb2b6700-873a-11ea-9206-aab015ea675d.png)

![image](https://user-images.githubusercontent.com/505721/80288837-041c3880-873b-11ea-9af4-0db5556117be.png)

**Comment by munen** [comment]
NB: From testing, `3pm` is not a recognized time whilst `3:00pm` is.

**Comment by schoettl** [comment]
@munen could you provide the orgmode source location of the am/pm parsing? I'd implement it in org-parser but I'm not sure about the supported syntax. Is it just `am|pm` or `[aA]\.?[mM]\.?|...`?

It obviously differs from the GNU/Linux date parsing. E.g. `date -d 8am` works.

**Comment by munen** [comment]
@schoettl There's multiple Regexps in the Emacs Org mode code relating to am/pm, but here's one: https://github.com/emacs-mirror/emacs/blob/763df4bc171c9742cf04b029ddfe495d52461bcf/lisp/org/org.el#L4143

**Comment by schoettl** [comment]
Thanks. Implemented in https://github.com/200ok-ch/org-parser/pull/9/commits/c429bb4226a687a1053f99dcde2fbbe27155164a :)

**Comment by munen** [comment]
@schoettl Sweet, great stuff! 🙏 

Closing this issue, then.
