### ISSUE TITLE
Search notes under heading

### ISSUE THREAD

**Issue by rodelrod** [200ok-ch/organice#257]
**Is your feature request related to a problem? Please describe.**
The current search feature seems to be restricted to the heading and its properties. This makes me miss a lot of matches in which the target string is only in the body of the note.

**Describe the solution you'd like**
As a user, when I search for "astring" I see a list of heading which include "astring" either in the heading text or in the text under the heading. Ideally I see a snippet of the matched line under the heading.

**Describe alternatives you've considered**
I don't see any alternative on mobile.

**Comment by schoettl** [comment]
Right, the current search only searches in title, properties, and tags. I implemented this search feature.

We could add a new type of search term `desc:astring` or `desc:"a string"` to search in the description text.

However, I would not make make the search term `astring` searching the description text by default. Because (at least in my org files) this would yield way too much false-positives.

If someone wants to work on that feature: the additional filter syntax must be added in the headline filter parser pegjs file and the matching logic must be implemented in headline_filter.js.

**Comment by rodelrod** [comment]
Thanks for the quick reply. 

> However, I would not make make the search term `astring` searching the description text by default. 

Any chance you would be open to reconsidering this? 

I'll try to state my case: searching the full text of the entry is the behavior of all search libraries that I'm acquainted with in org (org-agenda, org-ql, helm-org-rifle, ...) The same is the case for most other personal information management tools (outliners, task managers, note-taking apps). 

> Because (at least in my org files) this would yield way too much false-positives.

If the first search yields too many false-positives, you drill down by adding the search term as you suggest (e.g. `heading:astring`). Drilling down a too broad search tends to come more naturally to people than widening a search when there aren't enough matches. 

> If someone wants to work on that feature: the additional filter syntax must be added in the headline filter parser pegjs file and the matching logic must be implemented in headline_filter.js.

I'm quite tight with time but may consider tackling it this weekend, if I get one :).

**Comment by schoettl** [comment]
Hm, you have good points, the comparison to other search utils. At the end it's a decision of the maintainers, of course, not my decision alone.

But let me outline the reasons for how it is: The search was originally intendet for filtering a task list. Then also as general search and as a selector for refiling.

- For the task list I always want to filter for the task title in the first place.
- Also for refiling, IMO, filtering for the title is more important than description text.
- One of the special features of the search is the smart-case search. E.g. searching for "TODO" effectively finds TODO headers. This is simplicity for me. If that would search full-text it would probably yield much more false-positives.
- I found myself being faster (in real org mode) when I first only search in title. In my org flies, sparse tree finds dozens of unrelated headlines whereas the title search would find only a few.

If you're worried about always having to type "desc:", that's not a problem. We already have a completion system for the search field ;)

**Comment by munen** [comment]
Thank you @rodelrod for considering to work on this feature.

As for the implementation, it is not correct that _any_ search behaves as you describe. Let me give you some background: The current search builds on top of Emacs Org mode `org-sparse-tree` would provide. Here's a blog post building on top of that relation: https://200ok.ch/posts/2020-02-09_creating_org_mode_sparse_trees_in_emacs_and_organice.html

Beyond that, organice also implements functionality like `org-refile` which, again, searches on headlines. I could go on - for example `imenu` behaves similarly.

Having said that, if you can spare the time, I'm in favor of adding a new search query as @schoettl described. When building that, there's UI considerations, though. The current search filters on headlines. When introducing search in descriptions (which can be _huge_), how should they be indicated? One option would be "not at all", then the UI stays compatible with what we have. However, that'll defeat the purpose. Another option is to show the descriptions, but then you have to make sure that it's going to be usable - and that it's not breaking existing functionality.

**Comment by munen** [comment]
@schoettl Since the creator of the ticket is not interested in working on this, and I don't see how to reconcile the UX/UI considerations I outlined in the comment above, I vote to close this issue. If you have an idea on how to implement the UI, I'm happy to leave it open, of course.

**Comment by munen** [comment]
@rodelrod Are you still planning to work on this issue? Otherwise I'll close the issue as per the [contribution guidelines](https://github.com/200ok-ch/organice/blob/master/CONTRIBUTING.org#how-we-work-with-issues).

**Comment by rodelrod** [comment]
@munen Sorry for the lack of answer. Your comment deserved more timely attention. 

I see that the search features that you mention in org-mode, as well as the choice of naming for the body test ("descriptions") suggest the usage of Organice as a task management solution. 

I'm coming from a different angle. I already have an excellent task management solution on mobile in the form of beorg, coupled with org-agenda on desktop. My hopes for Organice were for a solution for my need as a *knowledge base*, where the headlines contain maybe 10% of the text that I need to search. 

I understand that even in desktop org-mode this is a challenge for performance reasons, so many of the solutions are headline-oriented. Also, functions such as `org-refile` fit naturally into a model of headline search. The exceptions that I listed above have performance limitations so I have to be careful managing them.

I have since understood that Organice will not help me with my knowledge base—not only because of search but also other reasons, such as the per-file handling. So I'm no longer using it for now.

Thanks for your attention and your contributions to the Org ecosystem.
