### ISSUE TITLE
No root list item, causes error

### ISSUE THREAD

**Issue by moconnor-leavened** [200ok-ch/organice#262]
If I open a note with out any nodes it causes an error screen.

This would be helpful for note files that are intended to be small.

**Comment by munen** [comment]
Hi @moconnor-leavened 

Thank you for your issue. At this point, organice requires a file that's not empty [as documented](https://organice.200ok.ch/documentation.html#org49867a5).

Would you like to work on mitigating this requirement?

**Comment by munen** [comment]
As per the [contribution guidelines](https://organice.200ok.ch/documentation.html#org62022ee), I'm closing this issue since there's no contributor for it. Feel free to re-open this issue when you find the time and effort to work on it.
