### ISSUE TITLE
WebDAV CORS headers missing

### ISSUE THREAD

**Issue by haji-ali** [200ok-ch/organice#264]
I am trying to use the backend in `https://organice.200ok.ch/` on my iPhone with pcloud and WebDAV (https://webdav.pcloud.com) to sync my org files. 

When I input the WebDAV URL and my credentials (email/password), I get "There was an error retrieving files!". Looking at the console, there appears to be these errors:

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://webdav.pcloud.com//. (Reason: CORS header 'Access-Control-Allow-Origin' missing).

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://webdav.pcloud.com//. (Reason: CORS request did not succeed).
```
So the header `Access-Control-Allow-Origin` is missing. I assume I cannot set this from my side without having my own backend, correct? There are others issues mentioning similar problems with no resolution (#77, #117, #225, #178)

Also, can you please tell me where are the WebDAV credentials saved when I use the backend `https://organice.200ok.ch` on my phone? Are they saved in cookies?

**Comment by munen** [comment]
Thank you for using organice!

The issue you describe is not with organice, this is how the web and WebDAV work. 

The organice docs have you covered, though: https://organice.200ok.ch/documentation.html#orga6f24ad

Good luck tweaking your setup accordingly and all the best!

**Comment by schoettl** [comment]
> Also, can you please tell me where are the WebDAV credentials saved when I use the backend `https://organice.200ok.ch` on my phone? Are they saved in cookies?

I have not checked, but since 200ok.ch and the connection should not be interested in the credentials, I believe that they are saved in local storage in the browser.

I don't know where to find the proof in the code but you can just check the cookies using the browser dev tools. It is the same thing on desktop and mobile...

**Comment by munen** [comment]
Regarding credentials: Yes, they are only accessible to the devices you're logging in with - on localStorage. Here's the relevant code for WebDAV: https://github.com/200ok-ch/organice/blob/master/src/App.js#L77-L80

Thanks @schoettl for jumping in. I didn't even see the second question, because it's completely unrelated to the title.

**Comment by haji-ali** [comment]
I would like to expand on the WebDAV issue a little bit.

I am surprised that organice is not working with my WebDAV service and would like to understand the reasons. I use this service with davfs2 and with beorg and they both are working fine. Since the WebDAV service is on pcloud, I cannot debug that side.

I see that the relevant code is in https://github.com/200ok-ch/organice/blob/master/src/sync_backend_clients/webdav_sync_backend_client.js
where a `webdav` library is used. However, I couldn't find the source of that library. Is it  perry-mitchell's?

**Comment by munen** [comment]
All the docs you need are here: https://organice.200ok.ch/documentation.html#orga6f24ad

Web applications have a different sandbox and threat model than native applications (like Beorg).

Technically, there's nothing I can do for you short of rewriting the browser you're using. A more prudent action would be to include the CORS headers for your storage - or use storage that doesn't require them - like Dropbox or another webdav host.
