### ISSUE TITLE
Dev en setup: start script has error with sed

### ISSUE THREAD

**Issue by chrismatheson** [200ok-ch/organice#273]
Hi, just looking to hack about on organise, but I've failed at the first hurdle it seems :)

I ran `npm start` (although I did try yarn just to make sure and got the same error) and got the following error

```
$ ./bin/compile_search_parser.sh && react-scripts start
sed: 1: "src/lib/headline_filter ...": bad flag in substitute command: 's'
error Command failed with exit code 1.
```

im not good with sed so I can't contribute a fix im afraid

**Comment by schoettl** [comment]
Looks like you have an old version of sed.

What version do you have? Operating system? Can you install GNU sed?

**Comment by schoettl** [comment]
Oh, and you better use `yarn start`.

**Comment by chrismatheson** [comment]
im using OSX standard sed 10.14.6. Is there a need for yarn, I guess its not a huge thing, I just resent having multiple packagemanagers for a single language.  

as far as I can see, the reason for the script is to have enlist ignore the generated files (makes sense. 

I was looking into a method of doing this with the existing react-scripts config stuff. I guess thats maybe been looked into already?

**Comment by chrismatheson** [comment]
assuming that the error only affects the ESLint reporting, I should still be able to run the program by calling `nix react-scripts start` directly yes?  b/c that causes other errors :)

```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:117:11)
    at Object.join (path.js:1039:7)
```

**Comment by schoettl** [comment]
I'm not sure about yarn, but for this project, it's the recommended way, see README.

I suggest, you try yarn and comment out the failing sed command or install GNU sed.

**Comment by chrismatheson** [comment]
ok yeah, after an install with yarn I can get a working version up. thanks :) I wonder what the problem is there.....

**Comment by chrismatheson** [comment]
(maybe) this issue could be re-opened with a sort of "more robust, method of excluding files from ESLint" but for now you have helped me get to the bottom of things, thanks @schoettl :)

**Comment by schoettl** [comment]
Yea, if you find out, why your sed does not understand the "i" (insert) command this way, that would be interesting.

Anyway, a fix should be cleaner than the current solution. We previously had shell code with cat and temp files but that was less robust.

**Comment by munen** [comment]
Regarding the sed incompatibility: Apple has a long standing problem with including recent GNU utilities. They are always way out of date. Sometimes they also include BSD alternatives.

Hence, most devs in OSX either use a Linux VM for development or install the GNU utilities through their favorite package manager (i.e. homebrew).
