### ISSUE TITLE
new tags gone after browser refresh

### ISSUE THREAD

**Issue by tcwinn** [200ok-ch/organice#286]
**Describe the bug**
The tag icon works beautifully in allowing me to assign selected newly created tags to each header. I really enjoy the display of the assigned tags. 
However, when the browser is refreshed, these tags become part of the header. For example, "this is header 1:TAG:"
When touching the tag icon again, it doesn't recognize this head has any tag at all. And the previously created tag list no longer exists. New tags have to be created. 
Each browser refresh appends the newly assigned tag to the end of the header.

**To Reproduce**
1. Assign new tags using the tag icon
2. Save 
3. Refresh browser

**Expected behavior**
I would expect the tag function to work across browser reloads.

**Smartphone (please complete the following information):**
 - iPhone 11
 - IOS 13.4.1
 - Browser: DuckDuckGo

**Comment by schoettl** [comment]
Good catch. I guess we save the org file without the mandatory space between headline and `:tag:`. I'll look into it.

**Comment by munen** [comment]
Thank you for the well documented bug report, @tcwinn! :pray: 

Thank you for the quick and solid bugfix, @schoettl :bow:

**Comment by tcwinn** [comment]
Thank you. Just verified it worked. This is an amzing app. I'm blown away by it. I'm an emacs user, but could never get over the intimidation of orgmode. But I'm drawn by this app. Great idea!

**Comment by munen** [comment]
@tcwinn Thank you for the kind words :pray: 

It's great to hear that organice helped you as an Emacs user to start to get into Org mode! For me, it was the other way around - I'm an Emacs user, too - and I use Org mode for anything from project management (for teams), personal GTD, papers, blog posts, controlling, bookkeeping, slides, quotes and invoices... With organice, it's possible to have access to all that on the go or from any other machine which is very helpful at times.

I'm really happy that it can work the other way around and ease an Emacs user into the depths of Org mode. To be honest, I haven't even thought about this angle so far(;

Enjoy the ride that is Org mode and all the best using organice!
