### ISSUE TITLE
Discuss configuration of prettier regarding parens behavior

### ISSUE THREAD

**Issue by munen** [200ok-ch/organice#288]
Originally reported by @schoettl https://github.com/200ok-ch/organice/pull/287#issuecomment-623694112

I have again minor problems with prettier:

```
$ npx prettier --version
1.19.1
$ prettier --version
2.0.5
```

- The newer system prettier wraps every single lambda arg in parens `(x) => x`.
- `npx prettier` does the opposite.

I personally think, the parens shouldn't be mandatory. What do you think?

I guess, we should edit `.prettierrc.json` to fix this version difference.

**Edit:**
Wow, huge discussion about it:
https://github.com/prettier/prettier/issues/812
Here is the documentation:
https://prettier.io/docs/en/options.html#arrow-function-parentheses
It looks like we can only be for or against it.

If we go with the new default, we should at some point update the whole code base. Otherwise, every contributor will change the whole file when they only want to fix one line. Which makes ugly commits in my opinion.

**Comment by munen** [comment]
@schoettl You are right, I agree that we should deal with this properly to keep future commits and PRs clean from changes in the tooling. Let's have a quick discussion on what we want to do.

There's two valid options:

1. Change the codebase to the new default (always to have parens in arrow functions)
2. Add `"arrowParens": "avoid"` to `.prettierrc.json`

Generally speaking, I can live with both. But since you brought it up, let's pick the solution we're both the happiest with.

Option 2 has the benefit that it's the easiest to implement. It also conforms to the JS spec in that the parens are optional for exactly one parameter.

Personally, I'd go for option 1, though. The rationale is:

- Generally, I'm not a big fan of adding more syntax to languages for special cases
- Imo it's harder to read. Generally, I like it when a language is concise, but I don't like it when the rule for syntax changes multiple times depending on a small change in the coede. It also leads to bigger diffs.
- I've seen quite a few people trip up over this particular change. "Oldtimers" (who learned JS years ago and are well versed in ES5) are often confused that no arguments equal parens, one argument equals no parens and multiple arguments equal parens. I've seen them think it's a bug in the code.

Hence, I'd opt for option 1 and can happily make a PR with the change added to the codebase.

Having said that, if you're a fan of the optional parens, then let's just add the config flag to prettierrc. My opinion above is just that - I weak and non authorative opinion(;

**Comment by schoettl** [comment]
Thanks for opening the separate issue!

I can also live with both. I stated my initial opinion (favouring option 2) before I read the reasons for the change of default. Now, I'd also go with option 1, always parens around lambda args.

OK, should be a simple change...
```
find . -name \*.js | xargs prettier --write
```

Can you, when you provide the PR, please also update the prettierrc, so that contributers using an older version of prettier don't mess up the code?

**Comment by munen** [comment]
@schoettl Ack!
