### ISSUE TITLE
minor touch mode for list

### ISSUE THREAD

**Issue by tcwinn** [200ok-ch/organice#295]
**Is your feature request related to a problem? Please describe.**
Editing a list (plain, ordered, or checkbox) on a touch screen is cumbersome. Select copy and paste can be slow and painful.

**Describe the solution you'd like**
Implement a minor mode for list similar to table. Instead of tapping on a cell, in this case a list entry. And the arrows would inherit the list mode instead of table mode. Up would be moving the entry up one; down would be moving the entry down one; right would indent one level; left would un-indent one level. An edit icon would enable editing of the entry itself. This would make it very intuitive without user having to deal with the raw hyphen and space characters.

**Comment by munen** [comment]
Thank you for opening an issue. This issue addresses a similar point: https://github.com/200ok-ch/organice/issues/21

Are you interested in implementing either of the options?

**Comment by tcwinn** [comment]
Yes, I read #21 before opening this one. I'm so impressed with the table editing function that I think it should be applied to lists.
I would love to implement if I have the skill set. But I don't. So I love to contribute any other way I can.

**Comment by munen** [comment]
@tcwinn Have you seen that you can move headers around? Here's a demo: https://youtu.be/aQKc0hcFXCk?t=360

Imo, it would be hard to make a UX distinction between headers and list items. If you see a good option, please feel free to make a mockup.

If you don't plan to work on this issue, I'd kindly refer you to "How we work with issues" in the docs: https://organice.200ok.ch/documentation.html#org82cbeed

**Comment by tcwinn** [comment]
Yes, I love the way we can move the headers around. It would be nice if we can apply the same to list items. Maybe this was too much to ask.

Please close this item until someone is willing to tackle it.

Thank you.

**Comment by munen** [comment]
🙏🏻
