### ISSUE TITLE
Couldn't parse file after deleting an item

### ISSUE THREAD

**Issue by zoechi** [200ok-ch/organice#312]
**Describe the bug**
I deleted an item of an Org file and after that Organice refused to render the file.

**To Reproduce**
1. Open README.org from this zip file in Organice
[README.org.zip](https://github.com/200ok-ch/organice/files/4707556/README.org.zip)

2. Delete the first entry with the Bookmarklet code by swiping it to the left

3. Organice shows

> Couldn't parse file

**Expected behavior**
The file should be rendered just without the deleted file

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Pixel 3a
 - OS: Android 10
 - Browser: Stock Chrome

**Additional context**
The file is hosted on Dropbox
The content of the file is somewhat unusual as there is JS code without `#+BEGIN_SRC`...`#+END_SRC`, but Organice should still not make the file unparseable.

**Comment by schoettl** [comment]
@zoechi thanks for the report. Could you add a minimal example org file and insert it here as markdown fenced code block?

**Comment by munen** [comment]
Thank you for the bug report and the sample file.

This behavior is well known and documented: https://organice.200ok.ch/documentation.html#org8c66386

Our planned mitigation is documented, as well: https://organice.200ok.ch/documentation.html#orgab0baeb

If you don't want to wait for said mitigation, would you be willing to provide a PR beforehand with an alternative fix?

**Comment by zoechi** [comment]
I don't really care. Normally An org file  would not look like that.
I just thought it might be useful as test case.

**Comment by munen** [comment]
👍
