### ISSUE TITLE
Performance bottlenecks in headerWithPath / parentIdOfHeaderWithId

### ISSUE THREAD

**Issue by aspiers** [200ok-ch/organice#321]
[As observed on Matrix](https://matrix.to/#/!DfVpGxoYxpbfAhuimY:matrix.org/$0yve1zLCmfGR1moQABe3vcEPPUpnH3UWwjhqW2_1ong?via=matrix.org), searching a large org file for a header within a capture can be extremely slow.  Chrome dev tool's Performance tab clearly illustrates that `headerWithPath` has an issue:

![image](https://user-images.githubusercontent.com/100738/83697378-becf0e80-a5f6-11ea-9cf0-fa2669d6494d.png)

Drilling down further reveals that the cost of `parentIdOfHeaderWithId()` calling `.reverse()` is certainly an issue, but there may be others.

## To Reproduce

1. Set up a large `.org` file
2. Set up a capture template where the header doesn't match anything
3. Initiate a capture

## Expected behavior

It displays the `The specified header path doesn't exist in this org file!` message quickly.

**Desktop (please complete the following information):**
 - OS: openSUSE Tumbleweed
 - Browser: Chrome 80

**Comment by aspiers** [comment]
OK it seems another problem is that this code is `O(n^2)`:

https://github.com/200ok-ch/organice/blob/68f688dca719cc11285b4e6fcf355aa5bc746468/src/lib/org_utils.js#L191-L195

because `parentIdOfHeaderWithId()` is itself `O(n)`.

Furthermore,

https://github.com/200ok-ch/organice/blob/68f688dca719cc11285b4e6fcf355aa5bc746468/src/lib/org_utils.js#L81-L82

is twice as slow as it needs to be, because `headerWithId()` calls `indexOfHeaderWithId()`, and then throws away the result after using it to return the header.

**Comment by aspiers** [comment]
#322 and #323 have already made a significant difference here, however we could still improve by an order of magnitude by maintaining a mapping from `headerId` to `headerIndex`, which would change `indexOfHeaderWithId()` from O(n) to O(1).

However it's getting late so I should probably stop here.

**Comment by aspiers** [comment]
Worth noting that @munen [does not see the same performance issue on his iPhone Xs](https://matrix.to/#/!DfVpGxoYxpbfAhuimY:matrix.org/$t0C1TSsHXJTYINwLzQEOO13X0SjsabDkH0QrX7vdAUw?via=matrix.org), which I find utterly baffling.

**Comment by munen** [comment]
> Worth noting that @munen does not see the same performance issue on his iPhone Xs, which I find utterly baffling.

I've tried it on my slowest machine and it's still instant. Not saying that your claim is not legit, I'm just trying to reproduce here.

Here's a screencast showing how fast it is on my regular dev machine. There's no latency on my main 287kb Org file with >1200 headers.


![perf_test](https://user-images.githubusercontent.com/505721/83852435-0c8d6900-a714-11ea-865f-ce7c6f6fbbd9.gif)

**Comment by aspiers** [comment]
I have almost 4200 headers, so for an O(n^2) algorithm maybe this could be the difference between instant and taking a few seconds?  Please can you test with more headers?

**Comment by munen** [comment]
Good point, could have been. I concatenated the file onto itself (now 1.2mb, 4900 headers) and it's still instant:

![image](https://user-images.githubusercontent.com/505721/83941901-441d1380-a7ef-11ea-8e8c-9c5341dc0a73.png)

NB: The file in question is "just" my primary file, but there are quite a few others(;

**Comment by munen** [comment]
It's the same on Chromium.

![image](https://user-images.githubusercontent.com/505721/83947450-45623680-a817-11ea-9ec5-1cf25569c6ca.png)

**Comment by aspiers** [comment]
Thanks for the update! This is super weird. I'll do some more experiments - maybe it's somehow related to my .org file.

**Comment by aspiers** [comment]
Weird, I can't even reproduce now!

**Comment by munen** [comment]
> Weird, I can't even reproduce now!

Hm.. Schroedingers bug? \(^_^)/

If you and me can't reproduce, there's nothing to do. Hence, I opt to close the issue. When it comes up, again, we can open it, again.

Of course, if you'd like to spend some more time on reproducing and getting together a sample file that shows the issue, that's your prerogative!

**Comment by aspiers** [comment]
Sure, I'll reopen next time I see this.
