### ISSUE TITLE
In Timestamp edit modal: Add button "Today" to set date to today

### ISSUE THREAD

**Issue by schoettl** [200ok-ch/organice#336]
**Is your feature request related to a problem? Please describe.**
My use case is actually this: I have a property `date` in a property drawer that stores an inactive timestamp. In the end, I want to "sign off" a checklist like:
```
:PROPERTIES:
:by: Jakob
:date: [2020-06-07 Sun 18:30]
:END:
```

There is currently no option to insert/edit a timestamp in the property modal. So my work-around is to have a "predefined" timestamp `[0000-00-00]` already in the properties, that can then be edited by click with the timestamp edit modal.

At this point, I have to enter the current date manually.

**Describe the solution you'd like**
Add a button or link "Today" somewhere near the date input in the modal.

Problem: there is not much space and I don't want to mess up the modal.

**Describe alternatives you've considered**
Well, Chromium on desktop has a "Today" button in its date picker. That would be sufficient.

But my Chrome and Firefox on my Android and Firefox don't have.

So, another solution was a unified, better date picker.

What do you think?

**Comment by schoettl** [comment]
OK – after writing this, I recognized, that I was very close to the solution:

When Organice opens such a timestamp `[0000-00-00]`, the date is empty but the datepicker always defaults to today. So it is already easy to select today :)

**Comment by munen** [comment]
Cool workaround - luckily somebody thought of adding great auto-complete for property keys and values(;

**Comment by schoettl** [comment]
I defer and close this issue until we have better system datepickers or included a datepicker library.
