### ISSUE TITLE
Can it work with the local file on my computer？

### ISSUE THREAD

**Issue by 809825706** [200ok-ch/organice#373]
**Is your feature request related to a problem? Please describe.**
it seems this PWA can not work with the local file, and the bad thing is that my webdav service don’t cannot be connect. 

**Describe the solution you'd like**
it can read and write the local org file.

**Describe alternatives you've considered** 

**Additional context**

**Comment by 809825706** [comment]
![批注 2020-06-24 215833](https://user-images.githubusercontent.com/46601791/85570371-e0576f00-b665-11ea-8d27-2200ec0579a3.png)

**Comment by munen** [comment]
Web applications can never directly access local files with arbitrary permissions. That would be very dangerous.

**Comment by munen** [comment]
As for WebDAV, you might find the documentation helpful: https://organice.200ok.ch/documentation.html#faq_webdav
