### ISSUE TITLE
Checking or unchecking a checkbox discards text with markup

### ISSUE THREAD

**Issue by schoettl** [200ok-ch/organice#376]
**Describe the bug**
Checking or unchecking a checkbox discards all text with markup under the same headline.

**To Reproduce**
1. Create a header with content like:
```
hier =code= hier

- [ ] check

hier *bold* uiae
```
2. Check the checkbox in organice
3. Notice that the mark-up text has gone:
```
hier  hier

- [ ] check

hier  uiae
```

**Expected behavior**
Organice should not delete any text when checking or unchecking checkboxes.

**Desktop (please complete the following information):**
 - Firefox
 - ?

**Smartphone (please complete the following information):**
 - iOS
 - ?

**Notes:**
The deletion is not immediately visible: you have to *edit* the text or *reload* the file to see the change.

**Comment by munen** [comment]
I confirm. Tested on iOS. I did have to reload the file to see the loss of markup. Not that it makes things better, it makes it harder to see the bug for a user. 

Good catch!

**Comment by schoettl** [comment]
More information and screenshots in #796

**Comment by saikiransathpadi** [comment]
@munen  It happened to me even without a reload in the chrome browser. I would like to try this out, could you please assign it to me?

**Comment by chasecaleb** [comment]
@saikiransathpadi Thank you so much!!! You'll make my day if you fix this. I'm not a maintainer so I can't assign this to you, but you're welcome to get started anyways and make a PR whenever you get it figured out.

**Comment by munen** [comment]
@saikiransathpadi You're very welcome, thank you for stepping up :pray: 

I'll be happy to help with testing, too!

**Comment by saikiransathpadi** [comment]
@munen  Hi, https://github.com/200ok-ch/organice/pull/928 I have made the respective changes. Hope this resolves the issue.

**Comment by munen** [comment]
Closed by https://github.com/200ok-ch/organice/pull/928

cc @chasecaleb
