### ISSUE TITLE
Support for GPG-encrypted org files

### ISSUE THREAD

**Issue by fabioberger** [200ok-ch/organice#385]
**Is your feature request related to a problem? Please describe.**

It would be great if Organice supported decryption/encryption of EasyPG-encrypted org files in the same [way as Emacs](https://orgmode.org/worg/org-tutorials/encrypting-files.html).

**Additional context**

I might have the time to contribute this improvement to Organice if it's low priority for the maintainers.

**Comment by munen** [comment]
Hi @fabioberger 

Thank you for looking into organice.

I'm using this feature myself for rare cases, but it's not on our dev roadmap at this point. However, if you want it to be in organice, I'm in favor and would happily give you support when building the feature, of course!

**Comment by fabioberger** [comment]
Thanks for the reply @munen. In that case, I'll add this to my side projects wish list. Will reach back out when I find the time to work on it.

**Comment by munen** [comment]
:+1:

**Comment by munen** [comment]
Closing, because it's been two years since the last ping. When yo get back to it, please feel free to re-open. I'm looking forward to the PR and will happily help out with testing and code-review :pray:
