### ISSUE TITLE
Allow template-variables in a header-path in a capture-template

### ISSUE THREAD

**Issue by jayesh-bhoot** [200ok-ch/organice#386]
**Is your feature request related to a problem? Please describe.**

I file my thoughts/observations/todos/notes of a day under a main headline titled as the timestamp of that day. For eg:

``` org
* [2020-07-08 Wed]
** After breathing for a couple of hours in a mask, I understand why Superman chose a pair of glasses and a curly lock of hair to hide his identity. :thoughts:
** A Time to Kill :watch:
** being bald: you immediately know when a fly has landed on your hair :thoughts:

* [2020-07-07 Tue]
** TODO Set up quick screenshotting in Zoom and Windows 7 :wife:
** Corona FAQ: :thoughts:
Q: Should I wear a mask while driving?
A: If you usually speed through red lights, then don't bother.
```
So the headline under which I want to use capture-templates are dynamic. 

**Describe the solution you'd like**
Allow the use of template-variables in the header-path in a capture-template. So I could simply use `%u` as my header-path.

**Describe alternatives you've considered**
Another way could be to allow adding a subheadline under (instead of below) a zoomed-in/narrowed-in headline.

**Comment by munen** [comment]
Hi @jayesh-bhoot 

Thank you for checking out organice! Would you be interested to building this feature?

**Comment by jayesh-bhoot** [comment]
So I gave this a shot. I think I have figured it out. [video demonstration on imgur](https://i.imgur.com/DkuqHhn.mp4)

I have kept the changes to a minimum -

1. Parse the template-variables in a header with `substituteTemplateVariables()` in `headerWithPath()`, so that the template-variables are processed wherever headerPath is touched (I think so atleast).
2. Parse the template variables in a header with `substituteTemplateVariables()` to display the header-path correctly in the `capture-modal`.

While all the existing tests pass, I think I should add a few tests to cover this change as well.

**Comment by munen** [comment]
From the video, it looks great! :tada: 

Adding tests for the specific new feature is much appreciated!

**Comment by jayesh-bhoot** [comment]
See if the PR #387 works for the project.

**Comment by munen** [comment]
@jayesh-bhoot Perfect implementation! 

I've added a [tiny bit of documentation](https://github.com/200ok-ch/organice/pull/387/commits/fa029f7023c255d7934594e6a44c5efaf88dda45) and the [contribution attribution](https://github.com/200ok-ch/organice/pull/387/commits/8b7d7e8f27121fc22c1602026a6f0547c41e0e2f).

Happy to merge it in! Welcome to the organice contributor list :pray: :bow:
