### ISSUE TITLE
Default to the system's monospace font-family instead of Courier fonts

### ISSUE THREAD

**Issue by jayesh-bhoot** [200ok-ch/organice#388]
**Is your feature request related to a problem? Please describe.**
The Courier font looks spartan at best. We can do better with a meagre effort. We could simply use the system's (Android or iOS) default `monospace` font. 

**Describe the solution you'd like**
We replace the instances of `font-family: Courier;` with a series of families, starting with the system's own - `font-family: monospace, xyz, Courier;`. I played around with this, and it's doable, with pleasing results (at least to my eye). But I will commit to the change fully only if you approve of the idea.

**Describe alternatives you've considered**
Alternatively, we could bundle a nice looking font along with the app. This seems excessive though.

**Comment by munen** [comment]
Font choice, that's an interesting topic(;

I assume that as soon as we change it, it'll be a regression for someone. If we make a change on that, we probably have to make it configurable in the settings. Would you be interested to work on that?

NB: Bundling a font could also be nice. Personally, I'm using [FiraCode](https://github.com/tonsky/FiraCode) in my [Emacs config](https://github.com/munen/emacs.d/#linux).

**Comment by jayesh-bhoot** [comment]
Alright. I am still making up my mind about org mode. In case I stick to it, I will take this task.

**Comment by munen** [comment]
@jayesh-bhoot That's fine with me, take your time.

In the meantime, I'm closing this issue as per https://github.com/200ok-ch/organice/blob/master/CONTRIBUTING.org#how-we-work-with-issues. If you choose to work on it at some point later, please just re-open the issue.
