### ISSUE TITLE
Full offline support

### ISSUE THREAD

**Issue by adamfaryna** [200ok-ch/organice#399]
**Is your feature request related to a problem? Please describe.**
This feature is meant to solve at least two problems:
1) Mobile apps are killed easily by OS, so we can't keep them forever alive to have offline access to org files.
2) If we use Chrome, we can have only a single instance of Organice showing a single org file. Switching between files will cause re-download and BSOD (black screen of death - which is white BTW) "internet not available".

These two issues make Organice quite useless and unreliable in offline mode.

**Describe the solution you'd like**
The solution would be to use local storage to store every visited org file, so even if we would be in offline mode we could have all features available - other than sync of course.

At any time when the network will be available again, we would sync current state with remote one, as simple as that.

This solution will not cause any additional problems because the sync mechanism is already implemented, so we can piggyback on it.

**Describe alternatives you've considered**
1) Using offline pages in Opera on mobile - it doesn't work with web apps, it caches only CSS and HTML so it works only for plain static pages.
2) Opt-out Organice from Android battery optimization - the app stays alive but we can access only a single file at a time. If we switch files or kill it by an incident we will get BSOD.
3) Tried Firefox, Chrome, Opera on Android - all of them refresh the content of the page when we reopen the app after killing.

**Additional context**
none

**Comment by munen** [comment]
Hi @adamfaryna

Thank you for opening an issue for organice and becoming a user! Also thank you for collaborating in the community chat before opening an issue.

Would you be interested in working on this issue?

**Comment by adamfaryna** [comment]
Thank you @munen

It will be hard for me to find a time these days. Maybe somebody else will be able to take up a glove, before I will have a moment. You can close it if you feel like it.

**Comment by munen** [comment]
Of course this would be a great feature, but it's a major refactor. It's not that I haven't thought of it, yet. But: It's not as simple as your laying it out and there's other stuff to do first in my opinion.

For the time being, closing this issue as per https://github.com/200ok-ch/organice/blob/master/CONTRIBUTING.org#how-we-work-with-issues. If you choose to work on it at some point later, please re-open the issue.

**Comment by munen** [comment]
@farynaio FYI, full offline support has been implemented in the beginning of the year. I just came across this old issue and wanted to let you know.

Here's some documentation on it: https://organice.200ok.ch/documentation.html#offline_support

**Comment by farynaio** [comment]
@munen that's great news, thanks for the update.
