### ISSUE TITLE
Table like edit menu for plain list edition

### ISSUE THREAD

**Issue by adamfaryna** [200ok-ch/organice#400]
**Is your feature request related to a problem? Please describe.**
Working with plain lists is cumbersome, especially when we have a sub-lists. Restoring indention for every item is a pain.

**Describe the solution you'd like**
I wish to have a way to add new items to the list and rearrange them without doing it manually.

The solution I propose is to have something similar we already have for tables. A menu that will show up when we click on the list to add items and reorder them.

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by munen** [comment]
Hi @adamfaryna 

Thank you for opening an issue for organice and becoming a user!

Would you be interested in working on this issue?

**Comment by adamfaryna** [comment]
Thank you @munen 

It will be hard for me to find a time these days. Maybe somebody else will be able to take up a glove, before I will have a moment.

**Comment by munen** [comment]
Thank you for your honesty.

Your requested feature is currently out of scope for the maintainers. Here's a duplicate issue outlining the rationale: https://github.com/200ok-ch/organice/issues/295

Closing this issue as per https://github.com/200ok-ch/organice/blob/master/CONTRIBUTING.org#how-we-work-with-issues. If you choose to work on it at some point later, please re-open the issue.
