### ISSUE TITLE
Headlines with active timestamps should appear in Agenda

### ISSUE THREAD

**Issue by munen** [200ok-ch/organice#42]
Currently, only headlines with SCHEDULED and DEADLINE attributes show in the agenda. However, any headline with an active timestamp should appear exactly on that date (https://orgmode.org/manual/Timestamps.html).

**Comment by mantlepro** [comment]
Agree that active timestamps should appear in agenda by default. In Org, `SCHEDULED` means _I am planning to start working on this task on a particular date,_ whereas appointments / meetings only need a simple \<active\> timestamp to be included in the agenda view.

From https://orgmode.org/manual/Deadlines-and-scheduling.html:

> Important: Scheduling an item in Org mode should not be understood
> in the same way that we understand scheduling a meeting. Setting a
> date for a meeting is just a simple appointment, you should mark
> this entry with a simple plain timestamp, to get this item shown on
> the date where it applies. This is a frequent misunderstanding by
> Org users. In Org mode, scheduling means setting a date when you
> want to start working on an action item.
