### ISSUE TITLE
External links in Organice settings open the page in the same window

### ISSUE THREAD

**Issue by schoettl** [200ok-ch/organice#435]
**Describe the bug**
External links to help pages in Organice settings are not `target=_blank`. At least when the app is opened in the browser, clicking them will open the page in the same browser window.

In contrast links in the open document are, e.g.
```
<a href="nnnnn" target="_blank" rel="noopener noreferrer">nnnnn</a>
```

**Expected behavior**
All links to external resources should behave the same way.

I can fix this. But I first want to see if someone is expert on links :)

`target="_blank" rel="noopener noreferrer"` makes sense also for all http(s) links to external pages, right? Is there a better way in React to code links than to just write all this `<a href...>`? I think we have a `<Link>` element or so... I will look how it's done in the document...

**Comment by munen** [comment]
:+1: on adding the suggested attributes to the anchor element for external links!

> target="_blank" rel="noopener noreferrer" makes sense also for all http(s) links to external pages, right? 

Yes.

> Is there a better way in React to code links than to just write all this <a href...>? I think we have a <Link> element or so... 

The `<Link>` component is primarily relevant for using routing (to allow users to navigate around in the same application).

For external links, `<a>` tags are the way to go.
