### ISSUE TITLE
(One) test fails randomly on some machines

### ISSUE THREAD

**Issue by munen** [200ok-ch/organice#442]
One test failed on CI in one run, but then ran on a rerun of the build on the same commit:

![image](https://user-images.githubusercontent.com/505721/91640770-3eb31c00-ea20-11ea-8d0e-6cbac8105f1c.png)

This is the test in question:

![image](https://user-images.githubusercontent.com/505721/91640790-60140800-ea20-11ea-8bf8-c6bd0ac26feb.png)

If that was the only time it was failing, there wouldn't be an issue. But @necto [mentioned](https://github.com/200ok-ch/organice/pull/440#issuecomment-683278079) that he is seeing this behavior of the test being flaky on his machine, too.

Iirc this is the first time that this test fails on CI. And I haven't seen this or other tests sporadicly fail on my machine, so far. This and that it becomes green for @necto when he's debugging makes it sound like a timing issue to me.

**Comment by munen** [comment]
@necto The test does open the agenda, which when run in the browser, does have an animation, at least. However, if that test fails for you sometimes, then other tests opening the agenda or similar modals (like search or the todo list) should also fail. Is that the case? Or is this the only test in the 'sometimes failing/flaky' category?

**Comment by necto** [comment]
This is the only test that fails sometimes. Other agenda- and search-related tests never failed randomly so far.

P.S. how do run this test in a browser to watch the animation?

**Comment by necto** [comment]
I tried decreasing stiffness for animations from `300` down to `3` which had a visible slowdown effect when trying out it manually. It did not affect the tests - all pass.

Although, I didn't find the animation related to this particular test (i.e. something around the click handler for the overdue display mode https://github.com/200ok-ch/organice/blob/master/src/components/OrgFile/components/AgendaModal/index.js#L76). Is it animated at all?

**Comment by munen** [comment]
> This is the only test that fails sometimes. Other agenda- and search-related tests never failed randomly so far.

:+1: 

Ok, so the challenge is to find out what is different in that specific test. 

> P.S. how do run this test in a browser to watch the animation?

That's not a core feature of the test framework we use ([jest](https://jestjs.io/)). The reason is that jest is zero-configuaration and standalone by default.

However, it seems there are options to add the ability to run the tests in the browser. For example with https://github.com/smooth-code/jest-puppeteer. I have no prior experience with this package, though. Maybe there are other and better options. I only quickly looked into it.

**Comment by munen** [comment]
> I tried decreasing stiffness for animations from 300 down to 3 which had a visible slowdown effect when trying out it manually. It did not affect the tests - all pass.

Good theory, though! :+1: 

> Although, I didn't find the animation related to this particular test

I retract the theory that it could have been about the animation of the agenda. It can't be, because the failure on CI was in the last line (https://github.com/200ok-ch/organice/blob/master/src/components/OrgFile/OrgFile.integration.test.js#L433) whereas there's already a check for content of the modal some lines before that (https://github.com/200ok-ch/organice/blob/master/src/components/OrgFile/OrgFile.integration.test.js#L430).

The expectation in line 430 is not accidentally green. When the modal isn't opened, then the test will fail there:

![image](https://user-images.githubusercontent.com/505721/91643224-8e4e1380-ea31-11ea-82cd-2c5ed43eaabb.png)

So it must be something different.

**Comment by munen** [comment]
NB: The switch of the `absolute` to `relative` time itself is not animated. I apologize for taking you down that rabbit hole.

**Comment by munen** [comment]
This hasn't failed on CI in some years and I also don't see randomly failing tests on my machine. Since I cannot act upon the issue, I'm closing it.

If anyone finds this issue in the future and has the same problem as described above, please feel free to re-open. Then let's discuss the issue again and find a new solution. Until then, tests are :heavy_check_mark:
