### ISSUE TITLE
Planning items with "DONE" state in Agenda

### ISSUE THREAD

**Issue by munen** [200ok-ch/organice#445]
We just introduced a major regression to the agenda in https://github.com/200ok-ch/organice/pull/423

TODO Items with "DONE" state will show up in the Agenda, now. That means in practice that there's hundreds of items in "Today". Most of them not actionable.

The bug wasn't there on the PR state where I  reviewed it:

![image](https://user-images.githubusercontent.com/505721/91658766-6f9c5b00-eacb-11ea-84b0-af4cce654b21.png)

However, on current `master`, it's there:

![image](https://user-images.githubusercontent.com/505721/91658816-dd488700-eacb-11ea-99f5-682f94c45cd6.png)

I assume it's this commit: https://github.com/200ok-ch/organice/commit/d22f7d0a3f15055e429f058a71ad78284c1671ba

@schoettl Let me know if you can work on that. Otherwise I'll make it a priority for me to fix this.

In any case, a good measure would be to have a test case guarding against this behaviour.

**Comment by schoettl** [comment]
Oh, I'm sorry. I'll look into this.

**Comment by munen** [comment]
> Oh, I'm sorry. 

No worries, that can always happen(;

I went over your additional commits and they didn't look suspicious. Also the tests were green. I was lucky, because I wanted to add a note to a header on my Agenda and while cooking some Spaghetti^^

> I'll look into this.

🙏

**Comment by schoettl** [comment]
`git bisect` tells me it is 36d736692e8910bff0edf17e666b1d6a55a95819

But I don't understand it.. all `!!` I removed the where in a boolean context.

Oh, I got it. I used word completion without looking good enough. Ending up in
```patch
+            todoKeyword && isTodoKeywordCompleted(todoKeywordSets, todoKeywordSets);
-            todoKeyword && isTodoKeywordCompleted(todoKeywordSets, todoKeyword);

**Comment by munen** [comment]
*hihi*

Yes, we could have caught that one in a review.

Looks like the culprit^^

But like I said, it happens(;
