### ISSUE TITLE
Respect file EOL (End of Line)

### ISSUE THREAD

**Issue by whudwl** [200ok-ch/organice#464]
**Describe the bug**
Organice always use Unix style EOL no matter what EOL the file uses. 

**To Reproduce**
1. Open an org file with DOS style EOL
2. Add a new header, save the file. 
3. View the file from a PC. 
4. You'll see that lines added using organice have Unix Style EOL while existing lines have DOS Style EOL. 

**Expected behavior**
organice uses whatever EOL the file uses.

**Comment by schoettl** [comment]
Hi @whudwl, we already had this report in #291.

Would you like to work on this?

**Comment by munen** [comment]
Closed with the same argumentation as in https://github.com/200ok-ch/organice/issues/291.
