### ISSUE TITLE
Number of todos in header not updated when refiling tasks

### ISSUE THREAD

**Issue by fkohrt** [200ok-ch/organice#473]
**Describe the bug**

If I have a bunch of tasks and refile one of them, the number of todos in the header does not get updated.

**To Reproduce**

1. Consider a setup like the following:

![1](https://user-images.githubusercontent.com/12914806/93103033-69ea6c00-f6ac-11ea-8f8f-a40a77127106.png)

2. Refiling _Task A_ to another header does not update the number of tasks in the header _My todos_:

![2](https://user-images.githubusercontent.com/12914806/93103147-90a8a280-f6ac-11ea-8953-68f654cfff6c.png)

**Expected behavior**

I expect the header _My todos_ change to "My todos [0/1]".

**Desktop (please complete the following information):**

 - OS: Fedora 31
 - Browser Mozilla Firefox 79.0

**Comment by fkohrt** [comment]
Oh, I don't use Org mode, I just inferred from similar behavior (updating a task from `TODO` to `DONE`) that this may not be intended. I'll close this then, although it might be a nice feature I guess.

**Comment by munen** [comment]
:+1: 

And good to see that organice has users that are not coming from Org mode themselves(; If you care to share, I'd be curious to hear how you came to organice and what youre use-case is.

**Comment by fkohrt** [comment]
Well I very much believe in the Unix plain text philosophy, and I'm attracted by standardizations of such, as they exists with Todo.txt or Org mode (or, for different use cases, with hledger, beancount or mermaid). There are very nice and shiny task managers out there, but they mostly either

- don't do plain text storage nicely or
- don't have both a [free](https://www.gnu.org/philosophy/free-sw.html) command line interface and a (self-hostable) web interface.

So while investigating Org mode, I came across [org-web](https://github.com/DanielDe/org-web), which however only supports proprietary cloud providers. Could be because of some Hacker News entry that I found organice. I started to use it together with some GTD setup (with `Flow` only being a textual description of the GTD setup):

![gtd](https://user-images.githubusercontent.com/12914806/93126943-5ac7e600-f6cd-11ea-80b5-f27450347c02.png)

But I am not too happy with my handling of projects, maybe writing a project name in uppercase to each task might work better than keeping a list of them under a separate header... I will see about that.

**Comment by munen** [comment]
Thank you very much for your explanation! I can see that we're very much in line in these matters(;

Thank you also for sharing your top level GTD setup, I appreciate it. Just for comparison, here's mine:

![image](https://user-images.githubusercontent.com/505721/93127739-bc3c8480-f6ce-11ea-8d4b-7a059a688a3e.png)

**Comment by munen** [comment]
FYI, since you mentioned hledger: We're also ledger users, but only use it for part of the bookkeeping. We have written an event sourced system which enables us to think only in business events and generate artifacts like invoices, salaries, tax payments and such. For the bookkeeping artifacts (like the annual financial statement), it uses leger. The project is FOSS and on GH: https://github.com/200ok-ch/easy

**Comment by fkohrt** [comment]
> We have written an event sourced system which enables us to think only in business events and generate artifacts like invoices, salaries, tax payments and such.

Very interesting! Reminds me of a different project I encountered ([Markdown2AssetStorm](https://github.com/AssetStorm/Markdown2AssetStorm), also presented in c't magazine 26/2019, p. 128). Thanks for sharing!

> Just for comparison, here's mine

For the sake of completeness :)

![flow](https://user-images.githubusercontent.com/12914806/93128553-f4909280-f6cf-11ea-8006-9ac82376b215.png)

![next-actions](https://user-images.githubusercontent.com/12914806/93134021-6b318e00-f6d8-11ea-8af7-7e53fb725a4e.png)

With some more physical `@location`s below...

**Comment by fkohrt** [comment]
Re plain text languages, I've been hacking together a Markdown-to-PDF converter that fulfils some special demands (like XMP metadata integration, microtypography [through `microtype`] or “smart typography” [as in turning `"quote"` to `“quote”`]) but does not require LaTeX knowledge for end users (especially no tedious installation procedure).

App: https://fkohrt.shinyapps.io/markdown-typesetter/ \
Code: https://gitlab.com/fkohrt/markdown-typesetter

**Comment by munen** [comment]
> RE plain text languages, I've been hacking together a Markdown-to-PDF converter

That looks quite interesting, thank you for sharing!

It's quite rare to see a R application as a web application in the wild, so it's even more special^^

NB: We use Org mode for pretty much everything from project planning (with estimations, time tracking and time reporting), slides, books, accounting, meeting minutes and so on. It's probably one of my most important tools in the toolbox(;

**Comment by munen** [comment]
Thank you also for sharing your `Flow` headline. It's a nice summary of GTD!

The equivalent in my file would be this: https://gist.github.com/munen/3c6c695be740a37d71aa1ebb4acb34b5

If you're looking to chat about workflows in Org mode (like GTD) at some point, you're very welcome to join  #organice on IRC Freenode, or #organice:matrix.org on Matrix, or shoot me an email(;

**Comment by fkohrt** [comment]
> It's quite rare to see a R application as a web application in the wild, so it's even more special^^

I never got accustomed to R very much, but around it a crazy ecosystem for building reproducible, computable documents has evolved (including [posters](https://brentthorne.github.io/posterdown_html_showcase/), [presentations](https://academic-demo.netlify.app/slides/example/), [dashboards](https://gallery.shinyapps.io/cran-gauge/), [blogs](https://xmin.yihui.org/), [websites](https://academic-demo.netlify.app/), [résumés](https://pagedown.rbind.io/html-resume), [books](https://bookdown.org/yihui/bookdown/) and [interactive tutorials](https://learnr-examples.shinyapps.io/ex-data-summarise/)).

> The equivalent in my file would be this: https://gist.github.com/munen/3c6c695be740a37d71aa1ebb4acb34b5

:+1: cool, thanks for sharing

> If you're looking to chat about workflows in Org mode

Thank you! I feel like I will eventually take a deep dive into Org mode and its magic, so I'll come back to that then :)

**Comment by munen** [comment]
> I never got accustomed to R very much, but around it a crazy ecosystem for building reproducible, computable documents has evolved (including posters, presentations, dashboards, blogs, websites, résumés, books and interactive tutorials).

Those are quite interesting resources. I haven't used R much myself, but my co-founder for 200ok.ch used to use it a lot. I'll make sure to share them with him :+1: 

> Thank you! I feel like I will eventually take a deep dive into Org mode and its magic, so I'll come back to that then :)

Looking forward to seeing you then^^
