### ISSUE TITLE
Autofocus on search field when refiling not working on Firefox

### ISSUE THREAD

**Issue by fkohrt** [200ok-ch/organice#474]
**Describe the bug**

When refiling an item, the Refile menu opens and I can select another item from a list. On Firefox, however, I can't immediately start typing to narrow down the list, but first have to click on the input field.

**Expected behavior**

The input field of the Refile menu should be on focus automatically.

**Desktop (please complete the following information):**

 - OS: Fedora 31
 - Browser: Mozilla Firefox 79.0

**Comment by munen** [comment]
Hi @fkohrt 

Thank you for getting involved in organice development :+1: 

I cannot reproduce this. It works for me on FF 80 on Debian bullseye/sid.

![refile_on_linux](https://user-images.githubusercontent.com/505721/93122966-aaa3ae80-f6c7-11ea-814a-ebbd627508ae.gif)

**Comment by fkohrt** [comment]
You are correct, my Docker Build was outdated (still from [2020-07-28 Tue]), and after doing a new pull it worked. It might help to show some version numbers in the footer to make it easy to manually check for newer versions.

**Comment by munen** [comment]
> It might help to show some version numbers in the footer to make it easy to manually check for newer versions.

We don't have version numbres, but we have something more semantic: A changelog. The changelog states that the feature was introduced after you pulled your Docker image:

![image](https://user-images.githubusercontent.com/505721/93125373-54d10580-f6cb-11ea-9171-c853b163347b.png)

organice also displays a :gift: icon whenever there's user visible changes on the top right and will lead you to the changelog

**Comment by fkohrt** [comment]
Yeah, I actually stumbled across it just now :)

It's nice how you can leverage your own user interface for things like showing the changelog.

**Comment by munen** [comment]
> Yeah, I actually stumbled across it just now :)

:+1: 

> It's nice how you can leverage your own user interface for things like showing the changelog.

Thank you :pray:
