### ISSUE TITLE
Dark mode?

### ISSUE THREAD

**Issue by Naheel-Azawy** [200ok-ch/organice#487]
**Is your feature request related to a problem? Please describe.**
Well, yes you can call it a problem. The light theme is a serious deal breaker for me. It hurts my eyes in my dark room.

**Describe the solution you'd like**
An option to make the theme dark. Or perhaps add multiple themes.

**Describe alternatives you've considered**
Maybe tell be which css I should I start from? I'm a bit in rush for now to dig.

**Additional context**
Nothing much, I just really like this project. Thanks to all who worked on it!

**Comment by munen** [comment]
Hi @Naheel-Azawy 

Thank you for checking out organice 🙏 

You are in luck! organice uses the popular [Solarized color scheme](https://ethanschoonover.com/solarized/). One of the properties of Solarized is that it implements light and dark modes using the same colors, so adding a Solarized dark mode should be pretty easy.

The current color scheme is mostly implemented in the CSS files in the [`src` directory](https://github.com/200ok-ch/organice/tree/master/src). The original PR to introduce it is #12.

Would you be interested in working on this?

**Comment by Naheel-Azawy** [comment]
That sounds cool.

> Would you be interested in working on this?

Am I interested in that? Of course yes. But can I? Unfortunately, probably not..

So I guess let's keep this open till I or anyone else get some time to work on it

**Comment by munen** [comment]
> Am I interested in that? Of course yes. But can I? Unfortunately, probably not..

I understand. In this case, we've got documentation on your options: https://organice.200ok.ch/documentation.html#how_we_work_with_issues

**Comment by Naheel-Azawy** [comment]
Mmm, ok. Maybe some day I get back to this. But thank you anyway. Keep up the good work!

**Comment by munen** [comment]
:+1:

**Comment by munen** [comment]
Dark mode has been implemented by https://github.com/200ok-ch/organice/pull/527

**Comment by Naheel-Azawy** [comment]
Super cool! Even though I'm not a big fan of the solarized bluish dark but that is great progress! Thank you @munen and @tarnung

**Comment by munen** [comment]
@Naheel-Azawy Solarized is quite definitively one of the most popular choices out there. Having said that, if you're particular about your preferred color scheme, there's good news: With the new implementation, it's actually quite easy to add additional color schemes. You're very welcome to contribute one that is to your liking.

**Comment by tarnung** [comment]
@Naheel-Azawy I experimented with some well known themes by copy-pasting their colors into our template. Some of them need more work. But if there's something more to your liking, let me know and I'll make a pull request so everyone can weigh in.

one dark
![onedark](https://user-images.githubusercontent.com/35081013/97088064-c38c7180-162e-11eb-8a1e-49352383af46.png)

gruvbox dark
![gruvboxdark](https://user-images.githubusercontent.com/35081013/97088069-c9825280-162e-11eb-913c-60def938f091.png)

smyck
![smyck](https://user-images.githubusercontent.com/35081013/97088074-cedf9d00-162e-11eb-96ef-49dc08702c53.png)

dark+ (VS Code default theme - rough epproximation)
![darkplus](https://user-images.githubusercontent.com/35081013/97088078-d30bba80-162e-11eb-866b-95c5d3c3eeac.png)

**Comment by Naheel-Azawy** [comment]
That is wonderful work thank you @tarnung!
To me, I like the background to be purely black, so "smyck" is the coolest here in my opinion. The rest of the colors are nice as well.
One more thing, regarding the glow (light shadow), I think it would look better if you set it to black as well. This way it would look more like shadow even in dark themes.

**Comment by munen** [comment]
@tarnung Amazing work, they all look gorgeous! :pray:
