### ISSUE TITLE
When repeating a task, an active date timestamp is logged instead of an inctive datetime timestamp

### ISSUE THREAD

**Issue by munen** [200ok-ch/organice#512]
Showing the different behavior between Emacs and organice toggling the same headline:

![image](https://user-images.githubusercontent.com/505721/96283536-a297a100-0fdc-11eb-9d9b-fdf764638600.png)

The wrong active timestamp is also not parsed (which is not too bad as it should not be there in the first place).

![image](https://user-images.githubusercontent.com/505721/96283966-3d907b00-0fdd-11eb-93e1-7a0b758d8c60.png)

**Comment by schoettl** [comment]
> The wrong active timestamp is also not parsed (which is not too bad as it should not be there in the first place).

Active or inactive: there should be an easy way to parse it and display it clickable because it already works for clock in/out (for logbook) and add note (if it's logged in log notes).

**Comment by munen** [comment]
> Active or inactive: there should be an easy way to parse it and display it clickable because it already works for clock in/out (for logbook) and add note (if it's logged in log notes).

Agreed. More importantly, though, this bug leads to buggy behavior for the agenda:

![image](https://user-images.githubusercontent.com/505721/96285156-da074d00-0fde-11eb-86bc-0a0455e7b720.png)

**Comment by schoettl** [comment]
Definitely. Good catch by @tarnung.

**Comment by munen** [comment]
Closed by #569.
