### ISSUE TITLE
Documentation for developers in Windows environment

### ISSUE THREAD

**Issue by schoettl** [200ok-ch/organice#513]
Some unit tests with strings like
```
`multi
line`
```
fail because Git on Windows check out CRLF, not just LF. Another reason might be that there IDE/editor saves CRLF.

_Originally posted by @tarnung @munen @schoettl in https://github.com/200ok-ch/organice/pull/505#issuecomment-710776100_

Here are some ideas to fix this.

A good place for documentation would be https://github.com/200ok-ch/organice#development

**Comment by munen** [comment]
Best would be if a solution can be found and documented by a Windows developer.

**Comment by schoettl** [comment]
Copied from other #505:

> If git config core.autocrlf false fixes the issues, that would definitively be preferable to changing all occurences of \n [to EOL from 'os'] (;

> ... plus the editor/IDE must save LF, not CRLF.

> Maybe that can be addressed with * text=auto (https://mirrors.edge.kernel.org/pub/software/scm/git/docs/gitattributes.html#_end_of_line_conversion).

**Comment by munen** [comment]
Closed by https://github.com/200ok-ch/organice/pull/563
