### ISSUE TITLE
Task list not scrollable on Android

### ISSUE THREAD

**Issue by tarnung** [200ok-ch/organice#514]
It seems there was a similar issue with Agenda as seen in #65 and #67.

While I can scroll the content of the task list in my desktop browser, I can't on my Android phone. I can see a scroll bar in the task list body, but I doesn't react.

**Comment by munen** [comment]
Can someone with an Android tackle this, please?

I confirm that there were the issues #65 and #67, but I have fixed those on Desktop and iOS. I can't for Android, because I do not own such a device.

**Comment by munen** [comment]
Closed by https://github.com/200ok-ch/organice/pull/561
