### ISSUE TITLE
the  layout is not Displayed

### ISSUE THREAD

**Issue by 809825706** [200ok-ch/organice#541]
**Describe the bug**
some layout is not Displayed on edge on win10 20H2

**To Reproduce**

**Expected behavior**
let the layout Displayed 

**Screenshots**
![image](https://user-images.githubusercontent.com/46601791/97252929-1f7d1300-1846-11eb-9f4d-25eb85f49cb4.png)

**Desktop (please complete the following information):**
 - OS: [windows10 20H2]
 - Browser [Microsoft edge 86.0.622.51]

**Additional context**
the button works, but I can't figure out what it is.

**Comment by 809825706** [comment]
network problem

**Comment by munen** [comment]
:+1:
