### ISSUE TITLE
Restrict search results to a maximum number of results

### ISSUE THREAD

**Issue by munen** [200ok-ch/organice#589]
@tarnung  is currently adding multi-file support. When adding a couple of big (but real) Org files to search, then my maxed out max Lenovo notebook is starting to become slow, yet noisy. The same happens for refile, naturally, which makes both features a little less usable. For me, it still works with some waiting, but my notebook is quite heavy machinery^^

I propose for search to limit the returned results to something reasonable (like 200). Reading through tens of thousands of headers in search is probably nothing that anybody would do. And if someone wants more, we could add it as a setting.

@schoettl Since you originally implemented search, I don't want to do such a change without your feedback. Do you have thoughts on that matter?

NB: The reason for organice to become slow in this scenario isn't search per se, of course, but rendering the many results.

Original discussion:

- https://github.com/200ok-ch/organice/pull/570#issuecomment-734946712
- https://github.com/200ok-ch/organice/pull/570#issuecomment-735218974

**Comment by tarnung** [comment]
I've never looked into this, but there might be list-components that only render the currently visible headers.
It would still be ok to end search after a certain amount of matches of course, but it might also have benefits when regularly displaying huge files - especially if we would add global visibility cycling or another feature that leads to many expanded headers.

**Comment by munen** [comment]
I'm also not familiar with this, but if there's a feature for that in React, and we could employ that globally, then this would certainly be a very reasonable alternative!

**Comment by munen** [comment]
Looks like this is a popular approach: https://github.com/bvaughn/react-window

Not saying we need to employ it, just dropping it here as an option.

**Comment by tarnung** [comment]
I implemented the 200 results limit on develop. It's a single commit, so we can revert in easily if we decide otherwise.

**Comment by munen** [comment]
Sweet! I didn't benchmark, but on Staging it feels a whole lot snappier on the same machine with the same Org files :+1:

**Comment by munen** [comment]
This is already deployed.
