### ISSUE TITLE
As a visitor on the LP, I want the "privacy policy" to be sticky to the bottom of the page

### ISSUE THREAD

**Issue by munen** [200ok-ch/organice#61]
On scrolling, the link doesn't stick to the bottom, but overlaps with the buttons on the page.

**Comment by dotcs** [comment]
I have worked on the layout to fix this issue. Please see my PR #140.

**Comment by munen** [comment]
Thank you very much :pray: :bowing_man: 

I have updated the changelog with your contribution and attribution: https://github.com/200ok-ch/organice/commit/636d341bbdffe3b25f7d6a0551b4c92940829b05
