### ISSUE TITLE
Possible to create a note like with file+olp+datetree?

### ISSUE THREAD

**Issue by poulpoulsen** [200ok-ch/organice#621]
Hello,
I want create notes in a datetree like in Emacs with file+olp+datetree.

Is it possible?
Or are you planning to implement it?

Regards
Poul

**Comment by schoettl** [comment]
Hi Poul, can you send a link to the documentation of the emacs feature you're referring to?

**Comment by poulpoulsen** [comment]
Here is the link:
https://orgmode.org/manual/Template-elements.html#Template-elements

Hope it helps 😃

**Comment by schoettl** [comment]
Wow, that's a pretty specific feature, I just learned about it.

Just for my interest, how do you use the date tree, what is your specific use case?

You're welcome to contribute this feature to Organice but I think it's not trivial. That would be, adding something like a combo box to the capture template form for selecting the "target" strategy. The other developers probably have their own TODO list for Organice :)

**Comment by poulpoulsen** [comment]
Hello,
My usecase is to create a journal of notes. Like in Emacs. Every new note 
is created under the header of current day or week, inside a header of 
current month and header year. This is a org-mode feature since some 
years. Nothing really special.
Organice has to use orc-capture elements, then this is one option to 
create an item.
Do I understand, that this feature is not planned in the next steps?

Regards
Poul


Von: Jakob Schöttl <notifications@github.com>
An: 200ok-ch/organice <organice@noreply.github.com>
Kopie: poulpoulsen <sammelpost@holnishaus.de>, Author 
<author@noreply.github.com>
Empfangen: 12.02.2021 23:01:58
Betreff: Re: [200ok-ch/organice] Possible to create a note like with 
file+olp+datetree? (#621)

**Comment by schoettl** [comment]
So the best thing, Organice can currently provide is a flat list of notes with timestamps sorted (desc- or ascending) by insertion date. Maybe these headers can be refiled into the date tree in emacs in an easier way?

> Do I understand, that this feature is not planned in the next steps?

Correct. If you don't plan to work on it and no other contributor speaks up within the next days, we'll close this issue as per https://github.com/200ok-ch/organice/blob/master/CONTRIBUTING.org#how-we-work-with-issues

**Comment by poulpoulsen** [comment]
Ok, Thank you.
because I am not a developer, it is better to close. I will look for 
other ways.

Regards
Poul

Von: Jakob Schöttl <notifications@github.com>
An: 200ok-ch/organice <organice@noreply.github.com>
Kopie: poulpoulsen <sammelpost@holnishaus.de>, Author 
<author@noreply.github.com>
Empfangen: 13.02.2021 09:38:38
Betreff: Re: [200ok-ch/organice] Possible to create a note like with 
file+olp+datetree? (#621)
