### ISSUE TITLE
Header Action Drawer does not hide

### ISSUE THREAD

**Issue by MisterY** [200ok-ch/organice#628]
**Describe the bug**

Clicking the header (title or the blank space) does not hide the action drawer, only the contents.

**To Reproduce**

1. Click the header to expand a collapsed note
  result: the content and the action drawer appear
2. Click the header to collapse the expanded note
  result: The content hides but the action drawer remains

**Expected behavior**

The action drawer should hide along with the content? I'm not sure what the original intention was but I'd like a way to "unselect" the note, hiding the action drawer as a result. It is too distracting when reading.

**Screenshots**

Expanded:

![image](https://user-images.githubusercontent.com/462445/109418795-70567100-79ca-11eb-97ec-62ee282b1d30.png)

Collapsed:

![image](https://user-images.githubusercontent.com/462445/109418956-3174eb00-79cb-11eb-96a7-81986f1885d1.png)

**Desktop (please complete the following information):**
 - OS: ArchLinux
 - Browser: Firefox

**Smartphone (please complete the following information):**
 - Device: Xiaomi Mi 9T
 - OS: Android
 - Browser: Firefox

**Additional context**

Note that I've tried only in Firefox, mobile and desktop.

**Comment by munen** [comment]
This is not a bug, this is intential. If the action bar would hide, then there goes your way of interacting with this header.

If you want to the header action drawer to disappear, see the documentation on how to work with headers:

![image](https://user-images.githubusercontent.com/505721/111283091-06cb9900-863f-11eb-9c93-d80d5b3b1a89.png)

**Comment by MisterY** [comment]
Yes, thanks, that's the line I have added in the first screenshot.

**Comment by steady137** [comment]
I came straight here after going through the sample and noticing the same thing. Tapping "into the title (or empty space) in the headerbar" does not close the action drawer as claimed in the screenshot cited by both @alensiljak and @munen. If it's intentional then perhaps the sample documentation can be updated or the feature could be implemented. I currently see no way to hide the action drawer and would very much like to. Is there something I've missed?

**Comment by steady137** [comment]
Quick clarification: the "headerbar" seems to refer to the top of the app, not the "header" area you want to close. So that works.
![image](https://github.com/200ok-ch/organice/assets/1694355/d582c2cc-4add-4e0f-acb7-2f21a245bf85)

**Comment by schoettl** [comment]
Hi there, yeah the docs are a bit misleading there. I fixed it in #975 (to be merged).
