### ISSUE TITLE
Implement as PWA

### ISSUE THREAD

**Issue by MisterY** [200ok-ch/organice#629]
**Is your feature request related to a problem? Please describe.**

The app is currently only available online. This may not always be the case.

**Describe the solution you'd like**

I would like the app to be able to Install on the device, through the browser, using PWA standards.

**Describe alternatives you've considered**

An alternative is using a native app.

**Additional context**

The app has a lot of potential. I see no reason for it not to have a few more files, to satisfy the PWA criteria, allowing it to be installable on mobile devices. This would allow working completely offline, irrespective of the network conditions and coverage.

**Comment by munen** [comment]
For future reference: organice is a full PWD with offline support. Documentation regarding these issues is here:

-    https://organice.200ok.ch/documentation.html#progressive_web_app
-    https://organice.200ok.ch/documentation.html#offline_support
-    https://organice.200ok.ch/documentation.html#multi_file_support
