### ISSUE TITLE
Add eslint to CI run

### ISSUE THREAD

**Issue by munen** [200ok-ch/organice#64]
Running `yarn start` will run eslint continuously and show ad-hoc warnings. `yarn build` will also run it - and fail if there's linting errors.

Hence, it would be great to include eslint as a check for CI. It's not completely trivial, though, because organice has been bootstrapped with [create-react-app](https://github.com/facebook/create-react-app).

The task will be to find out how to run eslint with the same configuration without ejecting from create-react-app, because we will want to continue to use it's benefits.

**Comment by munen** [comment]
Creating a prod build will do it, too. And it will stop the build if there’s an error. So it only makes sense to add it to CI.

**Comment by TristanCacqueray** [comment]
Using `yarn build` doesn't seem to fail with eslint errors.

**Comment by munen** [comment]
Not right now, it doesn't^^

But if you add a serious error, `yarn start` and `yarn build` will trigger a warning which in turn stops the CI build.

For example this is a CI build that didn't run due to an eslint error: https://circleci.com/gh/200ok-ch/organice/200 

I just reproduced the mistake from this old CI build - this is what it would look like locally:

![image](https://user-images.githubusercontent.com/505721/67623381-d9e9cc80-f824-11e9-9165-0051462603df.png)

As you can see, it actually does run locally whilst on CI it would not build/deploy. The latter is the right strategy imo.

**Comment by aspiers** [comment]
We've done this, right?

**Comment by munen** [comment]
@aspiers Correct^^

Fixed by @aspiers on commit ab74bda.
