### ISSUE TITLE
can

### ISSUE THREAD

**Issue by 809825706** [200ok-ch/organice#650]
Before creating a new issue, please read the "How we work with issues" section in the documentation: https://organice.200ok.ch/documentation.html#how_we_work_with_issues

**Is your feature request related to a problem? Please describe.**
I just want that it can read the local files.

**Describe the solution you'd like**
can I git the project and motify some files to read and edit the local org files?

**Describe alternatives you've considered**
I just want the UI to replace the complex operation in emacs. there are some apps in android and ios but windows.

**Comment by schoettl** [comment]
> I just want that it can read the local files.

A web page (or progressive web app = PWA) cannot access local files. See https://github.com/200ok-ch/organice#synchronization-back-ends for supported storage back-ends.

**Comment by 809825706** [comment]
> > I just want that it can read the local files.
> 
> A web page (or progressive web app = PWA) cannot access local files. See https://github.com/200ok-ch/organice#synchronization-back-ends for supported storage back-ends.

I see. but can I git the project and motif some configure to do this just like the developer.

**Comment by schoettl** [comment]
What does "to git" and "to motif some configure" mean?

You can use setup your own WebDAV server and use that as sync back-end.
You can try e.g. this WebDAV server: https://github.com/hacdias/webdav

**Comment by munen** [comment]
Your issue starts with:

> Before creating a new issue, please read the "How we work with issues" section in the documentation: https://organice.200ok.ch/documentation.html#how_we_work_with_issues

Please read that sentence and followed the link.
