### ISSUE TITLE
Too eager parsing of italic markup

### ISSUE THREAD

**Issue by munen** [200ok-ch/organice#668]
```
*** TODO organice parser error: Foo/Bar/Baz
Foo/Bar/Baz
```

Is shown as:

![image](https://user-images.githubusercontent.com/505721/117539992-57db8600-b00d-11eb-965a-1b6ce9c20b6f.png)

**Comment by schoettl** [comment]
I think that's a known bug and applies for all kind of markup. I think I remember that, once I worked on the regex parser, I decided that it's too hard to fix and postponed it to the future clojure parser :) But maybe a fresh look on the regex parser allows you to fix it.

**Comment by schoettl** [comment]
See also #94 and #198

**Comment by munen** [comment]
I don’t think it’s a duplicate. The other issues are about the parser choking on lines containing multiple inline markup statements. 

This issue is much more simple: `Foo/Bar/Baz` is just text. It shouldn’t be italicized at all^^

**Comment by schoettl** [comment]
Yep, the issues linked above are only related. It's probably the same regex.

Anyway, the problem applies to all kind of markup, e.g. `Foo+Bar+Baz`

**Comment by munen** [comment]
You are correct, it does apply to all kind of inline markup. I've written a test and looked at the Regexp. But I don't understand why it doesn't work as written at the moment(;

**Comment by munen** [comment]
Worse example with only one slash:

“organice supports parsing and preserving the minimum/maximum range timestamps.” becomes:

![C144C10B-A184-45F9-92DB-725D3927B7FE](https://user-images.githubusercontent.com/505721/118475501-a0312d00-b70c-11eb-8cc7-7246ec79acab.png)

**Comment by lechten** [comment]
I did not look at the proper Org syntax, but what if we just required a whitespace before inline markup?

Thus, replace `[*/~=_+]` with `\s[*/~=_+]`?

**Comment by munen** [comment]
@lechten Your proposal fixes some terms like `foo/bar` and `foo/bar/baz`, but it breaks terms like `*bold*`. I tried adding to your proposal with `[^\s][*/~=_+]`, but that's not working as expected. I must make a trivial mistake here^^

**Comment by munen** [comment]
Partial update: The `^` negates the `\s`, of course(; But `[\s^]` and `[\^\s]` also don't work.

**Comment by lechten** [comment]
The `^` does not work inside square brackets (where it is just another character). We might add `(^|\s)` but this adds another group, which seems to ask for lots of subsequent changes...

**Comment by munen** [comment]
*hihi*, we're looking at the same options currently. I'm checking if there's a way for a match group to basically be ignored. But that's probably against the whole idea of match groups.

**Comment by munen** [comment]
There is a way! `((?:\s|^)?[*/~=_+])` looks promising.

**Comment by munen** [comment]
Looked promising and passes all tests, but it breaks `foo/bar/baz`, again-_-

**Comment by munen** [comment]
`((?:^|\s+)[*/~=_+])` is most promising atm, but it fails ` *bold*`.

**Comment by munen** [comment]
I think `((?:^|\s+)[*/~=_+])` would actually be a good solution, however the match group just direct before `(([\s({'"]?)((?:^|\s+)[*/~=_+])` also has a `\s` which interferes...

Welcome to regexp based parsing hell(;

**Comment by lechten** [comment]
I hope that PR #910 fixes this now (one more commit not mentioning this, sorry).

**Comment by munen** [comment]
Closed by the amazing work of @lechten in #910 :fireworks: :confetti_ball:
