### ISSUE TITLE
When updating a reapeated task with timestamp, do not update the time portion

### ISSUE THREAD

**Issue by munen** [200ok-ch/organice#683]
When taking this headline:

```
* TODO Test task
  SCHEDULED: <2021-05-17 Mon 08:00 .+1d>
```

and marking it 'DONE' in Emacs on this day at 10:38am, the headline changes to:

```
* TODO Test task
  SCHEDULED: <2021-05-18 Tue 08:00 .+1d>
  :PROPERTIES:
  :LAST_REPEAT: [2021-05-17 Mon 10:38]
  :END:
  :LOGBOOK:
  - State "DONE"       from "TODO"       [2021-05-17 Mon 10:38]
  :END:
```

When marking the same headline as 'DONE' in organice, the headline changes to:

```
* TODO Test task
  SCHEDULED: <2021-05-18 Tue 10:38 .+1d>
  :PROPERTIES:
  :LAST_REPEAT: [2021-05-17 Mon 10:38]
  :END:
  :LOGBOOK:
  - State "DONE"       from "TODO"       [2021-05-17 Mon 10:38]
  :END:
```

In Emacs, the timestamp does not move. In organice, the timestamp was updated to the time when the TODO was marked as 'DONE'.

**Comment by munen** [comment]
@ tomonacci FYI. 

I found this, because I started to use Org habits to dog food the new functionality^^

**Comment by munen** [comment]
@tomonacci FYI. 

I found this, because I started to use Org habits to dog food the new functionality^^

**Comment by schoettl** [comment]
Shouldn't the issue title be "…, do not update the time portion"?

**Comment by munen** [comment]
> Shouldn't the issue title be "…, do not update the time portion"?

That would probably be the correct way to document the error^^
