### ISSUE TITLE
dropbox signin broken (android chrome)

### ISSUE THREAD

**Issue by edrex** [200ok-ch/organice#685]
**Describe the bug**

When selecting Dropbox at the signin view in the hosted version of organice, the URL bar briefly shows a URL encoded string starting with `[Object` and then reloads the signin view.

**Troubleshooting steps taken**

- clear organice cookies
- sign out of Dropbox
- check Dropbox authorized apps, but organice isn't listed

Things work fine when testing with Firefox on Android.

**Comment by edrex** [comment]
If it's not repro for devs I can attach a remote debugger and look at the errors

**Comment by edrex** [comment]
(android 11)

**Comment by munen** [comment]
@edrex Thank you for your bug report :pray: 

I have looked at it and found the culprit. If you're curious, here's the relevant PR: https://github.com/200ok-ch/organice/pull/686

Can you please test again and give me feedback on whether it works for you now? For that, please make sure that you're running the latest version of organice by forcing a refresh.

In any case, thank you for checking out organice and apologies for the problem :pray:

**Comment by edrex** [comment]
I just got around to testing, and it works! Thank you!
