### ISSUE TITLE
WebDav login fails on PROPFIND req method (401)

### ISSUE THREAD

**Issue by someguynamedmatt** [200ok-ch/organice#699]
**Describe the bug**
I battled through CORS issues (thanks for the great documentation!) and eventually settled on a 401 from the two initial PROPFIND request methods. Both 401 and an error is thrown in my console:
```
PROPFIND https://mydomain/webdav/ 401 (Unauthorized)
Login didn't work, error:  {"message":"Request failed with status code 401","name":"Error","stack":"Error: Request failed with status code 401","config":{"url":"https://mydomain.com/webdav/","method":"propfind","headers":{"Accept":"text/plain","Depth":1,"Authorization":"Basic bXk6ZGFiLXZldGsdfeABau2W4tbWFudHJhLWRlYnRvasf23radnVzaGFibGU="},"transformRequest":[null],"transformResponse":[null],"timeout":0,"responseType":"text","xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1}}
PROPFIND https://mydomain/webdav/ 401 (Unauthorized)
```

...and in my Apache logs I see this...
```
[Thu Jun 10 05:17:01.473588 2021] [auth_digest:error] [pid 6873:tid 140603287377664] [client 104.175.82.162:56058] AH01781: client used wrong authentication scheme `Basic': /webdav/
```
If I hit mydomain.com/webdav and pass in my credentials it works, so I don't think it's a server configuration issue, but I dunno.

Out of curiosity I changed my Apache server to respond to Basic authentication vs. Digest to see how organice would respond. When I did that I got a "password mismatch" error in my access logs (which makes sense). Also, none of my other login methods worked.

I'm sure there's something I've overlooked in the documentation, but is Basic authentication what needs to be done here or should organice be using Digest?

Thanks!

**To Reproduce**
1. Go to 'WebDav'
2. Monitor network traffic
3. watch webdav (or applicable endpoint) 401

**Expected behavior**
Logging in with WebDav should be done via Digest rather than Basic authentication

**Desktop (please complete the following information):**
 - OS: Linux (Arch)
 - Browser Chromium

**Comment by someguynamedmatt** [comment]
Ah! Of course after I post this an idea comes to mind and now my problem is solved! Sorry for the Issues spam. If anyone sees this issue in the future and is using Apache, I solved this by also limiting the `required-user` to `OPTIONS` **and** `PROPFIND`.

Thanks for the awesome app!

**Comment by munen** [comment]
Hi @someguynamedmatt 

Happy to hear you found a working solution! :rocket: 

Thank you for the kind words regarding organice and the documentation :pray: 

If you do have the time, I'd be happy to pull in changes regarding this - either in the [documentation](https://organice.200ok.ch/documentation.html#building_docs) or the [Apache configuration we use for testing](https://github.com/200ok-ch/organice/tree/master/doc/webdav).

In any case, thank you for using organice and have a good time!

**Comment by someguynamedmatt** [comment]
@munen I'd like to collaborate on the project's documentation. Unfortunately, I spoke too soon and I'm still having issues. Specifically, I _can_ log in now, and I can see all of my `.org` files, but every single one of them returns a 404 in the network tab and displays `File {some file}.org not found` on the organice interface.

I can access the files through other mediums so I don't know what's going on, but I'm combing through the docs and will submit an issue if I exhaust all avenues.

Thanks again!
