### ISSUE TITLE
npx: command not found

### ISSUE THREAD

**Issue by damiencourousse** [200ok-ch/organice#701]
hello,

Total newbie here.  Tried to give a test from the README, without knowing anything about the technologies behind, except emacs/org-mode.

Using Debian (based on the current stable), where I assume `yarn` is actually available in the package `yarnpkg`, providing the tool `yarnpkg`.  https://packages.debian.org/buster/yarnpkg

**Describe the bug**
Build error: `npx: command not found`.

**To Reproduce**
On Debian stable, 
1. install package `yarnpkg`
2. build:
```
$ LANG=C yarnpkg build
yarn run v1.13.0
$ ./bin/compile_search_parser.sh && react-scripts build
./bin/compile_search_parser.sh: line 3: npx: command not found
cat: src/lib/headline_filter_parser.js: No such file or directory
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Desktop (please complete the following information):**
 - OS: Debian stable
 - yarnpkg        1.13.0-1+deb10u1

**Comment by jzohrab** [comment]
This feels like a system issue (your machine), and not the code.  See e.g. [this SO post](https://stackoverflow.com/questions/49894620/npx-command-not-found).  What does `node --version` give you?

**Comment by munen** [comment]
@jzohrab Thank you for jumping in :pray: This is a system issue, indeed. 

@damiencourousse You've stated that you installed `npm` via Debian and that you're running Debian stable. Whilst I personally symathize (I run Debian Testing^^), the `npm` bundled by Debian Stable is very old and will not cut it for modern JavaScript applications. organice uses the customary version management of [nvm - Node Version Manager](https://github.com/nvm-sh/nvm) for installation of Node. You can find the documentation on how to install development tooling in the documentation under "Development": https://organice.200ok.ch/documentation.html#development
