### ISSUE TITLE
website is down? 

### ISSUE THREAD

**Issue by whudwl** [200ok-ch/organice#704]
Checked with https://downforeveryoneorjustme.com/200ok.ch?proto=https 
So, it seems it's not just down for me. 

![image](https://user-images.githubusercontent.com/2842789/122843276-6c1bde00-d342-11eb-9814-f46585e4130a.png)

**Comment by dixius99** [comment]
It was down for me yesterday too, but it appears to be back online now.

**Comment by munen** [comment]
The reference installation is hosted by Hetzner. Last night, Hetzner hat it’s first downtime in a long time. 

Hetzner is doing some maintenance. Maybe something will happen tonight, as well: https://status.hetzner.com/incident/60effc8b-701a-4f70-b81d-872c1fce5bfb

In any case, organice is generally not down, generally it is up. But no service is up 100% of the time(;

![08253029-9562-40D9-B364-CCCDDF312128](https://user-images.githubusercontent.com/505721/122994213-7f619480-d3a8-11eb-8ddd-2a662335b5d8.jpeg)

t🥲Thank you for your report and apologies for the inconvenience 🙏🏻
