### ISSUE TITLE
Not possible to access files using an android WebDAV server

### ISSUE THREAD

**Issue by Ypot** [200ok-ch/organice#712]
**Describe the bug**
I think it is very interesting to access our files without sharing them to DROPBOX or GOOGLE. This could be solved using a local WebDAV server for android. The server seems to work, but ORGANICE can't access the files.

**To Reproduce**

1. Install [WebDAV Server](https://play.google.com/store/apps/details?id=com.theolivetree.webdavserver)
2. Check if WebDAV server is working: Browse in your local network to the address of the mobile where WebDAV is running, ie http://192.168.1.2:8080/
3. Login into organice using WebDAV
4. I can't see any files.

**Expected behavior**
4. Files should be seen as they are seen in the web browser when reaching ie http://192.168.1.2:8080/

**Screenshots**
Browsing http://...:8080/ in Android Opera:
![tempFileForShare_20210710-135628](https://user-images.githubusercontent.com/30699014/125162184-c6ac9b00-e186-11eb-97e5-03f1078b3249.jpg)

Organice in Opera:
![Screenshot_20210710-135526_Opera](https://user-images.githubusercontent.com/30699014/125162180-c14f5080-e186-11eb-8f86-e904837af4ce.jpg)

Organice in Chrome:
![tempFileForShare_20210710-135952](https://user-images.githubusercontent.com/30699014/125162272-2b67f580-e187-11eb-97f4-094cdb9b24ac.jpg)

**Smartphone:**
 - Device: Samsung Note 8
 - OS: Android 9.1
 - Browser: Opera, Firefox, Kiwi browser, Chrome

**PC:**
Same behaviour. I can browse my files, using the android WebDAV server, but I can't access to them via organice.

**Comment by munen** [comment]
Hi @Ypot 

thank you for checking out organice! I agree that WebDAV is a good option. Hence, I would ask you to check out the documentation regarding WebDAV, especially the part with regards to opening bug reports: https://organice.200ok.ch/documentation.html#faq_webdav

If the docs don’t help, please do re-open the issue with the requested information. 

Good luck and all the best🙏🏻

**Comment by AlexD97** [comment]
@Ypot were you able to solve this issue?

**Comment by Ypot** [comment]
Hi AlexD97. No, I couldn't solve it. I hope you'll have better luck :-)
