### ISSUE TITLE
Allow setting custom file extensions

### ISSUE THREAD

**Issue by mcdejonge** [200ok-ch/organice#716]
Currently the .org extension seems to be hard coded. If this is indeed correct and I did not simply miss a setting somewhere: would it be possible to make it configurable?

I use .txt myself as that allows editing org files in any old text editing app (such as the Dropbox app on my phone).

**Comment by munen** [comment]
Hi @mcdejonge 

Thanks for checking out organice :pray: 

organice uses `.org` and `.org_archive` extensions to detect Org mode files.

The [Org manual](https://orgmode.org/org.html) describes the setting that you are proposing: 

> Files with the ‘.org’ extension use Org mode by default. To turn on Org mode in a file that does not have the extension ‘.org’, make the first line of a file look like this:

`MY PROJECTS    -*- mode: org; -*-`

> which selects Org mode for this buffer no matter what the file’s name is.

organice already supports various in-buffer settings (see https://organice.200ok.ch/documentation.html#customization). Adding this one is absolutely possible. Would you be interested in doing that?

Kind regards,
Zen Monk Alain M. Lafon

**Comment by mcdejonge** [comment]
Hi @munen / Alain,

It's not so much a question of Organice not recognizing a txt file as org, it's that the .txt files don't even show up in the listing.

A quick perusal of the source tells me the const orgFileExtensions = /\.org(_archive)?$/ (lib/org_utils.js) is the culprit. I'd like to make that configurable :-)

Thanks for the *etremely* speedy reply, btw.

Kind regards,

Matthijs de Jonge

**Comment by munen** [comment]
You are right. My answer was too fast, indeed(; I only thought of half the necessary adjustments. 

organice does filter the folder as you mention. The rationale is to be able to find Org files faster in case there’s lots of files that organice cannot open in the same folder. But some people mentioned before that they’d like to see all their files. 

So, multiple things to consider. One is that we can do without a GUI setting in organice for the file extension, because there’s an in buffer setting. The other thing is: How can we treat folders with different types of files. I see multiple options:

1. Have a GUI setting to toggle between all and just Org files 
2. Make the directory browser smarter and teach it filters 
  - Once a user has a filter, that could be persisted. 

Making the directory browser have some more fundamental features like filter, search and create file would be a nice outlook. 

What do you think?

**Comment by munen** [comment]
Come to think of it. We don’t even need the in buffer setting. organice tries parsing any file it opens as an Org file. If the parser crashes, there’s an error displayed. 

So, it’s only a question of making non .org and .org_archive files accessible in the directory browser.

**Comment by mcdejonge** [comment]
Not knowing enough about this code (nor about this sort of fancy front end app in general, unfortunately) it's difficult for me to assess what a good way to implement a solution would be.

From a general point of view, however, simply slurping everything in and ignoring crashes when something turns out not to be an org file, seems to be rather problematic.

I noticed when you connect with Dropbox you start at the Dropbox root. That means you'll likely encounter hundreds if not thousands of files that in no way can be parsed as org files - probably many more than there are actual org files. Crashing out for each and every one of them is probably a waste of system resources.

**Comment by munen** [comment]
Ah, no worries about organice trying to open _all the files_.

The directory browser is just a browser. organice will _not_ open every file in there. Just the ones that you click on and try to open. And if that happens to be a file with a .txt ending that can be parsed as an Org file, it'll work. If it's any other kind of file, it'll show an error. I think that's pretty much what most apps would do when ask them to open a file, no?

**Comment by mcdejonge** [comment]
Ah, ok, I misunderstood. Yeah, if it only starts parsing when you click on a file that's no problem at all (and probably a more elegant solution).

(btw, I just took a quick look at running it locally to do some hacking but it turns out that's not a trivial endeavour for someone without a lot of front end experience - so I can't *quickly* help out here, sorry.

**Comment by munen** [comment]
No worries about getting it done quickly. I'm happy to help out if you've got questions regarding the setup!

To get you started, the docs could be helpful: https://organice.200ok.ch/documentation.html#development

**Comment by munen** [comment]
Since this issue has been stale for a year, I'll close it according to the [contributor guidelines](https://github.com/200ok-ch/organice/blob/master/CONTRIBUTING.org).

If you want to work on this issue, please feel free re-open it any time! :pray:
