### ISSUE TITLE
README.md should have a TOC

### ISSUE THREAD

**Issue by amm98d** [200ok-ch/organice#765]
**Is your feature request related to a problem? Please describe.**
The README.md is quite lengthy and should have a TOC for easy access.

**Describe the solution you'd like**
I would like to add a TOC to the README.md

**Comment by munen** [comment]
The README is part of the documentation which has a pretty proper TOC(;

![image](https://user-images.githubusercontent.com/505721/145686475-21b4d975-1a1a-4fe5-9f91-52499ffd3501.png)

**Comment by amm98d** [comment]
I meant for GitHub, like the one here:

![image](https://user-images.githubusercontent.com/39633205/145686530-29ea8fcc-4bac-4948-aa26-2f816cb35cab.png)

However, if the current README.md is somehow being used to build the documentation and adding a TOC here would interfere with that, that is understandable.

**Comment by munen** [comment]
Exactly. Plus, the readme is not a md doc, it’s Org mode, of course. So you automatically get a ToC as Emacs user(;
