### ISSUE TITLE
WebDAV syncing (Nextcloud/Owncloud)

### ISSUE THREAD

**Issue by jfmcbrayer** [200ok-ch/organice#77]
This seems pretty nice, but I'm not willing to sync with a commercial service like Google Drive or Dropbox. If you supported WebDAV for syncing, users of Nextcloud or Owncloud could use their own self-hosted storage.

**Comment by munen** [comment]
Synchronization is build using the strategy pattern which is consumed here[1]. Implementing a new backend is as easy as implementing 8 functions[2]. For Dropbox it's about 120 LOC JavaScript.

I'll happily merge any PR enabling a different backend!

Would you be interested in working on it @jfmcbrayer?

1. https://github.com/200ok-ch/organice/blob/master/src/actions/sync_backend.js
2. https://github.com/200ok-ch/organice/blob/master/src/sync_backend_clients/dropbox_sync_backend_client.js#L134-L141

**Comment by munen** [comment]
For future reference, I have added an ADR on how to implement a new synchronization back-end: https://organice.200ok.ch/documentation.html#adr-003
