### ISSUE TITLE
Discussion: UX for trash can (currently deletes the TODO keyword if one is selected)

### ISSUE THREAD

**Issue by schoettl** [200ok-ch/organice#774]
### Discussed in https://github.com/200ok-ch/organice/discussions/773

<div type='discussions-op-text'>

<sup>Originally posted by **tkurtbond** January 14, 2022</sup>
When I edit the title there is a trashcan on the right, but nothing seems to happen when I select it.</div>

The trashcan button in the title edit panel has no effect.

**Comment by tarnung** [comment]
It deletes a TODO keyword if one is selected. The dots on the other side of the TODO keywords switch between TODO keyword sets if multiple ones are defined.
Tell me if you think of a way to make this more clear.

**Comment by tarnung** [comment]
I also like the suggestions 1 & 2. I do not like the written out "next set" though. 
I'll see if i can make 1&2 happen. If there is enthusiasm for 3, someone else should be able to make that happen quickly.

**Comment by munen** [comment]
@tarnung Thanks for responding to the issue, but please do not trouble yourself with implementation. #862 is a PR for all three points. If you want, you can review it, though^^

Btw, after having implemented it and have seen it, I do agree that “Next set” spelled out is not very nice. It’s pretty bold and “in your face” while it’s not the most important action on the screen at all. However, I do think that the ellipsis before were a bit undiscoverable. At this point, I don’t see a good alternative. I’m fine using #862, but reverting to the ellipsis if we don’t come up with another idea.

**Comment by munen** [comment]
> schoettls mockup is tame and reserved compared to your implementation.

Agreed :sweat_smile: 

One option to tame it a bit:

1. Having todo keyword sets is a pro user option. It's pro for at least so long as we don't have a UI to configure todo keyword sets. Hence, a lot of users will not need to see a button that doesn't do anything. I'm proposing to hide it if there's only one todo keyword set configured for the file.

2. > The only other button of this kind is the "Add" button in the notes modal 

And in the capture screen.

However, at least in the capture view and "add note" view, the "add", respectively "capture" are the only cta. It's the traditional "OK" button. In the view we are talking about, it's totally not the most important button at all.

One more thing: If the user has multiple or just one todo keyword sets, I'd argue that the most important task is to switch between keyword states, not toggle the sets.

In my latest commit, I'm proposing the following look. That one still can be improved upon by anyone with better design skills. But at least, it addresses the issues in as far as I'm able to(; I'm happy if anyone with better design/UX skills wants to pick it up from here.

![image](https://user-images.githubusercontent.com/505721/176411191-719490c5-f18b-499c-a2fe-b24cb0c66286.png)

If there's only one keyword set, this changes to an even simpler:

![image](https://user-images.githubusercontent.com/505721/176411103-91cb7c7b-810d-4308-aa81-429733caa41b.png)

> I can live with ugly buttons though and i think https://github.com/200ok-ch/organice/pull/862 is an overall improvement whether you decide to revert to the ellipsis or not. +1

Thank you :pray:

**Comment by munen** [comment]
New issue created: https://github.com/200ok-ch/organice/issues/867
