### ISSUE TITLE
PWA not installable

### ISSUE THREAD

**Issue by tbruckmaier** [200ok-ch/organice#779]
I cannot install organice as a PWA on my mobile browser (the "install" button does not appear in any browser, while it works on other PWAs like https://mdn.github.io/pwa-examples/a2hs/)

On desktop, Chrome & firefox both report several errors with the app manifest (Developer tools -> Application -> Manifest)
- "Manifest start URL is not valid"
- "Manifest does not contain a suitable icon [...]"

I have debugged the issue locally, and it seems to be a problem with the dynamically generated blob url, introduced in https://github.com/200ok-ch/organice/pull/465 . Apparently the relative urls (`"/"` for `start_url`, or `"organice-512x512.png"`for the icon `src` fields) are not resolved correctly when they appear inside `createObjectURL`?
When I manually change `start_url` and `src` to absolute urls, the errors from firefox & chrome disappear and both report the PWA as "installable".
The errors also disappear when the JS logic is removed, and a static `manifest.json` with relative urls is referenced in the `<link>` tag.

A possible fix could be to create absolute urls on the fly, that should not lead to any issues I guess? I can create a pull request for that if you like.

**To Reproduce**
1. Go to https://organice.200ok.ch/files
2. Open developer tools: Application -> Manifest
3. Error messages appear, PWA is shown as "not installable"

**Expected behavior**
PWA is installable, Browser report no errors with the app manifest

**Screenshots**
![image](https://user-images.githubusercontent.com/4941331/155301709-180e1d9e-e8a2-4f6f-978a-1db9f494c0d0.png)

Test with manually set absolute urls (with the same JS logic):
![image](https://user-images.githubusercontent.com/4941331/155303458-22dbfdef-1fa6-452b-8b94-d20a1bb29d40.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox 97.0.1 (64-bit), Chromium 98.0.4758.102 (Official Build) Manjaro Linux (64-bit)

**Comment by munen** [comment]
Hi @tbruckmaier 

Thank you for your report :pray:

A bit of background: We have introduced https://github.com/200ok-ch/organice/pull/465 to fix a change that happened on Android. The previous version still worked on iOS. The current version still works on iOS (I just tested with an iPhone 13 pro running the latest iOS 15.3.1). You mention that you cannot install it on a mobile browser, I'm assuming you're on Android? I can confirm, however, the same manifest error/warning in FF in Debian Linux!

> A possible fix could be to create absolute urls on the fly, that should not lead to any issues I guess? I can create a pull request for that if you like.

Could be. If you're doing a PR, I'm happy to deploy it to staging.organice.200ok.ch so we can both test it. If it works for current Android and current iOS, then let's merge it^^

Thank you, again, for the detailed report and the willingness to work on a solution!

**Comment by munen** [comment]
@schoettl Iirc, you're an Android user, too. Can you confirm that organice currently cannot be installed as a PWA?

Thank you(;

**Comment by schoettl** [comment]
Not sure, should there be a separate install option? The "add to home screen" button is there. For me, it still works offline given that it was opened when I was online.

![signal-2022-02-23-122549](https://user-images.githubusercontent.com/1301843/155310757-5dc4cf33-a5eb-4b30-82f7-97e2e6976e34.png)

**Comment by tbruckmaier** [comment]
Hi @munen and @schoettl , thanks for your quick feedback! Yes right, I am on Android, should have mentioned that...

@schoettl yeah, PWAs show a "Install" button there. "add to home screen" is shown for every website, that just creates a shortcut to that specific url (which opens in the browser regularily)

I will send a pull request shortly, I'm happy to test it on the staging environment!

**Comment by munen** [comment]
@schoettl Thank you for quickly checking it out :pray: 

I did look up the [docs from Google](https://support.google.com/chrome/answer/9658361?hl=en&co=GENIE.Platform%3DAndroid) and they confirm there should be an 'install' button.

The fix is deployed to production. I hope it leads to a better PWA experience for Android, now.

**Comment by tbruckmaier** [comment]
@munen I can confirm, the PWA is installable in Android now as well. Thank you all for the fast update!
