### ISSUE TITLE
FAQ WebDAV has moved?

### ISSUE THREAD

**Issue by schoettl** [200ok-ch/organice#787]
**Describe the bug**

In the README, there are some places linking `#faq_webdav` (i.e. anchor within README). But I can't find these anchor definition and the links don't work. I think it actually refers to https://organice.200ok.ch/documentation.html#faq_webdav

Should I change these occurrences to the absolute URL or did I get something wrong?

**Comment by schoettl** [comment]
Ah, I understand. I agree that it makes no sense to merge Wiki and README into one even bigger GitHub README.

The only solution that comes to my head is to use absolute URLs in the README where it refers to anchors that are not in the README (i.e. links referring to documentation.html).

When generating the documentation, a sed script could then replace the absolute URL `https://organice.200ok.ch/documentation.html#building_docs` with `#building_docs`.

This would fail if one day, the URL to documentation.html changes. But it would lead to a "correct" README *and* documentation, right?

**Comment by munen** [comment]
Yes, that would absolutely work :+1:
