### ISSUE TITLE
Toggling checkbox deletes marked-up text

### ISSUE THREAD

**Issue by chasecaleb** [200ok-ch/organice#796]
**Describe the bug**
Toggling a checkbox causes Organice to delete any marked-up text (bold, italics, etc) within the same heading's contents.

**To Reproduce**
1. Create a heading with a plain-list checkbox element as well as some marked-up text.
2. Toggle the checkbox
3. Sync
4. Refresh the page or view on another device: marked-up text is gone.

Here's the example org file I'm using for my repro screenshots:
```org
#+TITLE Organice Playground

* Organice checkbox markup bug
- : toggling a checkbox causes Organice to delete marked up text.
- The original (correct) text is still displayed in Organice, but it disappears after refreshing the page.
- [X] Checking this triggers the bug.
- Bold  will disappear.
- Italics  as well.
- Same with  and presumably other markup.
** Sub heading
   - Contents in sub headings *are not touched*
* Sibling heading
  - Contents in sibling headings *are not touched*
```

Here's the diff of the commit where Organice syncs the checkbox toggle:
```patch
diff --git a/organice.org b/organice.org
index 0535a374..f653b987 100644
--- a/organice.org
+++ b/organice.org
@@ -1,12 +1,12 @@
 #+TITLE Organice Playground

 * Organice checkbox markup bug
-  - /Bug/: toggling a checkbox causes Organice to delete marked up text.
-  - The original (correct) text is still displayed in Organice, but it disappears after refreshing the page.
-  - [ ] Checking this triggers the bug.
-  - Bold *like this* will disappear.
-  - Italics /like this/ as well.
-  - Same with +strikethroughs+ and presumably other markup.
+- : toggling a checkbox causes Organice to delete marked up text.
+- The original (correct) text is still displayed in Organice, but it disappears after refreshing the page.
+- [X] Checking this triggers the bug.
+- Bold  will disappear.
+- Italics  as well.
+- Same with  and presumably other markup.
 ** Sub heading
    - Contents in sub headings *are not touched*
 * Sibling heading
```

**Expected behavior**
Organice should preserve marked up contents.

**Screenshots** (Organice on left, Emacs on right)
1. Initial state: 
![2022-05-24-100800_1654x525_scrot](https://user-images.githubusercontent.com/5241169/170086995-b27585d2-6528-4b08-8887-60d16960d59c.png)

1. After toggling checkbox the underlying file is changed (see Emacs view) but Organice does not reflect this: 
![2022-05-24-100843_1669x560_scrot](https://user-images.githubusercontent.com/5241169/170087010-60fbdca7-6003-4499-ab56-0c89d4443fb8.png)

1. After refreshing Organice the bug is shown: 
![2022-05-24-100900_1620x536_scrot](https://user-images.githubusercontent.com/5241169/170087032-015567ae-cd1b-4a07-b4d2-e318f44607d1.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox 100

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S9+
 - OS: Android
 - Browser: Firefox

1. After refreshing Organice the bug is shown:
  ![](file:///tmp/2022-05-24-100900_1620x536_scrot.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox 100

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S9+
 - OS: Android
 - Browser: Firefox

**Comment by chasecaleb** [comment]
This isn't the same scenario as #668, but it might be the same underlying. If not, I suspect it's at vaguely 

Implementing #18 would also resolve the issue here, but I think this is worth fixing ASAP since it results in data loss (as opposed to waiting for #18, which is a long-term effort).

I'll try to poke around with this issue when I get a chance -- if anyone has suggestions on where to start looking or wants to help though it would be appreciated.

**Comment by schoettl** [comment]
Oh, that's a bad one. Thanks for reporting! It's already documented here though: #376 
So I guess we can close this issue.

I would appreciate very much if you have to time to check on it and fix it. I't start looking in the reducer function for the check/uncheck feature. Looks like that one is somehow deleting the markup.
