### ISSUE TITLE
Installing it

### ISSUE THREAD

**Issue by deshmukhs** [200ok-ch/organice#815]
A complete newbie here. So, the question may sound very basic.

How do I install it? I thought that all web apps are necessarily html files that I need to open in a browser. I have used tiddlywiki in the same way.

But, here, no such file is available. What exactly do I need to do?

Thanks.

**Comment by schoettl** [comment]
Hi @deshmukhs,
To install it, you have to open a hosted instance of organice in the browser on your mobile device. You can only install an web app that is hosted on a server. E.g. you can use the instance at https://organice.200ok.ch/
From there, refer to the [installation section](https://github.com/200ok-ch/organice#installation)

**Comment by deshmukhs** [comment]
@schoettl Thanks. That got me started, at least. I, now, have an 'app' on my mobile phone that opens organice in its own window.

A few other problems have cropped up. But I'll raise them separately.

One point, though. Without 'Signing In', it isn't possible to do much. This is a bit counter-intuitive given that organice is offline capable.

Lastly, to install it on FF on Android, there's an 'Install' option in the three dots menu. May be, we can update the instructions. :)

**Comment by schoettl** [comment]
@deshmukhs @munen to be honest, I agree that "sign in" is not 100% intuitive. My first reaction was "sign in, sign up? why would i need to create an organice account?". "Connect cloud storage" would maybe more clear, or just "Open organice app".

Regarding the installation instructions, I'll check this README section later!

**Comment by munen** [comment]
@schoettl I’m on the fence regarding wording. 

I can appreciate that “Sign in” can lead to the question regarding having to create an account for organice. However, what’s the issue with that?

Imo, if “Sign in” is creating trouble, which is quite a normal action to do for many apps, then the CTA “Open organice app” _after_ having opened the actual organice app will blow some heads. This kind of recursion might just be too much on some^^

And “Connect Cloud storage” does not sound like a very catchy primary CTA on a landing page. 

If you don’t like “Sign In”, I propose we start a separate discussion and go over options.
