### ISSUE TITLE
Using organice completely offline

### ISSUE THREAD

**Issue by deshmukhs** [200ok-ch/organice#819]
In order to use organice, it is almost mandatory to sign in to a syncing service.

Can it not be used exclusively with a local file? So, instead of connecting to a sync service, I just open the local file.

Also, I am using dropbox backend for now. The URL is shown as 'https://organice.200ok.ch/file/Apps/organice/test.org'

Is it that all files are also stored on organice.200ok.ch?

**Comment by munen** [comment]
Thank you for using organice. Please do read the documentation first before opening one issue after the other. Your last issue was answered in the docs. This latest issue is literally answered in the first paragraphs under “What does this project do”: https://organice.200ok.ch/documentation.html#what-does-this-project-do

If, after reading the docs, you have further questions please ask them in the community chat.

**Comment by deshmukhs** [comment]
@munen Apologies. I could have read the docs more carefully. Will keep in mind going forward

**Comment by munen** [comment]
Sweet, thanks 🙏🏻

All the best of luck and if you’ve got questions, you’re very welcome to join the community chat: #organice on IRC [Libera.Chat](https://libera.chat/), or [#organice:matrix.org](https://matrix.to/#/!DfVpGxoYxpbfAhuimY:matrix.org?via=matrix.org&via=ungleich.ch) on Matrix.
