### ISSUE TITLE
Showing overdue items on the agenda views

### ISSUE THREAD

**Issue by dmorlitz** [200ok-ch/organice#828]
Would it be possible (and easy) to have the agenda views also show incomplete and overdue tasks at the top.  While I am very new to org mode, I believe that their agenda view does have this capability.  I am not sure if that would be easy to build into your library or not - but I wanted to ask.  I think that would be a significantly helpful feature.

**Comment by munen** [comment]
Hi @dmorlitz 

That’s a vert reasonable request. And you are right, EMacs Org mode supports it. Luckily, organice also does(; I use it all the time, too. 

Here’s an agenda with quite a few issues that are way overdue:

![F471260E-A6E1-409A-8D6F-F91258F63F77](https://user-images.githubusercontent.com/505721/173193510-117f28b1-5f00-4802-a9ea-14f75f7ab27f.jpeg)

As you can see, the oldest issue is on top. You can also tap the date and make it switch to relative time:

![B7550BD1-B3CB-4C25-B12A-0BBC58801ED4](https://user-images.githubusercontent.com/505721/173193576-2223096b-0955-43ca-8b8a-0b1a9f7eee57.jpeg)

The important part is to look at the “Day” agenda tab for this. If you look at “Week” or “Month” you will get the scheduled tasks starting on the current date. 

If I understand you correctly, this is what you want. Let me know if you have a different requirement. 

Kind regards

**Comment by dmorlitz** [comment]
My apologies - you are quite correct.  This feature appears to already be here.  What had confused me is that (since I am new to org mode) none of my todo's were significantly old.  It appears on the agenda view that overdue items will appear on the day they are due (if that is on the screen) AND on today.  Since I was looking at the week and month view (and none of my test todo's were more than 1 week overdue) the duplication and sorting had me confused.
