### ISSUE TITLE
Header scrolls off screen

### ISSUE THREAD

**Issue by tarnung** [200ok-ch/organice#865]
The header (where the undo/redo buttons sit) scrolls off screen when scrolling in a view.

This behaviour existed way back when but for the last two years the header was sticky if i recall correctly.

Feel free to close this if it's an intended change that i just happened not to like.

**Comment by munen** [comment]
Good catch.

It is not an intended change. I botched it by accident by implementing [feat: Proper Landing Page](https://github.com/200ok-ch/organice/pull/809#)
#809[feat: Proper Landing Page](https://github.com/200ok-ch/organice/pull/809#)
#809 which was way more effort than I anticipated. But it also did bring a lot of goodies - not just the LP, but some refactoring. One PR before that, the header was still sticky.

**Comment by munen** [comment]
Hm.. it's not as easy as I hoped. Before introducing #809, it worked. After introducing #809, it did not. 

But going through the CSS code, I don't see what botched it. So it's probably markup related, not just CSS.

**Comment by munen** [comment]
I have created a PR based on the first original sticky header from 2019. That one turned out not to be sufficient since there were follow up PRs. However, it does seem to work well for me in first tests.

I'd be happy if you can check it out. If you like it, feel free to merge the PR.
