### ISSUE TITLE
Documentation has escaped HTML

### ISSUE THREAD

**Issue by schoettl** [200ok-ch/organice#880]
Seems to be a bug in the documentation make/deploy process...

![grafik](https://user-images.githubusercontent.com/1301843/177836179-88ceff18-c1ed-4dc5-b206-72b09199d6ce.png)

https://organice.200ok.ch/documentation.html

**Comment by munen** [comment]
Good catch!

@branch14 recently introduced nice labels for the Readme. Doesn't look like they are playing well with the docs -_-

![image](https://user-images.githubusercontent.com/505721/177836462-3db0ed9f-e4e0-48fd-a967-d1245808ef37.png)

**Comment by munen** [comment]
Makes actual sense, Phil replaced the 'ugly' inline `#+html:` blocks with `#+BEGIN_HTML`, but those are different When Emacs exports the latter, that's actually a code block!

**Comment by munen** [comment]
I thought that setting `:results value raw` to the source block would work, but on a first try it does not. I'll look into it another time.

Relevant exporting docs: 

https://orgmode.org/manual/Results-of-Evaluation.html

**Comment by schoettl** [comment]
Shouldn't it be `#+BEGIN_EXPORT html`? https://orgmode.org/manual/Quoting-HTML-tags.html

**Comment by munen** [comment]
Yes, that would be a totally valid option. But then the wonderful legacy Org mode parser of Github won't show it in the Readme(;

**Comment by munen** [comment]
If only there would be a good parser and Github would be FOSS, then we could make a PR to remedy that. A big and an even bigger 'if'(;

**Comment by schoettl** [comment]
> I thought that setting `:results value raw` to the source block would work, but on a first try it does not. I'll look into it another time.
> 
> Relevant exporting docs:
> 
> https://orgmode.org/manual/Results-of-Evaluation.html

Do you even have an HTML babel interpreter configured (`org-babel-execute`)? What does that do? The most useful thing is lingting IMO :D

```
#+begin_src html :results value raw
  <p>
#+end_src
```

**Comment by munen** [comment]
> Do you even have an HTML babel interpreter configured (org-babel-execute)?

I’m not sure I understand the implication. Of course babel understands HTML. 

> The most useful thing is linting IMO :D

Again, I don’t understand. There’s great tooling around HTML in Emacs and Org. For example this is a popular and powerful mode: https://web-mode.org/

Having said all that. For the Readme/docs, that’s all completely irrelevant. We just want to inject HTML into the exported document.

**Comment by munen** [comment]
`#+BEGIN_HTML` and `#+BEGIN_EXPORT html` are basically the same. Prior to `org-mode` 8, the first was used, afterwards the latter.

Unfortunately, Github uses a super legacy and buggy Org parser. That's why we used `#+BEGIN_HTML`. Unfortunately, Emacs does not export it the way it used to.

So the solution is to use the common denominator `#+HTML` which we used before introducing the new badges.
