### ISSUE TITLE
Progressive web app isn't working in Firefox on Android

### ISSUE THREAD

**Issue by cwitte** [200ok-ch/organice#89]
When I go to [](https://organice.200ok.ch/) in Firefox on Android, I expect there to be a button in the address bar "Add to homepage" as this is a PWA. The button doesn't appear. Let me know if I could provide more information to help debug this.

**Comment by munen** [comment]
Hi @cwitte 

Thank you for the bug report. I don’t have an Android, so I cannot test this. It works fine in iOS. Having said that, I want it to work on Android, too, of course. That’s why I looked up the docs: 

- https://hacks.mozilla.org/2017/10/progressive-web-apps-firefox-android/
- https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Add_to_home_screen

The latter shows the requirements for the button to appear on Android Firefox. Just reading them, I’d say organice qualifies for all. 

I’d appreciate it if an Android user can point to the specific thing that’s missing. Any help is appreciated🙏🏻

**Comment by munen** [comment]
@AlexMihov Since you're an Android user, can you please verify that the PWA functionality of organice is indeed not working?

**Comment by AlexMihov** [comment]
@munen I can confirm, that with the newest Android Version 10 on a Pixel 3 with Firefox 68.2.0 I do not see the icon on the top next to the address bar.

On other pages, such as `https://app.starbucks.com/` I do get the button, but there seems to be a bug with the default google launcher (or my phone behaves weirdly), since I do get the button and then a prompt, but when I accept, it does not add it to my home screen, where as it does work with third party launchers such as Nova Launcher;

The same is valid for Chrome on Android by the way;

**Comment by cwitte** [comment]
From reading here: https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Add_to_home_screen
it appears to be missing a link to the manifest file in the header of the html file, something like:
<link rel="manifest" href="manifest.json">
I'm not 100% sure though and I don't know how to test it.

**Comment by munen** [comment]
@AlexMihov Thank you for double checking!

@cwitte Thank you for validating which of the requirements is missing. I just added a link as described by the documentation that you've sent.

![image](https://user-images.githubusercontent.com/505721/68954071-89caae00-07c3-11ea-8c6f-121628ac5cb9.png)

Could you please retry, again? Please note that organice is using a ServiceWorker (https://github.com/200ok-ch/organice#pwa--offline-support), hence make sure to get the new version loaded into your browser(;

Thanks again for testing and debugging! :pray:

**Comment by vanous** [comment]
I can confirm that the add to homescreen button is now visible and working on ff on android. Awesome job !

**Comment by cwitte** [comment]
Great, it is now working for me too!

Thanks heaps.

**Comment by munen** [comment]
Awesome, thanks everyone! \(^-^)/
