### ISSUE TITLE
Missing folders in Dropbox

### ISSUE THREAD

**Issue by jbarbero** [200ok-ch/organice#896]
Hi organice team! I love this web app, but I'm having trouble with Dropbox sync. Certain folders don't show up.

My Dropbox root dir contains these folders:
1. action
2. Apps
3. data
4. docs
5. home
6. osx
7. Screenshots
8. Sent files
9. shared
10. tmp-backedup
11. wallet

What organice sees:
1. Apps
2. Screenshots
3. Sent files
4. docs
5. home
6. osx
7. shared
8. wallet

I can still access the missing folders by navigating to them manually, but I then can't add a bookmark to that view on iOS due to a bug generating start_url in the manifest, which I will debug and file an issue for separately.

The problem here is, why are certain Dropbox folders missing? Are there debug logs I can upload?

Thanks!

**Comment by schoettl** [comment]
That sounds weird. I see all my folders (except hidden folders starting with a dot).

Is it the same problem on your iOS and on a desktop PC?

Are you sure that you are not looking at two different Dropbox accounts, a newer one and an older one with less folders?

**Comment by jbarbero** [comment]
Yes, I'm sure. I thought it might be too many folders, so I reorganized my
Dropbox until it had only the above 11 and 3 are still missing. Organice
shows the new folders but some are still missing.

I see the same folders on Firefox on OS X, Firefox on iOS, and Safari on
iOS.

**Comment by munen** [comment]
That's an interesting issue, indeed.

I cannot delete all my folders in the root directory to try a 'pure' reproduction, but I have created your folders in a sub-directory `mkdir action Apps data docs home osx Screenshots "Sent files" shared tmp-backedup wallet` with. There, they show up just fine:

![image](https://user-images.githubusercontent.com/505721/190369785-e3fd603a-977d-49a3-924c-614273d984b6.png)

Does it work for you in a sub-directory? Or asked differently, is this issue specific the folders being in the root directory?

**Comment by munen** [comment]
OP hasn't answered in 9 months and the issue couldn't be reproduced.

OP, if you still have the issue and want to provide more information, please feel free to re-open this issue.
