### ISSUE TITLE
Fallback font formatting issues

### ISSUE THREAD

**Issue by neildavidforrest** [200ok-ch/organice#908]
**Describe the bug**
On Firefox Android the Courier font is not available and the CSS does not specify any mono-spaced fallback, so a variable width font is used and the formatting is a bit messed up. In addition to the variable width font, the bullet points are not aligned correctly with the headings.

While this issue is perhaps more to do with Firefox or the OS, it would probably be a good idea to provide a more acceptable appearance/fallback font when the desired font is missing?

**To Reproduce**
Look at Organice on Firefox for Android.

**Expected behavior**
Correct formatting with mono-spaced font fallback on all platforms.

**Screenshots**
![Screenshot_20221202-110303](https://user-images.githubusercontent.com/106537273/205279391-0620c3b0-541b-484c-b7e5-f0016fe8f4b1.png)

**Desktop (please complete the following information):**
 - Works find on Firefox desktop

**Smartphone (please complete the following information):**
 - Device: Fairphone 4
 - OS: Android 11
 - Browser: Firefox 107.2.0

**Additional context**
I edited the CSS to add `monospace` as a fallback, however the bullet points are still not aligned correctly.

**Comment by munen** [comment]
Would you also say it's a duplicate? If so, then I'll close this one.

**Comment by neildavidforrest** [comment]
Ah yes, I didn't find that one - thanks.

**Comment by munen** [comment]
👍
