### ISSUE TITLE
Undesirable auto-capilalization in search text input (Android Chrome)

### ISSUE THREAD

**Issue by neildavidforrest** [200ok-ch/organice#913]
**Describe the bug**
When using the search or task list text inputs the Android keyboard automatically applies the shift key, meaning that the first character is capatalized.

99% of the time this is not what I want because:
- Having mixed case triggers a case sensitive search. This is quite confusing when I did not intentionally use capitalization, but it was added anyway. For example, I type "and", and it actually inputs and searches for "And", which yields no results.
- Many of the keywords in the search grammar are lower case, e.g., `deadline:` `desc:`.  

As a consequence the first step of any search I do is to disable the shift key, which is rather annoying.

![image](https://user-images.githubusercontent.com/106537273/205782730-5b5df1d6-96cb-4ff7-9823-f622af442bea.png)

**To Reproduce**
1. Open the search modal

**Expected behavior**
Default should be lower case. IMHO.

**Screenshots**

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
 - Device: Fairphone 4
 - OS: Android 11
 - Browser: Chrome 107.0.5304.141 

**Additional context**
N/A

**Comment by munen** [comment]
Closed by #914.
