### ISSUE TITLE
Error on organice installation : node 12.13.0 LTS

### ISSUE THREAD

**Issue by nx345** [200ok-ch/organice#92]
Trying to install organice with yarn, I got this error : 

[1/5] Validating package.json...
error organice@0.2.0: The engine "node" is incompatible with this module. Expected version "12.9". Got "12.13.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

Node 12.13.0 is the LTS version, why version 12.9 is expected then ?

**Comment by munen** [comment]
Because organice needs no back-end and is not in long term support mode, but is constantly being developed. And being 3 minor versions behind is a trivial fix.

It installs and runs just fine with 12.13.0: https://github.com/200ok-ch/organice/commit/1b98a32f9d130b43a2a14e815e32fcb5b1a8b561

**Comment by nx345** [comment]
Thank you !
