### ISSUE TITLE
Improve styling of "deadline display" in responsive and mobile mode

### ISSUE THREAD

**Issue by munen** [200ok-ch/organice#923]
https://github.com/200ok-ch/organice/pull/891 added a deadline display option on headlines. It works great and is a solid implementation. Only in responsive mode and on mobile devices, there's room for improvement.

This is what it looks like on an iPhone 13 pro in PWA mode:

![3BDFBF3E-A2C4-44AD-9A96-1327722CAB57](https://user-images.githubusercontent.com/505721/210578345-07ec8328-17ab-4890-a120-313935575d1a.png)

Here it's in FF on Linux, using responsive mode to simulate a Galaxy 20:

![image](https://user-images.githubusercontent.com/505721/210578764-d15be66f-0ca8-4a6a-a691-6c9cde0b18a2.png)

**Comment by munen** [comment]
@dmorlitz Pinging you here for reference, because I mentioned I'll open a new issue for the responsiveness improvement on the new deadline display. Not that you have to take action on it, anybody can take it up!

**Comment by dmorlitz** [comment]
I have opened PR#925 (https://github.com/200ok-ch/organice/pull/925) which starts to fix some of these issues.  This PR adds a non-breaking attribute to the overlaid date and increases the right margin on the overlay so it does not fall off the screen on the systems I tested it on.  I want to see if I can more programmatically find the right margin - or change the span to a div - to avoid text falling off the screen in all cases

**Comment by dmorlitz** [comment]
I do also want to quickly mention that the date in the "Doctor's appointment" in the Sample file is part of the Description and not an actual Deadline - which is why it renders differently in your screenshot above.

**Comment by munen** [comment]
Closed by https://github.com/200ok-ch/organice/pull/925
