### ISSUE TITLE
Rendering of headlines with multiple italic words

### ISSUE THREAD

**Issue by munen** [200ok-ch/organice#94]
A header like `This /is/ a header with multiple /italic statements/` all of the text between the 2 words will display as italic, too.

<img width="531" alt="Screenshot 2019-11-03 at 19 21 31" src="https://user-images.githubusercontent.com/505721/68090005-28bfe380-fe6f-11e9-8756-d368f9521694.png">

**Comment by schoettl** [comment]
This is the "monster regex" in `parse_org.js`. The inline-markup regex is greedy, that is the problem. See #157

**Comment by munen** [comment]
Duplicate of https://github.com/200ok-ch/organice/issues/198
