### ISSUE TITLE
point organice to a read-only url, eg local file://

### ISSUE THREAD

**Issue by ashmanskas** [200ok-ch/organice#940]
I just gave organice a try, to see how handy it may be for letting me browse and search existing org content without editing it.

To do this, I wound up creating a gitlab repo, since my attempt to read via fastmail's webdav interface, as well as my attempt to read via local webdav, returned a failure message that didn't include any details; and I seldom use dropbox.

I think that for initially trying out organice on a desktop/laptop, it would be very handy to be able to point organice to a URL at which to find an org file, eg

https://raw.githubusercontent.com/xenodium/xenodium.github.io/master/index.org

or 

file:///home/ashmansk/org/test.org

Alternatively, one could point to a directory, possibly containing .organice-config.json as well as a set of org files.

Is this a feature that would have wider appeal?

**Comment by munen** [comment]
> Is this a feature that would have wider appeal?

Sure, apart from it not being technically possible.

However, there's ways to check out organice:

- https://organice.200ok.ch/sample
- https://organice.200ok.ch/documentation.html#faq_webdav
- Using the Android native app: https://github.com/200ok-ch/organice/pull/933

**Comment by unhammer** [comment]
>  my attempt to read via fastmail's webdav interface, as well as my attempt to read via local webdav, returned a failure message that didn't include any details

Just tried fastmail, from the console log it seems fastmail's CORS policy stops it from being used by organice (you would need to access it from a browser that doesn't check CORS policies). Would be nice if organice mentioned the CORS failure, but maybe that's difficult to know from js.

**Comment by munen** [comment]
@unhammer There is extensive documentation on how WebDAV as a protocol works, including CORS: https://organice.200ok.ch/documentation.html#faq_webdav

**Comment by ashmanskas** [comment]
The WebDAV/CORS documentation in the FAQ is indeed very extensive.  I suppose the WebDAV failure message "There was an error retrieving files!" could potentially point the user to the excellent diagnostic suggestions at

https://organice.200ok.ch/documentation.html#faq_webdav

which do mention why "organice cannot show you a really semantic error message on" WebDAV access failures.

It seems the message is generated in 'getDirectoryListing', which is not specific to the WebDAV sync backend.

https://github.com/200ok-ch/organice/blob/a7f57ce8520778625ba634617be681e2de6c117d/src/actions/sync_backend.js#L83

> @unhammer There is extensive documentation on how WebDAV as a protocol works, including CORS: https://organice.200ok.ch/documentation.html#faq_webdav
