### ISSUE TITLE
Google/Youtube Fingerprinting

### ISSUE THREAD

**Issue by AblatedSprocket** [200ok-ch/organice#948]
Hello!

In an earlier issue you mentioned being no friend to Google, so I thought it would be a good idea to create an issue about Organice posting data to googleapis, youtube, and play.google initiated by base.js and www-embed-player.js.

There may be another motivation for this traffic but I'm assuming that React is the cause, in which case your hands may be tied or the ends don't justify the means. If it's something you can't do anything about, I personally would very much appreciate at least a call-out to this in the README.

Thanks for your efforts to make Org more accessible on the web.

**Comment by munen** [comment]
Hi @AblatedSprocket 

Thank you for opening the issue. It is correct, I am not in favor of a FOSS application to send personal data to Google Analytics. And organice, the application, does not. What you observe as tracking is solely the Youtube embed on the landing page:

![image](https://user-images.githubusercontent.com/505721/231132414-5c80aa01-d547-4d8a-b9f3-a8879364465d.png)

Not even the landing page has any explicit tracking - neither through proprietary nor free software means.

> If it's something you can't do anything about, I personally would very much appreciate at least a call-out to this in the README.

The video explicitly shows the Youtube logo.
