### ISSUE TITLE
Setting of "Start of week for weekly agenda" is lost quite often

### ISSUE THREAD

**Issue by Simon-4545** [200ok-ch/organice#954]
**Describe the bug**
I wish to use the option for "Start of week" to set it to Sunday.
I do this from "Settings" menu, by selecting the "S" - for Sunday start of the week.
This setting holds for quite some time, (hours, days) but eventually it is lost, and the settings is back to default of "Monday" day.
This might be true for other day selection, but I've only tested it with attempt to select Sunday.

**To Reproduce**
1. While browsing an ORG file, go to "Settings" and select a different day than "Monday". I use Sunday, - so try this to re-produce first, 
2. Keep using for few days, and check if this settings holds over time. To me it doesn't

**Expected behavior**
When viewing a "Weekly Agenda", one can notice if starts from Monday, or from the other selected day from Settings menu.
Also - one can go to "Settings" page, and see if the selection of "Start of week for weekly agenda" entry has changed back to Monday.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] Firefox.

**Smartphone (please complete the following information):**

**Additional context**

**Comment by munen** [comment]
Hi @Simon-4545 

Thank you for reporting the issue. Do other settings persist fine for you?

**Comment by munen** [comment]
Closing according to https://organice.200ok.ch/documentation.html#how_we_work_with_issues
