### ISSUE TITLE
Can you use a local directory?

### ISSUE THREAD

**Issue by danielkrajnik** [200ok-ch/organice#959]
**Is your feature request related to a problem? Please describe.**
Only syncing options I see are Dropbox, GitLab and WebDAV. I have all org-mode notes synced with either syncthing or rclone to a local folder. Can organice use these files directly instead?

**Describe the solution you'd like**
Use local files in the local folder.

**Describe alternatives you've considered**
I tried running webdav server from termux, but it errored "can't retrieve files".

Maybe there are some other packages? Is it not possible to run organice as a standalone app?

**Comment by munen** [comment]
This topic has been discussed many times over. Please consult the docs and closed issues.

**Comment by munen** [comment]
For future reference, I have added an ADR on how to implement a new synchronization back-end: https://organice.200ok.ch/documentation.html#adr-003

**Comment by danielkrajnik** [comment]
Thank you for adding this, I'm new to this project and slightly overwhelmed. Would it be possible to please clarify whether there is a "local" backend? I keep seeing only Dropbox, GitLab, and WebDAV APIs? I could only find [this issue](https://github.com/200ok-ch/organice/issues/932) mentioning some work on a native client, but it hasn't been updated since January.

I'm just trying to use organice without any external server.
