### ISSUE TITLE
Message about a bug when trying to open an org file

### ISSUE THREAD

**Issue by mikeorlov** [200ok-ch/organice#966]
Hello!

I created a new org file via the app. Then I added a header with a deadline and a repeater. After that, I accidentally clicked "Back" in the browser. And now it shows an error message "Uh oh, you ran into a bug!" when I try to open the file.
The org file itself attached: [miker.txt](https://github.com/200ok-ch/organice/files/12525468/miker.txt)

Desktop: Mac OS X
Browser: Brave
Instance: https://organice.200ok.ch/ 
Synchronization back-end: Dropbox

**Comment by mikeorlov** [comment]
I can access the file after reloading the page. I guess, it does not need to be reported.

**Comment by munen** [comment]
Thank you for the effort, though 🙏 

Happy hacking and enjoy using organice!
