### ISSUE TITLE
Web Mode

### ISSUE THREAD

**Issue by cip123** [200ok-ch/organice#968]
I plan to use Organice mainly on my computer, with a keyboard and mouse.
Ideally, I would like to write markdown without being confined by any boxes. I would also love to use mouse-click events to toggle TODO states, checkboxes, insert dates, etc. 

However, most of the functionality is tailored for mobile, having controls for each action, which is limiting on desktop. 

Is there any plan for this kind of web-mode functionality?

**Comment by munen** [comment]
Hi @cip123 

Thank you for checking out organice :pray: 

The functionality you've mentioned exists exactly like that. Let me show you:


https://github.com/user-attachments/assets/97a474c6-dfe8-42ad-907c-bb2a3364cd3c

If you have further questions, feel free to re-open this issue.
