### ISSUE TITLE
Bookmarklets Javascript and Android Firefox sharing

### ISSUE THREAD

**Issue by ghost** [200ok-ch/organice#976]
Hi

I'd like to capture webpage from Android Firefox.
You give the JavaScript code, but I'm not a developer. Where should I put this code?

https://github.com/200ok-ch/organice#bookmarklets

Thank you

**Comment by schoettl** [comment]
Hi there,
[Wikipedia](https://en.wikipedia.org/wiki/Bookmarklet) describes what Bookmarklets are. I haven't tested if it works on Android Firefox but you can try. Only remember to change the relevant parts in the JavaScript code in the URL (capture template name, file name etc.).
