### ISSUE TITLE
Drawers should be collapsible

### ISSUE THREAD

**Issue by lckarssen** [200ok-ch/organice#98]
I use Org to [clock the time spent](https://orgmode.org/org.html#Clocking-Work-Time) on the work described in a certain heading. This creates a drawer of type `LOGBOOK` under the heading. Since some of my headings are long-term (or recurring) projects/tasks, the `LOGBOOK` drawer becomes very large (e.g. 220 lines in one case I checked). This obstructs the view of the actual text that is in the heading. 

A quick test shows this is the same for other [drawers](https://orgmode.org/org.html#Drawers) as well. 

Making drawers collapsible (like headings) would solve this issue, and I would argue that they should be collapsed by default.

**Comment by munen** [comment]
Good point. Personally, I'm still tracking time without drawers and have dedicated headers just for time tracking, so I never ran into this issue.

@lckarssen Would you be interested to work on that? I'd gladly do a review and pull the new functionality in.

**Comment by munen** [comment]
@lckarssen You are right! Personally, I haven't noticed this behavior, because I'm still tracking time without a drawer (the old pre Emacs 26 way) and in separate headers.

Having said that, organice can already do what you need for `:PROPERTIES:` drawers:

![demo](https://user-images.githubusercontent.com/505721/68541796-27794400-03a4-11ea-95a1-da4e57faf021.gif)

Would you be interested in making the functionality more generic for any kind of drawer?

**Comment by lckarssen** [comment]
Quick note: The current version on https://organice.200ok.ch/sample now implements collapsed `:LOGBOOK:` drawers. I guess this was part of PR #103. It doesn't work for other drawers yet. 

As for @munen's request whether I can work on this: I'm not sure. I have no experience with Javascript, so whatever I make would probably not look very good. I'm also a bit short on time. So if someone else want's to take a stab at this: please do!

**Comment by munen** [comment]
> Quick note: The current version on https://organice.200ok.ch/sample now implements collapsed :LOGBOOK: drawers. I guess this was part of PR #103. It doesn't work for other drawers yet.

Drawer logic works for all drawers that organice semantically understands. Those are `:PROPERTIES:` drawers and `:LOGBOOK:` by now. To make all drawers collapsible, it would be prudent to refactor the functionality from both of them into a new module. 

@lckarssen Thanks for your feedback. I understand it's not a good fit, then^^ As you said, anyone is free to pick this issue up, now.

**Comment by munen** [comment]
Both kinds of drawers can now be collapsed:

![image](https://user-images.githubusercontent.com/505721/80314334-42742f00-87f1-11ea-871e-d863a4a2c642.png)


![image](https://user-images.githubusercontent.com/505721/80314344-4dc75a80-87f1-11ea-928b-173b9b949a12.png)
