### ISSUE TITLE
Broken link in documentation

### ISSUE THREAD

**Issue by alexriabtsev** [200ok-ch/organice#986]
**Describe the bug**
Link to: https://docs.nextcloud.com/server/stable/user_manual/files/access_webdav.html?highlight=webdav gives File not found error. 

**To Reproduce**
1. Go to Documentation
2. Click on Link
3. See error

**Expected behavior**
Correct link to nextcloud doc.

**Comment by schoettl** [comment]
Thanks for the report.

Same for the [Seafile link](https://download.seafile.com/published/seafile-manual/extension/webdav.md), [on the same line in the README.org](https://github.com/200ok-ch/organice/blob/master/README.org?plain=1#L700).

Maybe someone can find the current version of these docs and provide a PR or just post them here...

**Comment by alexriabtsev** [comment]
I guess it shoudl be https://docs.nextcloud.com/server/latest/user_manual/en/files/access_webdav.html

**Comment by munen** [comment]
Hi everyone :wave: 

Thanks for the reports and looking up the new links :pray:  I just updated both Seafile and Nextcloud links in https://github.com/200ok-ch/organice/commit/1f43c1745138e79925468e8bdbe0d4eb93499c98.
