### ISSUE TITLE
press + then x, the sample file crashed

### ISSUE THREAD

**Issue by raymondelf** [200ok-ch/organice#988]
![Screenshot_2024-09-18-08-14-00-98_df198e732186825c8df26e3c5a10d7cd](https://github.com/user-attachments/assets/f478d99a-b107-4916-9d9f-0aca633ec224)

i was using edge on my phone.
trying sample page

 
![Screenshot_2024-09-18-08-16-16-85_df198e732186825c8df26e3c5a10d7cd](https://github.com/user-attachments/assets/7dfa05fd-e38c-4921-83a6-6fb36c0b7308)

**Comment by schoettl** [comment]
Thanks for the report.

Additional information:

- it's the list item editor
- it does not crash on Firefox 130 on Linux
- it does crash on Chrome and Firefox on Android

**Comment by raymondelf** [comment]
https://github.com/user-attachments/assets/43e2f700-04b8-414c-8846-ec3f8234db43

i closed my keyboard popping windows, it's crashed again.
i recorded a short video, maybe this could help.

**Comment by munen** [comment]
Hi @raymondelf 

Thank you for the bug report :pray:  I confirm the bug on iOS 17.6.1 on an iPhone 13 Pro.

I also cannot reproduce on the desktop. However, the '+ insert timestamp' feature doesn't even work for me on Firefox 128 Linux and Chromium 112 Linux:


https://github.com/user-attachments/assets/be726b0f-6094-4216-a0d5-2540f402d88a

**Comment by munen** [comment]
@kjmatsuda You are the master of the list item editor. Would you be interested in looking into this issue?

**Comment by kjmatsuda** [comment]
@munen OK, I will check this out.

**Comment by munen** [comment]
@kjmatsuda Amazing, thank you very much in advance :pray:

**Comment by kjmatsuda** [comment]
Hi @munen 

I’ve submitted a pull request to fix this issue:

fix: Prevent app crash when deleting a list item immediately after exiting edit mode 
https://github.com/200ok-ch/organice/pull/996

Could you take a look?

**Comment by kjmatsuda** [comment]
My pull request have some code format issues. I will fix that soon.

**Comment by munen** [comment]
@kjmatsuda Thank you very much :pray: Your fix works perfectly!

I'll merge, and add it to the changelog with attribution :bow:   

@raymondelf Thanks, again, for the initial bug report and getting involved with organice development :pray:
