### ISSUE TITLE
Allow users to clock in and out of a heading

### ISSUE THREAD

**Issue by lckarssen** [200ok-ch/organice#99]
I use Org to [clock the time spent](https://orgmode.org/org.html#Clocking-Work-Time) on the work described in a certain heading. It would be great if Organice gets functionality for clocking in and out of tasks/headings. 

An additional point on my wish list would be a way to select from the last e.g. 5 recently clocked tasks when clocking in (i.e. mimicking the behaviour of `C-u C-c C-x C-i`)

**Comment by munen** [comment]
@lckarssen I'm doing the same in Emacs(; I even have some custom elisp to export those times into a CSV which will later be processed by other tools: https://github.com/munen/emacs.d/#org-mode-exports

I agree, it would be nice if the functionality would be integrated in organice. Would you be interested in working on this feature in organice? I'll gladly give feedback and do a review of it.

**Comment by jamesnvc** [comment]
Hello! I also wanted this feature, so I took a crack at it at the above-linked PR.

**Comment by munen** [comment]
This feature has been perfectly implemented by @jamesnvc in this PR: #103 

The PR has been merged and the functionality is available on https://organice.200ok.ch

Thank you for the amazing work and contribution, @jamesnvc :pray: :bowing_man:

**Comment by lckarssen** [comment]
Thanks @jamesnvc! I hadn't had time to look into it yet. Glad you implemented it this quickly!
