### ISSUE TITLE
organice doesn

### ISSUE THREAD

**Issue by jibal** [200ok-ch/organice#990]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by schoettl** [comment]
Invalid bug report.

**Comment by jibal** [comment]
> Invalid bug report.

My finger slipped ... I've fixed it. Please reopen.

**Comment by munen** [comment]
Hi @jibal 

You are correct, organice does not understand header links. In fact, it does not support internal links. So, even if you were to use CUSTOM_IDs like so:

```
* Header 1
:PROPERTIES:
:CUSTOM_ID: foo
:END:


* Header 2

Link to [[#foo]].
```

organice will read the link as a link and try to open it in a new tab.

Would you be interested to build this feature?

NB: Please take a look at https://organice.200ok.ch/documentation.html#contributing

**Comment by jibal** [comment]
I only just discovered organice ... I'll have to think about it.

**Comment by munen** [comment]
Sure, take your time, get to know organice more and see if you like it :+1:
